namespace WinRTAdapter
{
[default_interface]
runtimeclass DispatchAdapter : Microsoft.Web.WebView2.Core.ICoreWebView2DispatchAdapter
{
    DispatchAdapter();
}

// Attribute applied to properties to indicate that their value
// won't change. This can be used as a hint to wv2winrt that
// the property value can be cached.
[attributeusage(target_property)]
[attributename("cacheable")]
attribute CacheableAttribute
{
}

}

