// WARNING: Please don't edit this file. It was generated by wv2winrt v1.0.0.0

#pragma once

#include "wv2winrt/converter.h"
#include "wv2winrt/remotedictionary.h"

// Must be included before any cppwinrt headers
#include <wv2winrt/base.h>

#include <winrt/Microsoft.Web.WebView2.Core.h>

namespace wv2winrt_impl
{

template <typename TIn, typename TOut> struct Converter;

static void GetDispId(::IDispatch* value, LPOLESTR* names, DISPID* dispId)
{
    HRESULT hr = value->GetIDsOfNames(IID_NULL, names, 1, LOCALE_USER_DEFAULT, dispId);

    if (hr == DISP_E_UNKNOWNNAME)
    {
        std::wstring message(L"Could not convert object to struct: object missing expected property '");
        message += std::wstring(*names) + L"'";
        throw winrt::hresult_error(hr, {message});
    }
    winrt::check_hresult(hr);
}

}
#include "winrt/Windows.Foundation.h"


namespace wv2winrt_impl
{

template<>
struct Converter<ICoreWebView2PrivateRemoteDictionary*, winrt::hresult>
{
    Converter(const winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter&
                    dispatchAdapter)
        : m_dispatchAdapter(dispatchAdapter)
    {
    }

    winrt::hresult Convert(ICoreWebView2PrivateRemoteDictionary* value)
    {
        winrt::com_ptr<::IDispatch> valueAsIDispatch;
        winrt::check_hresult(value->QueryInterface(IID_PPV_ARGS(valueAsIDispatch.put())));

        LPOLESTR names1 = const_cast<LPOLESTR>(L"Value");
        DISPID dispid1 = 0;
        GetDispId(valueAsIDispatch.get(), &names1, &dispid1);

        VARIANT result1;
        EXCEPINFO excepInfo1;
        winrt::check_hresult(valueAsIDispatch->Invoke(dispid1, IID_NULL, LOCALE_USER_DEFAULT, DISPATCH_PROPERTYGET, NULL, &result1, &excepInfo1, NULL));


        return {
            Converter<VARIANT, int32_t>(m_dispatchAdapter).Convert(result1)
        };
    }

    winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter m_dispatchAdapter;
};

}

namespace wv2winrt_impl
{

template<>
struct Converter<ICoreWebView2PrivateRemoteDictionary*, winrt::Windows::Foundation::Point>
{
    Converter(const winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter&
                    dispatchAdapter)
        : m_dispatchAdapter(dispatchAdapter)
    {
    }

    winrt::Windows::Foundation::Point Convert(ICoreWebView2PrivateRemoteDictionary* value)
    {
        winrt::com_ptr<::IDispatch> valueAsIDispatch;
        winrt::check_hresult(value->QueryInterface(IID_PPV_ARGS(valueAsIDispatch.put())));

        LPOLESTR names1 = const_cast<LPOLESTR>(L"X");
        DISPID dispid1 = 0;
        GetDispId(valueAsIDispatch.get(), &names1, &dispid1);

        VARIANT result1;
        EXCEPINFO excepInfo1;
        winrt::check_hresult(valueAsIDispatch->Invoke(dispid1, IID_NULL, LOCALE_USER_DEFAULT, DISPATCH_PROPERTYGET, NULL, &result1, &excepInfo1, NULL));

        LPOLESTR names2 = const_cast<LPOLESTR>(L"Y");
        DISPID dispid2 = 0;
        GetDispId(valueAsIDispatch.get(), &names2, &dispid2);

        VARIANT result2;
        EXCEPINFO excepInfo2;
        winrt::check_hresult(valueAsIDispatch->Invoke(dispid2, IID_NULL, LOCALE_USER_DEFAULT, DISPATCH_PROPERTYGET, NULL, &result2, &excepInfo2, NULL));


        return {
            Converter<VARIANT, float>(m_dispatchAdapter).Convert(result1),
            Converter<VARIANT, float>(m_dispatchAdapter).Convert(result2)
        };
    }

    winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter m_dispatchAdapter;
};

}

namespace wv2winrt_impl
{

template<>
struct Converter<ICoreWebView2PrivateRemoteDictionary*, winrt::Windows::Foundation::Size>
{
    Converter(const winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter&
                    dispatchAdapter)
        : m_dispatchAdapter(dispatchAdapter)
    {
    }

    winrt::Windows::Foundation::Size Convert(ICoreWebView2PrivateRemoteDictionary* value)
    {
        winrt::com_ptr<::IDispatch> valueAsIDispatch;
        winrt::check_hresult(value->QueryInterface(IID_PPV_ARGS(valueAsIDispatch.put())));

        LPOLESTR names1 = const_cast<LPOLESTR>(L"Width");
        DISPID dispid1 = 0;
        GetDispId(valueAsIDispatch.get(), &names1, &dispid1);

        VARIANT result1;
        EXCEPINFO excepInfo1;
        winrt::check_hresult(valueAsIDispatch->Invoke(dispid1, IID_NULL, LOCALE_USER_DEFAULT, DISPATCH_PROPERTYGET, NULL, &result1, &excepInfo1, NULL));

        LPOLESTR names2 = const_cast<LPOLESTR>(L"Height");
        DISPID dispid2 = 0;
        GetDispId(valueAsIDispatch.get(), &names2, &dispid2);

        VARIANT result2;
        EXCEPINFO excepInfo2;
        winrt::check_hresult(valueAsIDispatch->Invoke(dispid2, IID_NULL, LOCALE_USER_DEFAULT, DISPATCH_PROPERTYGET, NULL, &result2, &excepInfo2, NULL));


        return {
            Converter<VARIANT, float>(m_dispatchAdapter).Convert(result1),
            Converter<VARIANT, float>(m_dispatchAdapter).Convert(result2)
        };
    }

    winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter m_dispatchAdapter;
};

}

namespace wv2winrt_impl
{

template<>
struct Converter<ICoreWebView2PrivateRemoteDictionary*, winrt::Windows::Foundation::Rect>
{
    Converter(const winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter&
                    dispatchAdapter)
        : m_dispatchAdapter(dispatchAdapter)
    {
    }

    winrt::Windows::Foundation::Rect Convert(ICoreWebView2PrivateRemoteDictionary* value)
    {
        winrt::com_ptr<::IDispatch> valueAsIDispatch;
        winrt::check_hresult(value->QueryInterface(IID_PPV_ARGS(valueAsIDispatch.put())));

        LPOLESTR names1 = const_cast<LPOLESTR>(L"X");
        DISPID dispid1 = 0;
        GetDispId(valueAsIDispatch.get(), &names1, &dispid1);

        VARIANT result1;
        EXCEPINFO excepInfo1;
        winrt::check_hresult(valueAsIDispatch->Invoke(dispid1, IID_NULL, LOCALE_USER_DEFAULT, DISPATCH_PROPERTYGET, NULL, &result1, &excepInfo1, NULL));

        LPOLESTR names2 = const_cast<LPOLESTR>(L"Y");
        DISPID dispid2 = 0;
        GetDispId(valueAsIDispatch.get(), &names2, &dispid2);

        VARIANT result2;
        EXCEPINFO excepInfo2;
        winrt::check_hresult(valueAsIDispatch->Invoke(dispid2, IID_NULL, LOCALE_USER_DEFAULT, DISPATCH_PROPERTYGET, NULL, &result2, &excepInfo2, NULL));

        LPOLESTR names3 = const_cast<LPOLESTR>(L"Width");
        DISPID dispid3 = 0;
        GetDispId(valueAsIDispatch.get(), &names3, &dispid3);

        VARIANT result3;
        EXCEPINFO excepInfo3;
        winrt::check_hresult(valueAsIDispatch->Invoke(dispid3, IID_NULL, LOCALE_USER_DEFAULT, DISPATCH_PROPERTYGET, NULL, &result3, &excepInfo3, NULL));

        LPOLESTR names4 = const_cast<LPOLESTR>(L"Height");
        DISPID dispid4 = 0;
        GetDispId(valueAsIDispatch.get(), &names4, &dispid4);

        VARIANT result4;
        EXCEPINFO excepInfo4;
        winrt::check_hresult(valueAsIDispatch->Invoke(dispid4, IID_NULL, LOCALE_USER_DEFAULT, DISPATCH_PROPERTYGET, NULL, &result4, &excepInfo4, NULL));


        return {
            Converter<VARIANT, float>(m_dispatchAdapter).Convert(result1),
            Converter<VARIANT, float>(m_dispatchAdapter).Convert(result2),
            Converter<VARIANT, float>(m_dispatchAdapter).Convert(result3),
            Converter<VARIANT, float>(m_dispatchAdapter).Convert(result4)
        };
    }

    winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter m_dispatchAdapter;
};

}


#include "winrt/Windows.Storage.Search.h"


namespace wv2winrt_impl
{

template<>
struct Converter<ICoreWebView2PrivateRemoteDictionary*, winrt::Windows::Storage::Search::SortEntry>
{
    Converter(const winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter&
                    dispatchAdapter)
        : m_dispatchAdapter(dispatchAdapter)
    {
    }

    winrt::Windows::Storage::Search::SortEntry Convert(ICoreWebView2PrivateRemoteDictionary* value)
    {
        winrt::com_ptr<::IDispatch> valueAsIDispatch;
        winrt::check_hresult(value->QueryInterface(IID_PPV_ARGS(valueAsIDispatch.put())));

        LPOLESTR names1 = const_cast<LPOLESTR>(L"PropertyName");
        DISPID dispid1 = 0;
        GetDispId(valueAsIDispatch.get(), &names1, &dispid1);

        VARIANT result1;
        EXCEPINFO excepInfo1;
        winrt::check_hresult(valueAsIDispatch->Invoke(dispid1, IID_NULL, LOCALE_USER_DEFAULT, DISPATCH_PROPERTYGET, NULL, &result1, &excepInfo1, NULL));

        LPOLESTR names2 = const_cast<LPOLESTR>(L"AscendingOrder");
        DISPID dispid2 = 0;
        GetDispId(valueAsIDispatch.get(), &names2, &dispid2);

        VARIANT result2;
        EXCEPINFO excepInfo2;
        winrt::check_hresult(valueAsIDispatch->Invoke(dispid2, IID_NULL, LOCALE_USER_DEFAULT, DISPATCH_PROPERTYGET, NULL, &result2, &excepInfo2, NULL));


        return {
            Converter<VARIANT, winrt::hstring>(m_dispatchAdapter).Convert(result1),
            Converter<VARIANT, bool>(m_dispatchAdapter).Convert(result2)
        };
    }

    winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter m_dispatchAdapter;
};

}


#include "winrt/Windows.Data.Text.h"


namespace wv2winrt_impl
{

template<>
struct Converter<ICoreWebView2PrivateRemoteDictionary*, winrt::Windows::Data::Text::TextSegment>
{
    Converter(const winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter&
                    dispatchAdapter)
        : m_dispatchAdapter(dispatchAdapter)
    {
    }

    winrt::Windows::Data::Text::TextSegment Convert(ICoreWebView2PrivateRemoteDictionary* value)
    {
        winrt::com_ptr<::IDispatch> valueAsIDispatch;
        winrt::check_hresult(value->QueryInterface(IID_PPV_ARGS(valueAsIDispatch.put())));

        LPOLESTR names1 = const_cast<LPOLESTR>(L"StartPosition");
        DISPID dispid1 = 0;
        GetDispId(valueAsIDispatch.get(), &names1, &dispid1);

        VARIANT result1;
        EXCEPINFO excepInfo1;
        winrt::check_hresult(valueAsIDispatch->Invoke(dispid1, IID_NULL, LOCALE_USER_DEFAULT, DISPATCH_PROPERTYGET, NULL, &result1, &excepInfo1, NULL));

        LPOLESTR names2 = const_cast<LPOLESTR>(L"Length");
        DISPID dispid2 = 0;
        GetDispId(valueAsIDispatch.get(), &names2, &dispid2);

        VARIANT result2;
        EXCEPINFO excepInfo2;
        winrt::check_hresult(valueAsIDispatch->Invoke(dispid2, IID_NULL, LOCALE_USER_DEFAULT, DISPATCH_PROPERTYGET, NULL, &result2, &excepInfo2, NULL));


        return {
            Converter<VARIANT, uint32_t>(m_dispatchAdapter).Convert(result1),
            Converter<VARIANT, uint32_t>(m_dispatchAdapter).Convert(result2)
        };
    }

    winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter m_dispatchAdapter;
};

}



