// WARNING: Please don't edit this file. It was generated by wv2winrt v1.0.0.0
#pragma once

#include "wv2winrt/dispatchbase.h"
#include "wv2winrt/dispatchcollectionhelpers.h"
#include <functional>
#include "wv2winrt/base.h"
#include "winrt/NativeCode.h"


namespace wv2winrt_impl
{
struct Namespace_NativeCode : winrt::implements<Namespace_NativeCode, DispatchBase>
{
    public:
        Namespace_NativeCode(const winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter& dispatchAdapter);

        // IDispatch methods
        HRESULT STDMETHODCALLTYPE GetIDsOfNames(REFIID riid,
                                                LPOLESTR* names,
                                                unsigned int namesCount,
                                                LCID localeId,
                                                DISPID* dispId);

        HRESULT STDMETHODCALLTYPE Invoke(DISPID dispId,
                                         REFIID riid,
                                         LCID localeId,
                                         WORD flags,
                                         DISPPARAMS* dispParams,
                                         VARIANT* result,
                                         EXCEPINFO* excepInfo,
                                         UINT* argErr);
        // ICoreWebView2PrivateDispatchContainer methods
        HRESULT STDMETHODCALLTYPE GetPropertyNames(wchar_t***, size_t*);

    private:
        winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter m_dispatchAdapter;
        static DispatchProperties s_dispatchProperties;
        static const DISPID s_dispatchIds[];
};
}

namespace wv2winrt_impl
{
struct Class_NativeCode_PlayWithNumbers : winrt::implements<
    Class_NativeCode_PlayWithNumbers,
    DispatchBase>
{
    public:
        Class_NativeCode_PlayWithNumbers(::IInspectable* innerObject, const winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter& dispatchAdapter);

        // IDispatch methods
        HRESULT STDMETHODCALLTYPE GetIDsOfNames(REFIID riid,
                                                LPOLESTR* names,
                                                unsigned int namesCount,
                                                LCID localeId,
                                                DISPID* dispId) override;
        HRESULT STDMETHODCALLTYPE Invoke(DISPID dispId,
                                         REFIID riid,
                                         LCID localeId,
                                         WORD flags,
                                         DISPPARAMS* dispParams,
                                         VARIANT* result,
                                         EXCEPINFO* excepInfo,
                                         UINT* argErr) override;

        // ICoreWebView2PrivateDispatchContainer methods
        HRESULT STDMETHODCALLTYPE GetInnerObject(IUnknown** object) override;
        HRESULT STDMETHODCALLTYPE GetPropertyNames(wchar_t***, size_t*);
        HRESULT STDMETHODCALLTYPE GetPropertiesPrecacheability(BOOL** boolsOut, size_t* propertiesLengthOut);

    private:
        winrt::com_ptr<::IInspectable> m_innerObject;
        winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter m_dispatchAdapter;
        static DispatchProperties s_dispatchProperties;
        static const DISPID s_dispatchIds[];
        static const int s_precacheableProperties[];
};
}

namespace wv2winrt_impl
{
struct Class_NativeCode_IPlayWithNumbers : winrt::implements<
    Class_NativeCode_IPlayWithNumbers,
    DispatchBase>
{
    public:
        Class_NativeCode_IPlayWithNumbers(::IInspectable* innerObject, const winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter& dispatchAdapter);

        // IDispatch methods
        HRESULT STDMETHODCALLTYPE GetIDsOfNames(REFIID riid,
                                                LPOLESTR* names,
                                                unsigned int namesCount,
                                                LCID localeId,
                                                DISPID* dispId) override;
        HRESULT STDMETHODCALLTYPE Invoke(DISPID dispId,
                                         REFIID riid,
                                         LCID localeId,
                                         WORD flags,
                                         DISPPARAMS* dispParams,
                                         VARIANT* result,
                                         EXCEPINFO* excepInfo,
                                         UINT* argErr) override;

        // ICoreWebView2PrivateDispatchContainer methods
        HRESULT STDMETHODCALLTYPE GetInnerObject(IUnknown** object) override;
        HRESULT STDMETHODCALLTYPE GetPropertyNames(wchar_t***, size_t*);
        HRESULT STDMETHODCALLTYPE GetPropertiesPrecacheability(BOOL** boolsOut, size_t* propertiesLengthOut);

    private:
        winrt::com_ptr<::IInspectable> m_innerObject;
        winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter m_dispatchAdapter;
        static DispatchProperties s_dispatchProperties;
        static const DISPID s_dispatchIds[];
        static const int s_precacheableProperties[];
};
}
namespace wv2winrt_impl
{
struct Static_Class_NativeCode_PlayWithNumbers : winrt::implements<Static_Class_NativeCode_PlayWithNumbers, DispatchBase>
{
    public:
        Static_Class_NativeCode_PlayWithNumbers(const winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter& dispatchAdapter);

        HRESULT STDMETHODCALLTYPE GetIDsOfNames(REFIID riid,
                                                LPOLESTR* names,
                                                unsigned int namesCount,
                                                LCID localeId,
                                                DISPID* dispId) override;
        HRESULT STDMETHODCALLTYPE Invoke(DISPID dispId,
                                         REFIID riid,
                                         LCID localeId,
                                         WORD flags,
                                         DISPPARAMS* dispParams,
                                         VARIANT* result,
                                         EXCEPINFO* excepInfo,
                                         UINT* argErr) override;

        // ICoreWebView2PrivateDispatchContainer methods
        HRESULT STDMETHODCALLTYPE GetPropertyNames(wchar_t***, size_t*);

    private:
        winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter m_dispatchAdapter;
        static DispatchProperties s_dispatchProperties;
        static const DISPID s_dispatchIds[];
};
}
