// WARNING: Please don't edit this file. It was generated by wv2winrt v1.0.0.0
#pragma once

#include "wv2winrt/dispatchbase.h"
#include "wv2winrt/dispatchcollectionhelpers.h"
#include <functional>
#include "wv2winrt/base.h"
#include "winrt/Windows.Data.Text.h"


namespace wv2winrt_impl
{
struct Namespace_Windows_Data_Text : winrt::implements<Namespace_Windows_Data_Text, DispatchBase>
{
    public:
        Namespace_Windows_Data_Text(const winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter& dispatchAdapter);

        // IDispatch methods
        HRESULT STDMETHODCALLTYPE GetIDsOfNames(REFIID riid,
                                                LPOLESTR* names,
                                                unsigned int namesCount,
                                                LCID localeId,
                                                DISPID* dispId);

        HRESULT STDMETHODCALLTYPE Invoke(DISPID dispId,
                                         REFIID riid,
                                         LCID localeId,
                                         WORD flags,
                                         DISPPARAMS* dispParams,
                                         VARIANT* result,
                                         EXCEPINFO* excepInfo,
                                         UINT* argErr);
        // ICoreWebView2PrivateDispatchContainer methods
        HRESULT STDMETHODCALLTYPE GetPropertyNames(wchar_t***, size_t*);

    private:
        winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter m_dispatchAdapter;
        static DispatchProperties s_dispatchProperties;
        static const DISPID s_dispatchIds[];
};
}
namespace wv2winrt_impl
{

struct Struct_Windows_Data_Text_TextSegment : winrt::implements<
    Struct_Windows_Data_Text_TextSegment,
    DispatchBase>
{
    public:
        Struct_Windows_Data_Text_TextSegment(winrt::Windows::Data::Text::TextSegment innerObject, const winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter& dispatchAdapter);

        // IDispatch methods
        HRESULT STDMETHODCALLTYPE GetIDsOfNames(REFIID riid,
                                                LPOLESTR* names,
                                                unsigned int namesCount,
                                                LCID localeId,
                                                DISPID* dispId) override;
        HRESULT STDMETHODCALLTYPE Invoke(DISPID dispId,
                                         REFIID riid,
                                         LCID localeId,
                                         WORD flags,
                                         DISPPARAMS* dispParams,
                                         VARIANT* result,
                                         EXCEPINFO* excepInfo,
                                         UINT* argErr) override;

        // ICoreWebView2PrivateDispatchContainer methods
        HRESULT STDMETHODCALLTYPE GetInnerObject(IUnknown** object) override;
        HRESULT STDMETHODCALLTYPE GetPropertyNames(wchar_t***, size_t*);

    private:
        winrt::Windows::Data::Text::TextSegment m_innerObject;
        winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter m_dispatchAdapter;
        static DispatchProperties s_dispatchProperties;
        static const DISPID s_dispatchIds[];
};

}

