// WARNING: Please don't edit this file. It was generated by wv2winrt v1.0.0.0
#pragma once

#include "wv2winrt/dispatchbase.h"
#include "wv2winrt/dispatchcollectionhelpers.h"
#include <functional>
#include "wv2winrt/base.h"
#include "winrt/Windows.Storage.h"


namespace wv2winrt_impl
{
struct Namespace_Windows_Storage : winrt::implements<Namespace_Windows_Storage, DispatchBase>
{
    public:
        Namespace_Windows_Storage(const winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter& dispatchAdapter);

        // IDispatch methods
        HRESULT STDMETHODCALLTYPE GetIDsOfNames(REFIID riid,
                                                LPOLESTR* names,
                                                unsigned int namesCount,
                                                LCID localeId,
                                                DISPID* dispId);

        HRESULT STDMETHODCALLTYPE Invoke(DISPID dispId,
                                         REFIID riid,
                                         LCID localeId,
                                         WORD flags,
                                         DISPPARAMS* dispParams,
                                         VARIANT* result,
                                         EXCEPINFO* excepInfo,
                                         UINT* argErr);
        // ICoreWebView2PrivateDispatchContainer methods
        HRESULT STDMETHODCALLTYPE GetPropertyNames(wchar_t***, size_t*);

    private:
        winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter m_dispatchAdapter;
        static DispatchProperties s_dispatchProperties;
        static const DISPID s_dispatchIds[];
};
}
namespace wv2winrt_impl
{
struct Enum_Windows_Storage_FileAccessMode : winrt::implements<Enum_Windows_Storage_FileAccessMode, DispatchBase>
{
    public:
        Enum_Windows_Storage_FileAccessMode(const winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter&);

        HRESULT STDMETHODCALLTYPE GetIDsOfNames(REFIID riid,
                                                LPOLESTR* names,
                                                unsigned int namesCount,
                                                LCID localeId,
                                                DISPID* dispId) override;
        HRESULT STDMETHODCALLTYPE Invoke(DISPID dispId,
                                         REFIID riid,
                                         LCID localeId,
                                         WORD flags,
                                         DISPPARAMS* dispParams,
                                         VARIANT* result,
                                         EXCEPINFO* excepInfo,
                                         UINT* argErr) override;

        // ICoreWebView2PrivateDispatchContainer methods
        HRESULT STDMETHODCALLTYPE GetPropertyNames(wchar_t***, size_t*);

    private:
        static DispatchProperties s_dispatchProperties;
        static const DISPID s_dispatchIds[];
};
}
namespace wv2winrt_impl
{
struct Enum_Windows_Storage_NameCollisionOption : winrt::implements<Enum_Windows_Storage_NameCollisionOption, DispatchBase>
{
    public:
        Enum_Windows_Storage_NameCollisionOption(const winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter&);

        HRESULT STDMETHODCALLTYPE GetIDsOfNames(REFIID riid,
                                                LPOLESTR* names,
                                                unsigned int namesCount,
                                                LCID localeId,
                                                DISPID* dispId) override;
        HRESULT STDMETHODCALLTYPE Invoke(DISPID dispId,
                                         REFIID riid,
                                         LCID localeId,
                                         WORD flags,
                                         DISPPARAMS* dispParams,
                                         VARIANT* result,
                                         EXCEPINFO* excepInfo,
                                         UINT* argErr) override;

        // ICoreWebView2PrivateDispatchContainer methods
        HRESULT STDMETHODCALLTYPE GetPropertyNames(wchar_t***, size_t*);

    private:
        static DispatchProperties s_dispatchProperties;
        static const DISPID s_dispatchIds[];
};
}
namespace wv2winrt_impl
{
struct Enum_Windows_Storage_StorageDeleteOption : winrt::implements<Enum_Windows_Storage_StorageDeleteOption, DispatchBase>
{
    public:
        Enum_Windows_Storage_StorageDeleteOption(const winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter&);

        HRESULT STDMETHODCALLTYPE GetIDsOfNames(REFIID riid,
                                                LPOLESTR* names,
                                                unsigned int namesCount,
                                                LCID localeId,
                                                DISPID* dispId) override;
        HRESULT STDMETHODCALLTYPE Invoke(DISPID dispId,
                                         REFIID riid,
                                         LCID localeId,
                                         WORD flags,
                                         DISPPARAMS* dispParams,
                                         VARIANT* result,
                                         EXCEPINFO* excepInfo,
                                         UINT* argErr) override;

        // ICoreWebView2PrivateDispatchContainer methods
        HRESULT STDMETHODCALLTYPE GetPropertyNames(wchar_t***, size_t*);

    private:
        static DispatchProperties s_dispatchProperties;
        static const DISPID s_dispatchIds[];
};
}
namespace wv2winrt_impl
{
struct Enum_Windows_Storage_StorageItemTypes : winrt::implements<Enum_Windows_Storage_StorageItemTypes, DispatchBase>
{
    public:
        Enum_Windows_Storage_StorageItemTypes(const winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter&);

        HRESULT STDMETHODCALLTYPE GetIDsOfNames(REFIID riid,
                                                LPOLESTR* names,
                                                unsigned int namesCount,
                                                LCID localeId,
                                                DISPID* dispId) override;
        HRESULT STDMETHODCALLTYPE Invoke(DISPID dispId,
                                         REFIID riid,
                                         LCID localeId,
                                         WORD flags,
                                         DISPPARAMS* dispParams,
                                         VARIANT* result,
                                         EXCEPINFO* excepInfo,
                                         UINT* argErr) override;

        // ICoreWebView2PrivateDispatchContainer methods
        HRESULT STDMETHODCALLTYPE GetPropertyNames(wchar_t***, size_t*);

    private:
        static DispatchProperties s_dispatchProperties;
        static const DISPID s_dispatchIds[];
};
}
namespace wv2winrt_impl
{
struct Enum_Windows_Storage_StorageOpenOptions : winrt::implements<Enum_Windows_Storage_StorageOpenOptions, DispatchBase>
{
    public:
        Enum_Windows_Storage_StorageOpenOptions(const winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter&);

        HRESULT STDMETHODCALLTYPE GetIDsOfNames(REFIID riid,
                                                LPOLESTR* names,
                                                unsigned int namesCount,
                                                LCID localeId,
                                                DISPID* dispId) override;
        HRESULT STDMETHODCALLTYPE Invoke(DISPID dispId,
                                         REFIID riid,
                                         LCID localeId,
                                         WORD flags,
                                         DISPPARAMS* dispParams,
                                         VARIANT* result,
                                         EXCEPINFO* excepInfo,
                                         UINT* argErr) override;

        // ICoreWebView2PrivateDispatchContainer methods
        HRESULT STDMETHODCALLTYPE GetPropertyNames(wchar_t***, size_t*);

    private:
        static DispatchProperties s_dispatchProperties;
        static const DISPID s_dispatchIds[];
};
}
namespace wv2winrt_impl
{
struct Enum_Windows_Storage_FileAttributes : winrt::implements<Enum_Windows_Storage_FileAttributes, DispatchBase>
{
    public:
        Enum_Windows_Storage_FileAttributes(const winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter&);

        HRESULT STDMETHODCALLTYPE GetIDsOfNames(REFIID riid,
                                                LPOLESTR* names,
                                                unsigned int namesCount,
                                                LCID localeId,
                                                DISPID* dispId) override;
        HRESULT STDMETHODCALLTYPE Invoke(DISPID dispId,
                                         REFIID riid,
                                         LCID localeId,
                                         WORD flags,
                                         DISPPARAMS* dispParams,
                                         VARIANT* result,
                                         EXCEPINFO* excepInfo,
                                         UINT* argErr) override;

        // ICoreWebView2PrivateDispatchContainer methods
        HRESULT STDMETHODCALLTYPE GetPropertyNames(wchar_t***, size_t*);

    private:
        static DispatchProperties s_dispatchProperties;
        static const DISPID s_dispatchIds[];
};
}
namespace wv2winrt_impl
{
struct Enum_Windows_Storage_CreationCollisionOption : winrt::implements<Enum_Windows_Storage_CreationCollisionOption, DispatchBase>
{
    public:
        Enum_Windows_Storage_CreationCollisionOption(const winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter&);

        HRESULT STDMETHODCALLTYPE GetIDsOfNames(REFIID riid,
                                                LPOLESTR* names,
                                                unsigned int namesCount,
                                                LCID localeId,
                                                DISPID* dispId) override;
        HRESULT STDMETHODCALLTYPE Invoke(DISPID dispId,
                                         REFIID riid,
                                         LCID localeId,
                                         WORD flags,
                                         DISPPARAMS* dispParams,
                                         VARIANT* result,
                                         EXCEPINFO* excepInfo,
                                         UINT* argErr) override;

        // ICoreWebView2PrivateDispatchContainer methods
        HRESULT STDMETHODCALLTYPE GetPropertyNames(wchar_t***, size_t*);

    private:
        static DispatchProperties s_dispatchProperties;
        static const DISPID s_dispatchIds[];
};
}
namespace wv2winrt_impl
{
struct Enum_Windows_Storage_StorageLibraryChangeType : winrt::implements<Enum_Windows_Storage_StorageLibraryChangeType, DispatchBase>
{
    public:
        Enum_Windows_Storage_StorageLibraryChangeType(const winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter&);

        HRESULT STDMETHODCALLTYPE GetIDsOfNames(REFIID riid,
                                                LPOLESTR* names,
                                                unsigned int namesCount,
                                                LCID localeId,
                                                DISPID* dispId) override;
        HRESULT STDMETHODCALLTYPE Invoke(DISPID dispId,
                                         REFIID riid,
                                         LCID localeId,
                                         WORD flags,
                                         DISPPARAMS* dispParams,
                                         VARIANT* result,
                                         EXCEPINFO* excepInfo,
                                         UINT* argErr) override;

        // ICoreWebView2PrivateDispatchContainer methods
        HRESULT STDMETHODCALLTYPE GetPropertyNames(wchar_t***, size_t*);

    private:
        static DispatchProperties s_dispatchProperties;
        static const DISPID s_dispatchIds[];
};
}

namespace wv2winrt_impl
{
struct Class_Windows_Storage_StorageFile : winrt::implements<
    Class_Windows_Storage_StorageFile,
    DispatchBase>
{
    public:
        Class_Windows_Storage_StorageFile(::IInspectable* innerObject, const winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter& dispatchAdapter);

        // IDispatch methods
        HRESULT STDMETHODCALLTYPE GetIDsOfNames(REFIID riid,
                                                LPOLESTR* names,
                                                unsigned int namesCount,
                                                LCID localeId,
                                                DISPID* dispId) override;
        HRESULT STDMETHODCALLTYPE Invoke(DISPID dispId,
                                         REFIID riid,
                                         LCID localeId,
                                         WORD flags,
                                         DISPPARAMS* dispParams,
                                         VARIANT* result,
                                         EXCEPINFO* excepInfo,
                                         UINT* argErr) override;

        // ICoreWebView2PrivateDispatchContainer methods
        HRESULT STDMETHODCALLTYPE GetInnerObject(IUnknown** object) override;
        HRESULT STDMETHODCALLTYPE GetPropertyNames(wchar_t***, size_t*);
        HRESULT STDMETHODCALLTYPE GetPropertiesPrecacheability(BOOL** boolsOut, size_t* propertiesLengthOut);

    private:
        winrt::com_ptr<::IInspectable> m_innerObject;
        winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter m_dispatchAdapter;
        static DispatchProperties s_dispatchProperties;
        static const DISPID s_dispatchIds[];
        static const int s_precacheableProperties[];
};
}

namespace wv2winrt_impl
{
struct Class_Windows_Storage_IStorageFile : winrt::implements<
    Class_Windows_Storage_IStorageFile,
    DispatchBase>
{
    public:
        Class_Windows_Storage_IStorageFile(::IInspectable* innerObject, const winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter& dispatchAdapter);

        // IDispatch methods
        HRESULT STDMETHODCALLTYPE GetIDsOfNames(REFIID riid,
                                                LPOLESTR* names,
                                                unsigned int namesCount,
                                                LCID localeId,
                                                DISPID* dispId) override;
        HRESULT STDMETHODCALLTYPE Invoke(DISPID dispId,
                                         REFIID riid,
                                         LCID localeId,
                                         WORD flags,
                                         DISPPARAMS* dispParams,
                                         VARIANT* result,
                                         EXCEPINFO* excepInfo,
                                         UINT* argErr) override;

        // ICoreWebView2PrivateDispatchContainer methods
        HRESULT STDMETHODCALLTYPE GetInnerObject(IUnknown** object) override;
        HRESULT STDMETHODCALLTYPE GetPropertyNames(wchar_t***, size_t*);
        HRESULT STDMETHODCALLTYPE GetPropertiesPrecacheability(BOOL** boolsOut, size_t* propertiesLengthOut);

    private:
        winrt::com_ptr<::IInspectable> m_innerObject;
        winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter m_dispatchAdapter;
        static DispatchProperties s_dispatchProperties;
        static const DISPID s_dispatchIds[];
        static const int s_precacheableProperties[];
};
}

namespace wv2winrt_impl
{
struct Class_Windows_Storage_IStorageFolder : winrt::implements<
    Class_Windows_Storage_IStorageFolder,
    DispatchBase>
{
    public:
        Class_Windows_Storage_IStorageFolder(::IInspectable* innerObject, const winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter& dispatchAdapter);

        // IDispatch methods
        HRESULT STDMETHODCALLTYPE GetIDsOfNames(REFIID riid,
                                                LPOLESTR* names,
                                                unsigned int namesCount,
                                                LCID localeId,
                                                DISPID* dispId) override;
        HRESULT STDMETHODCALLTYPE Invoke(DISPID dispId,
                                         REFIID riid,
                                         LCID localeId,
                                         WORD flags,
                                         DISPPARAMS* dispParams,
                                         VARIANT* result,
                                         EXCEPINFO* excepInfo,
                                         UINT* argErr) override;

        // ICoreWebView2PrivateDispatchContainer methods
        HRESULT STDMETHODCALLTYPE GetInnerObject(IUnknown** object) override;
        HRESULT STDMETHODCALLTYPE GetPropertyNames(wchar_t***, size_t*);
        HRESULT STDMETHODCALLTYPE GetPropertiesPrecacheability(BOOL** boolsOut, size_t* propertiesLengthOut);

    private:
        winrt::com_ptr<::IInspectable> m_innerObject;
        winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter m_dispatchAdapter;
        static DispatchProperties s_dispatchProperties;
        static const DISPID s_dispatchIds[];
        static const int s_precacheableProperties[];
};
}

namespace wv2winrt_impl
{
struct Class_Windows_Storage_IStorageItem : winrt::implements<
    Class_Windows_Storage_IStorageItem,
    DispatchBase>
{
    public:
        Class_Windows_Storage_IStorageItem(::IInspectable* innerObject, const winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter& dispatchAdapter);

        // IDispatch methods
        HRESULT STDMETHODCALLTYPE GetIDsOfNames(REFIID riid,
                                                LPOLESTR* names,
                                                unsigned int namesCount,
                                                LCID localeId,
                                                DISPID* dispId) override;
        HRESULT STDMETHODCALLTYPE Invoke(DISPID dispId,
                                         REFIID riid,
                                         LCID localeId,
                                         WORD flags,
                                         DISPPARAMS* dispParams,
                                         VARIANT* result,
                                         EXCEPINFO* excepInfo,
                                         UINT* argErr) override;

        // ICoreWebView2PrivateDispatchContainer methods
        HRESULT STDMETHODCALLTYPE GetInnerObject(IUnknown** object) override;
        HRESULT STDMETHODCALLTYPE GetPropertyNames(wchar_t***, size_t*);
        HRESULT STDMETHODCALLTYPE GetPropertiesPrecacheability(BOOL** boolsOut, size_t* propertiesLengthOut);

    private:
        winrt::com_ptr<::IInspectable> m_innerObject;
        winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter m_dispatchAdapter;
        static DispatchProperties s_dispatchProperties;
        static const DISPID s_dispatchIds[];
        static const int s_precacheableProperties[];
};
}

namespace wv2winrt_impl
{
struct Class_Windows_Storage_IStorageItemProperties : winrt::implements<
    Class_Windows_Storage_IStorageItemProperties,
    DispatchBase>
{
    public:
        Class_Windows_Storage_IStorageItemProperties(::IInspectable* innerObject, const winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter& dispatchAdapter);

        // IDispatch methods
        HRESULT STDMETHODCALLTYPE GetIDsOfNames(REFIID riid,
                                                LPOLESTR* names,
                                                unsigned int namesCount,
                                                LCID localeId,
                                                DISPID* dispId) override;
        HRESULT STDMETHODCALLTYPE Invoke(DISPID dispId,
                                         REFIID riid,
                                         LCID localeId,
                                         WORD flags,
                                         DISPPARAMS* dispParams,
                                         VARIANT* result,
                                         EXCEPINFO* excepInfo,
                                         UINT* argErr) override;

        // ICoreWebView2PrivateDispatchContainer methods
        HRESULT STDMETHODCALLTYPE GetInnerObject(IUnknown** object) override;
        HRESULT STDMETHODCALLTYPE GetPropertyNames(wchar_t***, size_t*);
        HRESULT STDMETHODCALLTYPE GetPropertiesPrecacheability(BOOL** boolsOut, size_t* propertiesLengthOut);

    private:
        winrt::com_ptr<::IInspectable> m_innerObject;
        winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter m_dispatchAdapter;
        static DispatchProperties s_dispatchProperties;
        static const DISPID s_dispatchIds[];
        static const int s_precacheableProperties[];
};
}

namespace wv2winrt_impl
{
struct Class_Windows_Storage_IStorageItem2 : winrt::implements<
    Class_Windows_Storage_IStorageItem2,
    DispatchBase>
{
    public:
        Class_Windows_Storage_IStorageItem2(::IInspectable* innerObject, const winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter& dispatchAdapter);

        // IDispatch methods
        HRESULT STDMETHODCALLTYPE GetIDsOfNames(REFIID riid,
                                                LPOLESTR* names,
                                                unsigned int namesCount,
                                                LCID localeId,
                                                DISPID* dispId) override;
        HRESULT STDMETHODCALLTYPE Invoke(DISPID dispId,
                                         REFIID riid,
                                         LCID localeId,
                                         WORD flags,
                                         DISPPARAMS* dispParams,
                                         VARIANT* result,
                                         EXCEPINFO* excepInfo,
                                         UINT* argErr) override;

        // ICoreWebView2PrivateDispatchContainer methods
        HRESULT STDMETHODCALLTYPE GetInnerObject(IUnknown** object) override;
        HRESULT STDMETHODCALLTYPE GetPropertyNames(wchar_t***, size_t*);
        HRESULT STDMETHODCALLTYPE GetPropertiesPrecacheability(BOOL** boolsOut, size_t* propertiesLengthOut);

    private:
        winrt::com_ptr<::IInspectable> m_innerObject;
        winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter m_dispatchAdapter;
        static DispatchProperties s_dispatchProperties;
        static const DISPID s_dispatchIds[];
        static const int s_precacheableProperties[];
};
}

namespace wv2winrt_impl
{
struct Class_Windows_Storage_IStorageFile2 : winrt::implements<
    Class_Windows_Storage_IStorageFile2,
    DispatchBase>
{
    public:
        Class_Windows_Storage_IStorageFile2(::IInspectable* innerObject, const winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter& dispatchAdapter);

        // IDispatch methods
        HRESULT STDMETHODCALLTYPE GetIDsOfNames(REFIID riid,
                                                LPOLESTR* names,
                                                unsigned int namesCount,
                                                LCID localeId,
                                                DISPID* dispId) override;
        HRESULT STDMETHODCALLTYPE Invoke(DISPID dispId,
                                         REFIID riid,
                                         LCID localeId,
                                         WORD flags,
                                         DISPPARAMS* dispParams,
                                         VARIANT* result,
                                         EXCEPINFO* excepInfo,
                                         UINT* argErr) override;

        // ICoreWebView2PrivateDispatchContainer methods
        HRESULT STDMETHODCALLTYPE GetInnerObject(IUnknown** object) override;
        HRESULT STDMETHODCALLTYPE GetPropertyNames(wchar_t***, size_t*);
        HRESULT STDMETHODCALLTYPE GetPropertiesPrecacheability(BOOL** boolsOut, size_t* propertiesLengthOut);

    private:
        winrt::com_ptr<::IInspectable> m_innerObject;
        winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter m_dispatchAdapter;
        static DispatchProperties s_dispatchProperties;
        static const DISPID s_dispatchIds[];
        static const int s_precacheableProperties[];
};
}

namespace wv2winrt_impl
{
struct Class_Windows_Storage_IStorageFileStatics : winrt::implements<
    Class_Windows_Storage_IStorageFileStatics,
    DispatchBase>
{
    public:
        Class_Windows_Storage_IStorageFileStatics(::IInspectable* innerObject, const winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter& dispatchAdapter);

        // IDispatch methods
        HRESULT STDMETHODCALLTYPE GetIDsOfNames(REFIID riid,
                                                LPOLESTR* names,
                                                unsigned int namesCount,
                                                LCID localeId,
                                                DISPID* dispId) override;
        HRESULT STDMETHODCALLTYPE Invoke(DISPID dispId,
                                         REFIID riid,
                                         LCID localeId,
                                         WORD flags,
                                         DISPPARAMS* dispParams,
                                         VARIANT* result,
                                         EXCEPINFO* excepInfo,
                                         UINT* argErr) override;

        // ICoreWebView2PrivateDispatchContainer methods
        HRESULT STDMETHODCALLTYPE GetInnerObject(IUnknown** object) override;
        HRESULT STDMETHODCALLTYPE GetPropertyNames(wchar_t***, size_t*);
        HRESULT STDMETHODCALLTYPE GetPropertiesPrecacheability(BOOL** boolsOut, size_t* propertiesLengthOut);

    private:
        winrt::com_ptr<::IInspectable> m_innerObject;
        winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter m_dispatchAdapter;
        static DispatchProperties s_dispatchProperties;
        static const DISPID s_dispatchIds[];
        static const int s_precacheableProperties[];
};
}

namespace wv2winrt_impl
{
struct Class_Windows_Storage_StreamedFileDataRequestedHandler : winrt::implements<
    Class_Windows_Storage_StreamedFileDataRequestedHandler,
    DispatchBase>
{
    public:
        Class_Windows_Storage_StreamedFileDataRequestedHandler(::IInspectable* innerObject, const winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter& dispatchAdapter);

        // IDispatch methods
        HRESULT STDMETHODCALLTYPE GetIDsOfNames(REFIID riid,
                                                LPOLESTR* names,
                                                unsigned int namesCount,
                                                LCID localeId,
                                                DISPID* dispId) override;
        HRESULT STDMETHODCALLTYPE Invoke(DISPID dispId,
                                         REFIID riid,
                                         LCID localeId,
                                         WORD flags,
                                         DISPPARAMS* dispParams,
                                         VARIANT* result,
                                         EXCEPINFO* excepInfo,
                                         UINT* argErr) override;

        // ICoreWebView2PrivateDispatchContainer methods
        HRESULT STDMETHODCALLTYPE GetInnerObject(IUnknown** object) override;
        HRESULT STDMETHODCALLTYPE GetPropertyNames(wchar_t***, size_t*);
        HRESULT STDMETHODCALLTYPE GetPropertiesPrecacheability(BOOL** boolsOut, size_t* propertiesLengthOut);

    private:
        winrt::com_ptr<::IInspectable> m_innerObject;
        winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter m_dispatchAdapter;
        static DispatchProperties s_dispatchProperties;
        static const DISPID s_dispatchIds[];
        static const int s_precacheableProperties[];
};
}

namespace wv2winrt_impl
{
struct Class_Windows_Storage_StorageProvider : winrt::implements<
    Class_Windows_Storage_StorageProvider,
    DispatchBase>
{
    public:
        Class_Windows_Storage_StorageProvider(::IInspectable* innerObject, const winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter& dispatchAdapter);

        // IDispatch methods
        HRESULT STDMETHODCALLTYPE GetIDsOfNames(REFIID riid,
                                                LPOLESTR* names,
                                                unsigned int namesCount,
                                                LCID localeId,
                                                DISPID* dispId) override;
        HRESULT STDMETHODCALLTYPE Invoke(DISPID dispId,
                                         REFIID riid,
                                         LCID localeId,
                                         WORD flags,
                                         DISPPARAMS* dispParams,
                                         VARIANT* result,
                                         EXCEPINFO* excepInfo,
                                         UINT* argErr) override;

        // ICoreWebView2PrivateDispatchContainer methods
        HRESULT STDMETHODCALLTYPE GetInnerObject(IUnknown** object) override;
        HRESULT STDMETHODCALLTYPE GetPropertyNames(wchar_t***, size_t*);
        HRESULT STDMETHODCALLTYPE GetPropertiesPrecacheability(BOOL** boolsOut, size_t* propertiesLengthOut);

    private:
        winrt::com_ptr<::IInspectable> m_innerObject;
        winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter m_dispatchAdapter;
        static DispatchProperties s_dispatchProperties;
        static const DISPID s_dispatchIds[];
        static const int s_precacheableProperties[];
};
}

namespace wv2winrt_impl
{
struct Class_Windows_Storage_IStorageItemProperties2 : winrt::implements<
    Class_Windows_Storage_IStorageItemProperties2,
    DispatchBase>
{
    public:
        Class_Windows_Storage_IStorageItemProperties2(::IInspectable* innerObject, const winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter& dispatchAdapter);

        // IDispatch methods
        HRESULT STDMETHODCALLTYPE GetIDsOfNames(REFIID riid,
                                                LPOLESTR* names,
                                                unsigned int namesCount,
                                                LCID localeId,
                                                DISPID* dispId) override;
        HRESULT STDMETHODCALLTYPE Invoke(DISPID dispId,
                                         REFIID riid,
                                         LCID localeId,
                                         WORD flags,
                                         DISPPARAMS* dispParams,
                                         VARIANT* result,
                                         EXCEPINFO* excepInfo,
                                         UINT* argErr) override;

        // ICoreWebView2PrivateDispatchContainer methods
        HRESULT STDMETHODCALLTYPE GetInnerObject(IUnknown** object) override;
        HRESULT STDMETHODCALLTYPE GetPropertyNames(wchar_t***, size_t*);
        HRESULT STDMETHODCALLTYPE GetPropertiesPrecacheability(BOOL** boolsOut, size_t* propertiesLengthOut);

    private:
        winrt::com_ptr<::IInspectable> m_innerObject;
        winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter m_dispatchAdapter;
        static DispatchProperties s_dispatchProperties;
        static const DISPID s_dispatchIds[];
        static const int s_precacheableProperties[];
};
}

namespace wv2winrt_impl
{
struct Class_Windows_Storage_IStorageItemPropertiesWithProvider : winrt::implements<
    Class_Windows_Storage_IStorageItemPropertiesWithProvider,
    DispatchBase>
{
    public:
        Class_Windows_Storage_IStorageItemPropertiesWithProvider(::IInspectable* innerObject, const winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter& dispatchAdapter);

        // IDispatch methods
        HRESULT STDMETHODCALLTYPE GetIDsOfNames(REFIID riid,
                                                LPOLESTR* names,
                                                unsigned int namesCount,
                                                LCID localeId,
                                                DISPID* dispId) override;
        HRESULT STDMETHODCALLTYPE Invoke(DISPID dispId,
                                         REFIID riid,
                                         LCID localeId,
                                         WORD flags,
                                         DISPPARAMS* dispParams,
                                         VARIANT* result,
                                         EXCEPINFO* excepInfo,
                                         UINT* argErr) override;

        // ICoreWebView2PrivateDispatchContainer methods
        HRESULT STDMETHODCALLTYPE GetInnerObject(IUnknown** object) override;
        HRESULT STDMETHODCALLTYPE GetPropertyNames(wchar_t***, size_t*);
        HRESULT STDMETHODCALLTYPE GetPropertiesPrecacheability(BOOL** boolsOut, size_t* propertiesLengthOut);

    private:
        winrt::com_ptr<::IInspectable> m_innerObject;
        winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter m_dispatchAdapter;
        static DispatchProperties s_dispatchProperties;
        static const DISPID s_dispatchIds[];
        static const int s_precacheableProperties[];
};
}

namespace wv2winrt_impl
{
struct Class_Windows_Storage_IStorageFilePropertiesWithAvailability : winrt::implements<
    Class_Windows_Storage_IStorageFilePropertiesWithAvailability,
    DispatchBase>
{
    public:
        Class_Windows_Storage_IStorageFilePropertiesWithAvailability(::IInspectable* innerObject, const winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter& dispatchAdapter);

        // IDispatch methods
        HRESULT STDMETHODCALLTYPE GetIDsOfNames(REFIID riid,
                                                LPOLESTR* names,
                                                unsigned int namesCount,
                                                LCID localeId,
                                                DISPID* dispId) override;
        HRESULT STDMETHODCALLTYPE Invoke(DISPID dispId,
                                         REFIID riid,
                                         LCID localeId,
                                         WORD flags,
                                         DISPPARAMS* dispParams,
                                         VARIANT* result,
                                         EXCEPINFO* excepInfo,
                                         UINT* argErr) override;

        // ICoreWebView2PrivateDispatchContainer methods
        HRESULT STDMETHODCALLTYPE GetInnerObject(IUnknown** object) override;
        HRESULT STDMETHODCALLTYPE GetPropertyNames(wchar_t***, size_t*);
        HRESULT STDMETHODCALLTYPE GetPropertiesPrecacheability(BOOL** boolsOut, size_t* propertiesLengthOut);

    private:
        winrt::com_ptr<::IInspectable> m_innerObject;
        winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter m_dispatchAdapter;
        static DispatchProperties s_dispatchProperties;
        static const DISPID s_dispatchIds[];
        static const int s_precacheableProperties[];
};
}

namespace wv2winrt_impl
{
struct Class_Windows_Storage_StorageStreamTransaction : winrt::implements<
    Class_Windows_Storage_StorageStreamTransaction,
    DispatchBase>
{
    public:
        Class_Windows_Storage_StorageStreamTransaction(::IInspectable* innerObject, const winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter& dispatchAdapter);

        // IDispatch methods
        HRESULT STDMETHODCALLTYPE GetIDsOfNames(REFIID riid,
                                                LPOLESTR* names,
                                                unsigned int namesCount,
                                                LCID localeId,
                                                DISPID* dispId) override;
        HRESULT STDMETHODCALLTYPE Invoke(DISPID dispId,
                                         REFIID riid,
                                         LCID localeId,
                                         WORD flags,
                                         DISPPARAMS* dispParams,
                                         VARIANT* result,
                                         EXCEPINFO* excepInfo,
                                         UINT* argErr) override;

        // ICoreWebView2PrivateDispatchContainer methods
        HRESULT STDMETHODCALLTYPE GetInnerObject(IUnknown** object) override;
        HRESULT STDMETHODCALLTYPE GetPropertyNames(wchar_t***, size_t*);
        HRESULT STDMETHODCALLTYPE GetPropertiesPrecacheability(BOOL** boolsOut, size_t* propertiesLengthOut);

    private:
        winrt::com_ptr<::IInspectable> m_innerObject;
        winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter m_dispatchAdapter;
        static DispatchProperties s_dispatchProperties;
        static const DISPID s_dispatchIds[];
        static const int s_precacheableProperties[];
};
}

namespace wv2winrt_impl
{
struct Class_Windows_Storage_StorageFolder : winrt::implements<
    Class_Windows_Storage_StorageFolder,
    DispatchBase>
{
    public:
        Class_Windows_Storage_StorageFolder(::IInspectable* innerObject, const winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter& dispatchAdapter);

        // IDispatch methods
        HRESULT STDMETHODCALLTYPE GetIDsOfNames(REFIID riid,
                                                LPOLESTR* names,
                                                unsigned int namesCount,
                                                LCID localeId,
                                                DISPID* dispId) override;
        HRESULT STDMETHODCALLTYPE Invoke(DISPID dispId,
                                         REFIID riid,
                                         LCID localeId,
                                         WORD flags,
                                         DISPPARAMS* dispParams,
                                         VARIANT* result,
                                         EXCEPINFO* excepInfo,
                                         UINT* argErr) override;

        // ICoreWebView2PrivateDispatchContainer methods
        HRESULT STDMETHODCALLTYPE GetInnerObject(IUnknown** object) override;
        HRESULT STDMETHODCALLTYPE GetPropertyNames(wchar_t***, size_t*);
        HRESULT STDMETHODCALLTYPE GetPropertiesPrecacheability(BOOL** boolsOut, size_t* propertiesLengthOut);

    private:
        winrt::com_ptr<::IInspectable> m_innerObject;
        winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter m_dispatchAdapter;
        static DispatchProperties s_dispatchProperties;
        static const DISPID s_dispatchIds[];
        static const int s_precacheableProperties[];
};
}

namespace wv2winrt_impl
{
struct Class_Windows_Storage_IStorageProvider : winrt::implements<
    Class_Windows_Storage_IStorageProvider,
    DispatchBase>
{
    public:
        Class_Windows_Storage_IStorageProvider(::IInspectable* innerObject, const winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter& dispatchAdapter);

        // IDispatch methods
        HRESULT STDMETHODCALLTYPE GetIDsOfNames(REFIID riid,
                                                LPOLESTR* names,
                                                unsigned int namesCount,
                                                LCID localeId,
                                                DISPID* dispId) override;
        HRESULT STDMETHODCALLTYPE Invoke(DISPID dispId,
                                         REFIID riid,
                                         LCID localeId,
                                         WORD flags,
                                         DISPPARAMS* dispParams,
                                         VARIANT* result,
                                         EXCEPINFO* excepInfo,
                                         UINT* argErr) override;

        // ICoreWebView2PrivateDispatchContainer methods
        HRESULT STDMETHODCALLTYPE GetInnerObject(IUnknown** object) override;
        HRESULT STDMETHODCALLTYPE GetPropertyNames(wchar_t***, size_t*);
        HRESULT STDMETHODCALLTYPE GetPropertiesPrecacheability(BOOL** boolsOut, size_t* propertiesLengthOut);

    private:
        winrt::com_ptr<::IInspectable> m_innerObject;
        winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter m_dispatchAdapter;
        static DispatchProperties s_dispatchProperties;
        static const DISPID s_dispatchIds[];
        static const int s_precacheableProperties[];
};
}

namespace wv2winrt_impl
{
struct Class_Windows_Storage_IStorageProvider2 : winrt::implements<
    Class_Windows_Storage_IStorageProvider2,
    DispatchBase>
{
    public:
        Class_Windows_Storage_IStorageProvider2(::IInspectable* innerObject, const winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter& dispatchAdapter);

        // IDispatch methods
        HRESULT STDMETHODCALLTYPE GetIDsOfNames(REFIID riid,
                                                LPOLESTR* names,
                                                unsigned int namesCount,
                                                LCID localeId,
                                                DISPID* dispId) override;
        HRESULT STDMETHODCALLTYPE Invoke(DISPID dispId,
                                         REFIID riid,
                                         LCID localeId,
                                         WORD flags,
                                         DISPPARAMS* dispParams,
                                         VARIANT* result,
                                         EXCEPINFO* excepInfo,
                                         UINT* argErr) override;

        // ICoreWebView2PrivateDispatchContainer methods
        HRESULT STDMETHODCALLTYPE GetInnerObject(IUnknown** object) override;
        HRESULT STDMETHODCALLTYPE GetPropertyNames(wchar_t***, size_t*);
        HRESULT STDMETHODCALLTYPE GetPropertiesPrecacheability(BOOL** boolsOut, size_t* propertiesLengthOut);

    private:
        winrt::com_ptr<::IInspectable> m_innerObject;
        winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter m_dispatchAdapter;
        static DispatchProperties s_dispatchProperties;
        static const DISPID s_dispatchIds[];
        static const int s_precacheableProperties[];
};
}

namespace wv2winrt_impl
{
struct Class_Windows_Storage_IStorageStreamTransaction : winrt::implements<
    Class_Windows_Storage_IStorageStreamTransaction,
    DispatchBase>
{
    public:
        Class_Windows_Storage_IStorageStreamTransaction(::IInspectable* innerObject, const winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter& dispatchAdapter);

        // IDispatch methods
        HRESULT STDMETHODCALLTYPE GetIDsOfNames(REFIID riid,
                                                LPOLESTR* names,
                                                unsigned int namesCount,
                                                LCID localeId,
                                                DISPID* dispId) override;
        HRESULT STDMETHODCALLTYPE Invoke(DISPID dispId,
                                         REFIID riid,
                                         LCID localeId,
                                         WORD flags,
                                         DISPPARAMS* dispParams,
                                         VARIANT* result,
                                         EXCEPINFO* excepInfo,
                                         UINT* argErr) override;

        // ICoreWebView2PrivateDispatchContainer methods
        HRESULT STDMETHODCALLTYPE GetInnerObject(IUnknown** object) override;
        HRESULT STDMETHODCALLTYPE GetPropertyNames(wchar_t***, size_t*);
        HRESULT STDMETHODCALLTYPE GetPropertiesPrecacheability(BOOL** boolsOut, size_t* propertiesLengthOut);

    private:
        winrt::com_ptr<::IInspectable> m_innerObject;
        winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter m_dispatchAdapter;
        static DispatchProperties s_dispatchProperties;
        static const DISPID s_dispatchIds[];
        static const int s_precacheableProperties[];
};
}

namespace wv2winrt_impl
{
struct Class_Windows_Storage_IStorageFolder3 : winrt::implements<
    Class_Windows_Storage_IStorageFolder3,
    DispatchBase>
{
    public:
        Class_Windows_Storage_IStorageFolder3(::IInspectable* innerObject, const winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter& dispatchAdapter);

        // IDispatch methods
        HRESULT STDMETHODCALLTYPE GetIDsOfNames(REFIID riid,
                                                LPOLESTR* names,
                                                unsigned int namesCount,
                                                LCID localeId,
                                                DISPID* dispId) override;
        HRESULT STDMETHODCALLTYPE Invoke(DISPID dispId,
                                         REFIID riid,
                                         LCID localeId,
                                         WORD flags,
                                         DISPPARAMS* dispParams,
                                         VARIANT* result,
                                         EXCEPINFO* excepInfo,
                                         UINT* argErr) override;

        // ICoreWebView2PrivateDispatchContainer methods
        HRESULT STDMETHODCALLTYPE GetInnerObject(IUnknown** object) override;
        HRESULT STDMETHODCALLTYPE GetPropertyNames(wchar_t***, size_t*);
        HRESULT STDMETHODCALLTYPE GetPropertiesPrecacheability(BOOL** boolsOut, size_t* propertiesLengthOut);

    private:
        winrt::com_ptr<::IInspectable> m_innerObject;
        winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter m_dispatchAdapter;
        static DispatchProperties s_dispatchProperties;
        static const DISPID s_dispatchIds[];
        static const int s_precacheableProperties[];
};
}

namespace wv2winrt_impl
{
struct Class_Windows_Storage_StorageLibraryChangeTracker : winrt::implements<
    Class_Windows_Storage_StorageLibraryChangeTracker,
    DispatchBase>
{
    public:
        Class_Windows_Storage_StorageLibraryChangeTracker(::IInspectable* innerObject, const winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter& dispatchAdapter);

        // IDispatch methods
        HRESULT STDMETHODCALLTYPE GetIDsOfNames(REFIID riid,
                                                LPOLESTR* names,
                                                unsigned int namesCount,
                                                LCID localeId,
                                                DISPID* dispId) override;
        HRESULT STDMETHODCALLTYPE Invoke(DISPID dispId,
                                         REFIID riid,
                                         LCID localeId,
                                         WORD flags,
                                         DISPPARAMS* dispParams,
                                         VARIANT* result,
                                         EXCEPINFO* excepInfo,
                                         UINT* argErr) override;

        // ICoreWebView2PrivateDispatchContainer methods
        HRESULT STDMETHODCALLTYPE GetInnerObject(IUnknown** object) override;
        HRESULT STDMETHODCALLTYPE GetPropertyNames(wchar_t***, size_t*);
        HRESULT STDMETHODCALLTYPE GetPropertiesPrecacheability(BOOL** boolsOut, size_t* propertiesLengthOut);

    private:
        winrt::com_ptr<::IInspectable> m_innerObject;
        winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter m_dispatchAdapter;
        static DispatchProperties s_dispatchProperties;
        static const DISPID s_dispatchIds[];
        static const int s_precacheableProperties[];
};
}

namespace wv2winrt_impl
{
struct Class_Windows_Storage_IStorageFolder2 : winrt::implements<
    Class_Windows_Storage_IStorageFolder2,
    DispatchBase>
{
    public:
        Class_Windows_Storage_IStorageFolder2(::IInspectable* innerObject, const winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter& dispatchAdapter);

        // IDispatch methods
        HRESULT STDMETHODCALLTYPE GetIDsOfNames(REFIID riid,
                                                LPOLESTR* names,
                                                unsigned int namesCount,
                                                LCID localeId,
                                                DISPID* dispId) override;
        HRESULT STDMETHODCALLTYPE Invoke(DISPID dispId,
                                         REFIID riid,
                                         LCID localeId,
                                         WORD flags,
                                         DISPPARAMS* dispParams,
                                         VARIANT* result,
                                         EXCEPINFO* excepInfo,
                                         UINT* argErr) override;

        // ICoreWebView2PrivateDispatchContainer methods
        HRESULT STDMETHODCALLTYPE GetInnerObject(IUnknown** object) override;
        HRESULT STDMETHODCALLTYPE GetPropertyNames(wchar_t***, size_t*);
        HRESULT STDMETHODCALLTYPE GetPropertiesPrecacheability(BOOL** boolsOut, size_t* propertiesLengthOut);

    private:
        winrt::com_ptr<::IInspectable> m_innerObject;
        winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter m_dispatchAdapter;
        static DispatchProperties s_dispatchProperties;
        static const DISPID s_dispatchIds[];
        static const int s_precacheableProperties[];
};
}

namespace wv2winrt_impl
{
struct Class_Windows_Storage_IStorageLibraryChangeTracker : winrt::implements<
    Class_Windows_Storage_IStorageLibraryChangeTracker,
    DispatchBase>
{
    public:
        Class_Windows_Storage_IStorageLibraryChangeTracker(::IInspectable* innerObject, const winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter& dispatchAdapter);

        // IDispatch methods
        HRESULT STDMETHODCALLTYPE GetIDsOfNames(REFIID riid,
                                                LPOLESTR* names,
                                                unsigned int namesCount,
                                                LCID localeId,
                                                DISPID* dispId) override;
        HRESULT STDMETHODCALLTYPE Invoke(DISPID dispId,
                                         REFIID riid,
                                         LCID localeId,
                                         WORD flags,
                                         DISPPARAMS* dispParams,
                                         VARIANT* result,
                                         EXCEPINFO* excepInfo,
                                         UINT* argErr) override;

        // ICoreWebView2PrivateDispatchContainer methods
        HRESULT STDMETHODCALLTYPE GetInnerObject(IUnknown** object) override;
        HRESULT STDMETHODCALLTYPE GetPropertyNames(wchar_t***, size_t*);
        HRESULT STDMETHODCALLTYPE GetPropertiesPrecacheability(BOOL** boolsOut, size_t* propertiesLengthOut);

    private:
        winrt::com_ptr<::IInspectable> m_innerObject;
        winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter m_dispatchAdapter;
        static DispatchProperties s_dispatchProperties;
        static const DISPID s_dispatchIds[];
        static const int s_precacheableProperties[];
};
}

namespace wv2winrt_impl
{
struct Class_Windows_Storage_StorageLibraryChangeReader : winrt::implements<
    Class_Windows_Storage_StorageLibraryChangeReader,
    DispatchBase>
{
    public:
        Class_Windows_Storage_StorageLibraryChangeReader(::IInspectable* innerObject, const winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter& dispatchAdapter);

        // IDispatch methods
        HRESULT STDMETHODCALLTYPE GetIDsOfNames(REFIID riid,
                                                LPOLESTR* names,
                                                unsigned int namesCount,
                                                LCID localeId,
                                                DISPID* dispId) override;
        HRESULT STDMETHODCALLTYPE Invoke(DISPID dispId,
                                         REFIID riid,
                                         LCID localeId,
                                         WORD flags,
                                         DISPPARAMS* dispParams,
                                         VARIANT* result,
                                         EXCEPINFO* excepInfo,
                                         UINT* argErr) override;

        // ICoreWebView2PrivateDispatchContainer methods
        HRESULT STDMETHODCALLTYPE GetInnerObject(IUnknown** object) override;
        HRESULT STDMETHODCALLTYPE GetPropertyNames(wchar_t***, size_t*);
        HRESULT STDMETHODCALLTYPE GetPropertiesPrecacheability(BOOL** boolsOut, size_t* propertiesLengthOut);

    private:
        winrt::com_ptr<::IInspectable> m_innerObject;
        winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter m_dispatchAdapter;
        static DispatchProperties s_dispatchProperties;
        static const DISPID s_dispatchIds[];
        static const int s_precacheableProperties[];
};
}

namespace wv2winrt_impl
{
struct Class_Windows_Storage_IStorageLibraryChangeTracker2 : winrt::implements<
    Class_Windows_Storage_IStorageLibraryChangeTracker2,
    DispatchBase>
{
    public:
        Class_Windows_Storage_IStorageLibraryChangeTracker2(::IInspectable* innerObject, const winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter& dispatchAdapter);

        // IDispatch methods
        HRESULT STDMETHODCALLTYPE GetIDsOfNames(REFIID riid,
                                                LPOLESTR* names,
                                                unsigned int namesCount,
                                                LCID localeId,
                                                DISPID* dispId) override;
        HRESULT STDMETHODCALLTYPE Invoke(DISPID dispId,
                                         REFIID riid,
                                         LCID localeId,
                                         WORD flags,
                                         DISPPARAMS* dispParams,
                                         VARIANT* result,
                                         EXCEPINFO* excepInfo,
                                         UINT* argErr) override;

        // ICoreWebView2PrivateDispatchContainer methods
        HRESULT STDMETHODCALLTYPE GetInnerObject(IUnknown** object) override;
        HRESULT STDMETHODCALLTYPE GetPropertyNames(wchar_t***, size_t*);
        HRESULT STDMETHODCALLTYPE GetPropertiesPrecacheability(BOOL** boolsOut, size_t* propertiesLengthOut);

    private:
        winrt::com_ptr<::IInspectable> m_innerObject;
        winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter m_dispatchAdapter;
        static DispatchProperties s_dispatchProperties;
        static const DISPID s_dispatchIds[];
        static const int s_precacheableProperties[];
};
}

namespace wv2winrt_impl
{
struct Class_Windows_Storage_StorageLibraryChangeTrackerOptions : winrt::implements<
    Class_Windows_Storage_StorageLibraryChangeTrackerOptions,
    DispatchBase>
{
    public:
        Class_Windows_Storage_StorageLibraryChangeTrackerOptions(::IInspectable* innerObject, const winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter& dispatchAdapter);

        // IDispatch methods
        HRESULT STDMETHODCALLTYPE GetIDsOfNames(REFIID riid,
                                                LPOLESTR* names,
                                                unsigned int namesCount,
                                                LCID localeId,
                                                DISPID* dispId) override;
        HRESULT STDMETHODCALLTYPE Invoke(DISPID dispId,
                                         REFIID riid,
                                         LCID localeId,
                                         WORD flags,
                                         DISPPARAMS* dispParams,
                                         VARIANT* result,
                                         EXCEPINFO* excepInfo,
                                         UINT* argErr) override;

        // ICoreWebView2PrivateDispatchContainer methods
        HRESULT STDMETHODCALLTYPE GetInnerObject(IUnknown** object) override;
        HRESULT STDMETHODCALLTYPE GetPropertyNames(wchar_t***, size_t*);
        HRESULT STDMETHODCALLTYPE GetPropertiesPrecacheability(BOOL** boolsOut, size_t* propertiesLengthOut);

    private:
        winrt::com_ptr<::IInspectable> m_innerObject;
        winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter m_dispatchAdapter;
        static DispatchProperties s_dispatchProperties;
        static const DISPID s_dispatchIds[];
        static const int s_precacheableProperties[];
};
}

namespace wv2winrt_impl
{
struct Class_Windows_Storage_IStorageLibraryChangeReader : winrt::implements<
    Class_Windows_Storage_IStorageLibraryChangeReader,
    DispatchBase>
{
    public:
        Class_Windows_Storage_IStorageLibraryChangeReader(::IInspectable* innerObject, const winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter& dispatchAdapter);

        // IDispatch methods
        HRESULT STDMETHODCALLTYPE GetIDsOfNames(REFIID riid,
                                                LPOLESTR* names,
                                                unsigned int namesCount,
                                                LCID localeId,
                                                DISPID* dispId) override;
        HRESULT STDMETHODCALLTYPE Invoke(DISPID dispId,
                                         REFIID riid,
                                         LCID localeId,
                                         WORD flags,
                                         DISPPARAMS* dispParams,
                                         VARIANT* result,
                                         EXCEPINFO* excepInfo,
                                         UINT* argErr) override;

        // ICoreWebView2PrivateDispatchContainer methods
        HRESULT STDMETHODCALLTYPE GetInnerObject(IUnknown** object) override;
        HRESULT STDMETHODCALLTYPE GetPropertyNames(wchar_t***, size_t*);
        HRESULT STDMETHODCALLTYPE GetPropertiesPrecacheability(BOOL** boolsOut, size_t* propertiesLengthOut);

    private:
        winrt::com_ptr<::IInspectable> m_innerObject;
        winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter m_dispatchAdapter;
        static DispatchProperties s_dispatchProperties;
        static const DISPID s_dispatchIds[];
        static const int s_precacheableProperties[];
};
}

namespace wv2winrt_impl
{
struct Class_Windows_Storage_IStorageLibraryChangeReader2 : winrt::implements<
    Class_Windows_Storage_IStorageLibraryChangeReader2,
    DispatchBase>
{
    public:
        Class_Windows_Storage_IStorageLibraryChangeReader2(::IInspectable* innerObject, const winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter& dispatchAdapter);

        // IDispatch methods
        HRESULT STDMETHODCALLTYPE GetIDsOfNames(REFIID riid,
                                                LPOLESTR* names,
                                                unsigned int namesCount,
                                                LCID localeId,
                                                DISPID* dispId) override;
        HRESULT STDMETHODCALLTYPE Invoke(DISPID dispId,
                                         REFIID riid,
                                         LCID localeId,
                                         WORD flags,
                                         DISPPARAMS* dispParams,
                                         VARIANT* result,
                                         EXCEPINFO* excepInfo,
                                         UINT* argErr) override;

        // ICoreWebView2PrivateDispatchContainer methods
        HRESULT STDMETHODCALLTYPE GetInnerObject(IUnknown** object) override;
        HRESULT STDMETHODCALLTYPE GetPropertyNames(wchar_t***, size_t*);
        HRESULT STDMETHODCALLTYPE GetPropertiesPrecacheability(BOOL** boolsOut, size_t* propertiesLengthOut);

    private:
        winrt::com_ptr<::IInspectable> m_innerObject;
        winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter m_dispatchAdapter;
        static DispatchProperties s_dispatchProperties;
        static const DISPID s_dispatchIds[];
        static const int s_precacheableProperties[];
};
}

namespace wv2winrt_impl
{
struct Class_Windows_Storage_IStorageLibraryChangeTrackerOptions : winrt::implements<
    Class_Windows_Storage_IStorageLibraryChangeTrackerOptions,
    DispatchBase>
{
    public:
        Class_Windows_Storage_IStorageLibraryChangeTrackerOptions(::IInspectable* innerObject, const winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter& dispatchAdapter);

        // IDispatch methods
        HRESULT STDMETHODCALLTYPE GetIDsOfNames(REFIID riid,
                                                LPOLESTR* names,
                                                unsigned int namesCount,
                                                LCID localeId,
                                                DISPID* dispId) override;
        HRESULT STDMETHODCALLTYPE Invoke(DISPID dispId,
                                         REFIID riid,
                                         LCID localeId,
                                         WORD flags,
                                         DISPPARAMS* dispParams,
                                         VARIANT* result,
                                         EXCEPINFO* excepInfo,
                                         UINT* argErr) override;

        // ICoreWebView2PrivateDispatchContainer methods
        HRESULT STDMETHODCALLTYPE GetInnerObject(IUnknown** object) override;
        HRESULT STDMETHODCALLTYPE GetPropertyNames(wchar_t***, size_t*);
        HRESULT STDMETHODCALLTYPE GetPropertiesPrecacheability(BOOL** boolsOut, size_t* propertiesLengthOut);

    private:
        winrt::com_ptr<::IInspectable> m_innerObject;
        winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter m_dispatchAdapter;
        static DispatchProperties s_dispatchProperties;
        static const DISPID s_dispatchIds[];
        static const int s_precacheableProperties[];
};
}

namespace wv2winrt_impl
{
struct Class_Windows_Storage_StorageLibraryChange : winrt::implements<
    Class_Windows_Storage_StorageLibraryChange,
    DispatchBase>
{
    public:
        Class_Windows_Storage_StorageLibraryChange(::IInspectable* innerObject, const winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter& dispatchAdapter);

        // IDispatch methods
        HRESULT STDMETHODCALLTYPE GetIDsOfNames(REFIID riid,
                                                LPOLESTR* names,
                                                unsigned int namesCount,
                                                LCID localeId,
                                                DISPID* dispId) override;
        HRESULT STDMETHODCALLTYPE Invoke(DISPID dispId,
                                         REFIID riid,
                                         LCID localeId,
                                         WORD flags,
                                         DISPPARAMS* dispParams,
                                         VARIANT* result,
                                         EXCEPINFO* excepInfo,
                                         UINT* argErr) override;

        // ICoreWebView2PrivateDispatchContainer methods
        HRESULT STDMETHODCALLTYPE GetInnerObject(IUnknown** object) override;
        HRESULT STDMETHODCALLTYPE GetPropertyNames(wchar_t***, size_t*);
        HRESULT STDMETHODCALLTYPE GetPropertiesPrecacheability(BOOL** boolsOut, size_t* propertiesLengthOut);

    private:
        winrt::com_ptr<::IInspectable> m_innerObject;
        winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter m_dispatchAdapter;
        static DispatchProperties s_dispatchProperties;
        static const DISPID s_dispatchIds[];
        static const int s_precacheableProperties[];
};
}

namespace wv2winrt_impl
{
struct Class_Windows_Storage_IStorageLibraryChange : winrt::implements<
    Class_Windows_Storage_IStorageLibraryChange,
    DispatchBase>
{
    public:
        Class_Windows_Storage_IStorageLibraryChange(::IInspectable* innerObject, const winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter& dispatchAdapter);

        // IDispatch methods
        HRESULT STDMETHODCALLTYPE GetIDsOfNames(REFIID riid,
                                                LPOLESTR* names,
                                                unsigned int namesCount,
                                                LCID localeId,
                                                DISPID* dispId) override;
        HRESULT STDMETHODCALLTYPE Invoke(DISPID dispId,
                                         REFIID riid,
                                         LCID localeId,
                                         WORD flags,
                                         DISPPARAMS* dispParams,
                                         VARIANT* result,
                                         EXCEPINFO* excepInfo,
                                         UINT* argErr) override;

        // ICoreWebView2PrivateDispatchContainer methods
        HRESULT STDMETHODCALLTYPE GetInnerObject(IUnknown** object) override;
        HRESULT STDMETHODCALLTYPE GetPropertyNames(wchar_t***, size_t*);
        HRESULT STDMETHODCALLTYPE GetPropertiesPrecacheability(BOOL** boolsOut, size_t* propertiesLengthOut);

    private:
        winrt::com_ptr<::IInspectable> m_innerObject;
        winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter m_dispatchAdapter;
        static DispatchProperties s_dispatchProperties;
        static const DISPID s_dispatchIds[];
        static const int s_precacheableProperties[];
};
}
namespace wv2winrt_impl
{
struct Static_Class_Windows_Storage_StorageFile : winrt::implements<Static_Class_Windows_Storage_StorageFile, DispatchBase>
{
    public:
        Static_Class_Windows_Storage_StorageFile(const winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter& dispatchAdapter);

        HRESULT STDMETHODCALLTYPE GetIDsOfNames(REFIID riid,
                                                LPOLESTR* names,
                                                unsigned int namesCount,
                                                LCID localeId,
                                                DISPID* dispId) override;
        HRESULT STDMETHODCALLTYPE Invoke(DISPID dispId,
                                         REFIID riid,
                                         LCID localeId,
                                         WORD flags,
                                         DISPPARAMS* dispParams,
                                         VARIANT* result,
                                         EXCEPINFO* excepInfo,
                                         UINT* argErr) override;

        // ICoreWebView2PrivateDispatchContainer methods
        HRESULT STDMETHODCALLTYPE GetPropertyNames(wchar_t***, size_t*);

    private:
        winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter m_dispatchAdapter;
        static DispatchProperties s_dispatchProperties;
        static const DISPID s_dispatchIds[];
};
}
namespace wv2winrt_impl
{
struct Static_Class_Windows_Storage_StorageFolder : winrt::implements<Static_Class_Windows_Storage_StorageFolder, DispatchBase>
{
    public:
        Static_Class_Windows_Storage_StorageFolder(const winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter& dispatchAdapter);

        HRESULT STDMETHODCALLTYPE GetIDsOfNames(REFIID riid,
                                                LPOLESTR* names,
                                                unsigned int namesCount,
                                                LCID localeId,
                                                DISPID* dispId) override;
        HRESULT STDMETHODCALLTYPE Invoke(DISPID dispId,
                                         REFIID riid,
                                         LCID localeId,
                                         WORD flags,
                                         DISPPARAMS* dispParams,
                                         VARIANT* result,
                                         EXCEPINFO* excepInfo,
                                         UINT* argErr) override;

        // ICoreWebView2PrivateDispatchContainer methods
        HRESULT STDMETHODCALLTYPE GetPropertyNames(wchar_t***, size_t*);

    private:
        winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter m_dispatchAdapter;
        static DispatchProperties s_dispatchProperties;
        static const DISPID s_dispatchIds[];
};
}
namespace wv2winrt_impl
{
struct Static_Class_Windows_Storage_StorageLibraryChangeTrackerOptions : winrt::implements<Static_Class_Windows_Storage_StorageLibraryChangeTrackerOptions, DispatchBase>
{
    public:
        Static_Class_Windows_Storage_StorageLibraryChangeTrackerOptions(const winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter& dispatchAdapter);

        HRESULT STDMETHODCALLTYPE GetIDsOfNames(REFIID riid,
                                                LPOLESTR* names,
                                                unsigned int namesCount,
                                                LCID localeId,
                                                DISPID* dispId) override;
        HRESULT STDMETHODCALLTYPE Invoke(DISPID dispId,
                                         REFIID riid,
                                         LCID localeId,
                                         WORD flags,
                                         DISPPARAMS* dispParams,
                                         VARIANT* result,
                                         EXCEPINFO* excepInfo,
                                         UINT* argErr) override;

        // ICoreWebView2PrivateDispatchContainer methods
        HRESULT STDMETHODCALLTYPE GetPropertyNames(wchar_t***, size_t*);

    private:
        winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter m_dispatchAdapter;
        static DispatchProperties s_dispatchProperties;
        static const DISPID s_dispatchIds[];
};
}
