// WARNING: Please don't edit this file. It was generated by wv2winrt v1.0.0.0
#pragma once

#include "wv2winrt/dispatchbase.h"
#include "wv2winrt/dispatchcollectionhelpers.h"
#include <functional>
#include "wv2winrt/base.h"
#include "winrt/Windows.Foundation.Collections.h"

#include "winrt/Windows.Foundation.Collections.h"
#include "winrt/Windows.System.h"
#include "winrt/Windows.Storage.h"
#include "winrt/Windows.Foundation.h"
#include "winrt/Windows.Storage.Search.h"
#include "winrt/Windows.Data.Text.h"


namespace wv2winrt_impl
{
struct Namespace_Windows_Foundation_Collections : winrt::implements<Namespace_Windows_Foundation_Collections, DispatchBase>
{
    public:
        Namespace_Windows_Foundation_Collections(const winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter& dispatchAdapter);

        // IDispatch methods
        HRESULT STDMETHODCALLTYPE GetIDsOfNames(REFIID riid,
                                                LPOLESTR* names,
                                                unsigned int namesCount,
                                                LCID localeId,
                                                DISPID* dispId);

        HRESULT STDMETHODCALLTYPE Invoke(DISPID dispId,
                                         REFIID riid,
                                         LCID localeId,
                                         WORD flags,
                                         DISPPARAMS* dispParams,
                                         VARIANT* result,
                                         EXCEPINFO* excepInfo,
                                         UINT* argErr);
        // ICoreWebView2PrivateDispatchContainer methods
        HRESULT STDMETHODCALLTYPE GetPropertyNames(wchar_t***, size_t*);

    private:
        winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter m_dispatchAdapter;
        static DispatchProperties s_dispatchProperties;
        static const DISPID s_dispatchIds[];
};
}

namespace wv2winrt_impl
{
struct Class_Windows_Foundation_Collections_IVectorView_1_HSTRING_ : winrt::implements<
    Class_Windows_Foundation_Collections_IVectorView_1_HSTRING_,
    DispatchBase>
{
    public:
        Class_Windows_Foundation_Collections_IVectorView_1_HSTRING_(::IInspectable* innerObject, const winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter& dispatchAdapter);

        // IDispatch methods
        HRESULT STDMETHODCALLTYPE GetIDsOfNames(REFIID riid,
                                                LPOLESTR* names,
                                                unsigned int namesCount,
                                                LCID localeId,
                                                DISPID* dispId) override;
        HRESULT STDMETHODCALLTYPE Invoke(DISPID dispId,
                                         REFIID riid,
                                         LCID localeId,
                                         WORD flags,
                                         DISPPARAMS* dispParams,
                                         VARIANT* result,
                                         EXCEPINFO* excepInfo,
                                         UINT* argErr) override;

        // ICoreWebView2PrivateDispatchContainer methods
        HRESULT STDMETHODCALLTYPE GetInnerObject(IUnknown** object) override;
        HRESULT STDMETHODCALLTYPE GetScriptBehavior(DWORD* behavior)
        {
            *behavior = DispatchContainerScriptBehaviorVector;
            return S_OK;
        }
        HRESULT STDMETHODCALLTYPE GetPropertyNames(wchar_t***, size_t*);
        HRESULT STDMETHODCALLTYPE GetPropertiesPrecacheability(BOOL** boolsOut, size_t* propertiesLengthOut);

    private:
        winrt::com_ptr<::IInspectable> m_innerObject;
        winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter m_dispatchAdapter;
        static DispatchProperties s_dispatchProperties;
        static const DISPID s_dispatchIds[];
        static const int s_precacheableProperties[];
        DispatchVectorHelper<winrt::Windows::Foundation::Collections::IVectorView<
                winrt::hstring>,
            false, winrt::hstring> m_dispatchCollectionHelper;
};
}

namespace wv2winrt_impl
{
struct Class_Windows_Foundation_Collections_IVector_1_HSTRING_ : winrt::implements<
    Class_Windows_Foundation_Collections_IVector_1_HSTRING_,
    DispatchBase>
{
    public:
        Class_Windows_Foundation_Collections_IVector_1_HSTRING_(::IInspectable* innerObject, const winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter& dispatchAdapter);

        // IDispatch methods
        HRESULT STDMETHODCALLTYPE GetIDsOfNames(REFIID riid,
                                                LPOLESTR* names,
                                                unsigned int namesCount,
                                                LCID localeId,
                                                DISPID* dispId) override;
        HRESULT STDMETHODCALLTYPE Invoke(DISPID dispId,
                                         REFIID riid,
                                         LCID localeId,
                                         WORD flags,
                                         DISPPARAMS* dispParams,
                                         VARIANT* result,
                                         EXCEPINFO* excepInfo,
                                         UINT* argErr) override;

        // ICoreWebView2PrivateDispatchContainer methods
        HRESULT STDMETHODCALLTYPE GetInnerObject(IUnknown** object) override;
        HRESULT STDMETHODCALLTYPE GetScriptBehavior(DWORD* behavior)
        {
            *behavior = DispatchContainerScriptBehaviorVector;
            return S_OK;
        }
        HRESULT STDMETHODCALLTYPE GetPropertyNames(wchar_t***, size_t*);
        HRESULT STDMETHODCALLTYPE GetPropertiesPrecacheability(BOOL** boolsOut, size_t* propertiesLengthOut);

    private:
        winrt::com_ptr<::IInspectable> m_innerObject;
        winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter m_dispatchAdapter;
        static DispatchProperties s_dispatchProperties;
        static const DISPID s_dispatchIds[];
        static const int s_precacheableProperties[];
        DispatchVectorHelper<winrt::Windows::Foundation::Collections::IVector<
                winrt::hstring>,
            true, winrt::hstring> m_dispatchCollectionHelper;
};
}

namespace wv2winrt_impl
{
struct Class_Windows_Foundation_Collections_IIterable_1_HSTRING_ : winrt::implements<
    Class_Windows_Foundation_Collections_IIterable_1_HSTRING_,
    DispatchBase>
{
    public:
        Class_Windows_Foundation_Collections_IIterable_1_HSTRING_(::IInspectable* innerObject, const winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter& dispatchAdapter);

        // IDispatch methods
        HRESULT STDMETHODCALLTYPE GetIDsOfNames(REFIID riid,
                                                LPOLESTR* names,
                                                unsigned int namesCount,
                                                LCID localeId,
                                                DISPID* dispId) override;
        HRESULT STDMETHODCALLTYPE Invoke(DISPID dispId,
                                         REFIID riid,
                                         LCID localeId,
                                         WORD flags,
                                         DISPPARAMS* dispParams,
                                         VARIANT* result,
                                         EXCEPINFO* excepInfo,
                                         UINT* argErr) override;

        // ICoreWebView2PrivateDispatchContainer methods
        HRESULT STDMETHODCALLTYPE GetInnerObject(IUnknown** object) override;
        HRESULT STDMETHODCALLTYPE GetPropertyNames(wchar_t***, size_t*);
        HRESULT STDMETHODCALLTYPE GetPropertiesPrecacheability(BOOL** boolsOut, size_t* propertiesLengthOut);

    private:
        winrt::com_ptr<::IInspectable> m_innerObject;
        winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter m_dispatchAdapter;
        static DispatchProperties s_dispatchProperties;
        static const DISPID s_dispatchIds[];
        static const int s_precacheableProperties[];
};
}

namespace wv2winrt_impl
{
struct Class_Windows_Foundation_Collections_IMapView_2_HSTRING_IInspectable_ : winrt::implements<
    Class_Windows_Foundation_Collections_IMapView_2_HSTRING_IInspectable_,
    DispatchBase>
{
    public:
        Class_Windows_Foundation_Collections_IMapView_2_HSTRING_IInspectable_(::IInspectable* innerObject, const winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter& dispatchAdapter);

        // IDispatch methods
        HRESULT STDMETHODCALLTYPE GetIDsOfNames(REFIID riid,
                                                LPOLESTR* names,
                                                unsigned int namesCount,
                                                LCID localeId,
                                                DISPID* dispId) override;
        HRESULT STDMETHODCALLTYPE Invoke(DISPID dispId,
                                         REFIID riid,
                                         LCID localeId,
                                         WORD flags,
                                         DISPPARAMS* dispParams,
                                         VARIANT* result,
                                         EXCEPINFO* excepInfo,
                                         UINT* argErr) override;

        // ICoreWebView2PrivateDispatchContainer methods
        HRESULT STDMETHODCALLTYPE GetInnerObject(IUnknown** object) override;
        HRESULT STDMETHODCALLTYPE GetScriptBehavior(DWORD* behavior)
        {
            *behavior = DispatchContainerScriptBehaviorMap;
            return S_OK;
        }
        HRESULT STDMETHODCALLTYPE GetPropertyNames(wchar_t***, size_t*);
        HRESULT STDMETHODCALLTYPE GetPropertiesPrecacheability(BOOL** boolsOut, size_t* propertiesLengthOut);

    private:
        winrt::com_ptr<::IInspectable> m_innerObject;
        winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter m_dispatchAdapter;
        static DispatchProperties s_dispatchProperties;
        static const DISPID s_dispatchIds[];
        static const int s_precacheableProperties[];
        DispatchMapHelper<winrt::Windows::Foundation::Collections::IMapView<
                winrt::hstring, winrt::Windows::Foundation::IInspectable>,

            false, winrt::Windows::Foundation::IInspectable> m_dispatchCollectionHelper;
};
}

namespace wv2winrt_impl
{
struct Class_Windows_Foundation_Collections_IIterable_1_Windows_Foundation_Collections_IKeyValuePair_2_HSTRING_IInspectable__ : winrt::implements<
    Class_Windows_Foundation_Collections_IIterable_1_Windows_Foundation_Collections_IKeyValuePair_2_HSTRING_IInspectable__,
    DispatchBase>
{
    public:
        Class_Windows_Foundation_Collections_IIterable_1_Windows_Foundation_Collections_IKeyValuePair_2_HSTRING_IInspectable__(::IInspectable* innerObject, const winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter& dispatchAdapter);

        // IDispatch methods
        HRESULT STDMETHODCALLTYPE GetIDsOfNames(REFIID riid,
                                                LPOLESTR* names,
                                                unsigned int namesCount,
                                                LCID localeId,
                                                DISPID* dispId) override;
        HRESULT STDMETHODCALLTYPE Invoke(DISPID dispId,
                                         REFIID riid,
                                         LCID localeId,
                                         WORD flags,
                                         DISPPARAMS* dispParams,
                                         VARIANT* result,
                                         EXCEPINFO* excepInfo,
                                         UINT* argErr) override;

        // ICoreWebView2PrivateDispatchContainer methods
        HRESULT STDMETHODCALLTYPE GetInnerObject(IUnknown** object) override;
        HRESULT STDMETHODCALLTYPE GetPropertyNames(wchar_t***, size_t*);
        HRESULT STDMETHODCALLTYPE GetPropertiesPrecacheability(BOOL** boolsOut, size_t* propertiesLengthOut);

    private:
        winrt::com_ptr<::IInspectable> m_innerObject;
        winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter m_dispatchAdapter;
        static DispatchProperties s_dispatchProperties;
        static const DISPID s_dispatchIds[];
        static const int s_precacheableProperties[];
};
}

namespace wv2winrt_impl
{
struct Class_Windows_Foundation_Collections_IIterator_1_Windows_Foundation_Collections_IKeyValuePair_2_HSTRING_IInspectable__ : winrt::implements<
    Class_Windows_Foundation_Collections_IIterator_1_Windows_Foundation_Collections_IKeyValuePair_2_HSTRING_IInspectable__,
    DispatchBase>
{
    public:
        Class_Windows_Foundation_Collections_IIterator_1_Windows_Foundation_Collections_IKeyValuePair_2_HSTRING_IInspectable__(::IInspectable* innerObject, const winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter& dispatchAdapter);

        // IDispatch methods
        HRESULT STDMETHODCALLTYPE GetIDsOfNames(REFIID riid,
                                                LPOLESTR* names,
                                                unsigned int namesCount,
                                                LCID localeId,
                                                DISPID* dispId) override;
        HRESULT STDMETHODCALLTYPE Invoke(DISPID dispId,
                                         REFIID riid,
                                         LCID localeId,
                                         WORD flags,
                                         DISPPARAMS* dispParams,
                                         VARIANT* result,
                                         EXCEPINFO* excepInfo,
                                         UINT* argErr) override;

        // ICoreWebView2PrivateDispatchContainer methods
        HRESULT STDMETHODCALLTYPE GetInnerObject(IUnknown** object) override;
        HRESULT STDMETHODCALLTYPE GetPropertyNames(wchar_t***, size_t*);
        HRESULT STDMETHODCALLTYPE GetPropertiesPrecacheability(BOOL** boolsOut, size_t* propertiesLengthOut);

    private:
        winrt::com_ptr<::IInspectable> m_innerObject;
        winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter m_dispatchAdapter;
        static DispatchProperties s_dispatchProperties;
        static const DISPID s_dispatchIds[];
        static const int s_precacheableProperties[];
};
}

namespace wv2winrt_impl
{
struct Class_Windows_Foundation_Collections_IIterator_1_HSTRING_ : winrt::implements<
    Class_Windows_Foundation_Collections_IIterator_1_HSTRING_,
    DispatchBase>
{
    public:
        Class_Windows_Foundation_Collections_IIterator_1_HSTRING_(::IInspectable* innerObject, const winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter& dispatchAdapter);

        // IDispatch methods
        HRESULT STDMETHODCALLTYPE GetIDsOfNames(REFIID riid,
                                                LPOLESTR* names,
                                                unsigned int namesCount,
                                                LCID localeId,
                                                DISPID* dispId) override;
        HRESULT STDMETHODCALLTYPE Invoke(DISPID dispId,
                                         REFIID riid,
                                         LCID localeId,
                                         WORD flags,
                                         DISPPARAMS* dispParams,
                                         VARIANT* result,
                                         EXCEPINFO* excepInfo,
                                         UINT* argErr) override;

        // ICoreWebView2PrivateDispatchContainer methods
        HRESULT STDMETHODCALLTYPE GetInnerObject(IUnknown** object) override;
        HRESULT STDMETHODCALLTYPE GetPropertyNames(wchar_t***, size_t*);
        HRESULT STDMETHODCALLTYPE GetPropertiesPrecacheability(BOOL** boolsOut, size_t* propertiesLengthOut);

    private:
        winrt::com_ptr<::IInspectable> m_innerObject;
        winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter m_dispatchAdapter;
        static DispatchProperties s_dispatchProperties;
        static const DISPID s_dispatchIds[];
        static const int s_precacheableProperties[];
};
}

namespace wv2winrt_impl
{
struct Class_Windows_Foundation_Collections_IKeyValuePair_2_HSTRING_IInspectable_ : winrt::implements<
    Class_Windows_Foundation_Collections_IKeyValuePair_2_HSTRING_IInspectable_,
    DispatchBase>
{
    public:
        Class_Windows_Foundation_Collections_IKeyValuePair_2_HSTRING_IInspectable_(::IInspectable* innerObject, const winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter& dispatchAdapter);

        // IDispatch methods
        HRESULT STDMETHODCALLTYPE GetIDsOfNames(REFIID riid,
                                                LPOLESTR* names,
                                                unsigned int namesCount,
                                                LCID localeId,
                                                DISPID* dispId) override;
        HRESULT STDMETHODCALLTYPE Invoke(DISPID dispId,
                                         REFIID riid,
                                         LCID localeId,
                                         WORD flags,
                                         DISPPARAMS* dispParams,
                                         VARIANT* result,
                                         EXCEPINFO* excepInfo,
                                         UINT* argErr) override;

        // ICoreWebView2PrivateDispatchContainer methods
        HRESULT STDMETHODCALLTYPE GetInnerObject(IUnknown** object) override;
        HRESULT STDMETHODCALLTYPE GetPropertyNames(wchar_t***, size_t*);
        HRESULT STDMETHODCALLTYPE GetPropertiesPrecacheability(BOOL** boolsOut, size_t* propertiesLengthOut);

    private:
        winrt::com_ptr<::IInspectable> m_innerObject;
        winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter m_dispatchAdapter;
        static DispatchProperties s_dispatchProperties;
        static const DISPID s_dispatchIds[];
        static const int s_precacheableProperties[];
};
}

namespace wv2winrt_impl
{
struct Class_Windows_Foundation_Collections_IPropertySet : winrt::implements<
    Class_Windows_Foundation_Collections_IPropertySet,
    DispatchBase>
{
    public:
        Class_Windows_Foundation_Collections_IPropertySet(::IInspectable* innerObject, const winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter& dispatchAdapter);

        // IDispatch methods
        HRESULT STDMETHODCALLTYPE GetIDsOfNames(REFIID riid,
                                                LPOLESTR* names,
                                                unsigned int namesCount,
                                                LCID localeId,
                                                DISPID* dispId) override;
        HRESULT STDMETHODCALLTYPE Invoke(DISPID dispId,
                                         REFIID riid,
                                         LCID localeId,
                                         WORD flags,
                                         DISPPARAMS* dispParams,
                                         VARIANT* result,
                                         EXCEPINFO* excepInfo,
                                         UINT* argErr) override;

        // ICoreWebView2PrivateDispatchContainer methods
        HRESULT STDMETHODCALLTYPE GetInnerObject(IUnknown** object) override;
        HRESULT STDMETHODCALLTYPE GetScriptBehavior(DWORD* behavior)
        {
            *behavior = DispatchContainerScriptBehaviorMap;
            return S_OK;
        }
        HRESULT STDMETHODCALLTYPE GetPropertyNames(wchar_t***, size_t*);
        HRESULT STDMETHODCALLTYPE GetPropertiesPrecacheability(BOOL** boolsOut, size_t* propertiesLengthOut);

    private:
        winrt::com_ptr<::IInspectable> m_innerObject;
        winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter m_dispatchAdapter;
        static DispatchProperties s_dispatchProperties;
        static const DISPID s_dispatchIds[];
        static const int s_precacheableProperties[];
        DispatchMapHelper<winrt::Windows::Foundation::Collections::IMap<
                winrt::hstring, winrt::Windows::Foundation::IInspectable>,

            true, winrt::Windows::Foundation::IInspectable> m_dispatchCollectionHelper;
};
}

namespace wv2winrt_impl
{
struct Class_Windows_Foundation_Collections_IVectorView_1_Windows_System_User_ : winrt::implements<
    Class_Windows_Foundation_Collections_IVectorView_1_Windows_System_User_,
    DispatchBase>
{
    public:
        Class_Windows_Foundation_Collections_IVectorView_1_Windows_System_User_(::IInspectable* innerObject, const winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter& dispatchAdapter);

        // IDispatch methods
        HRESULT STDMETHODCALLTYPE GetIDsOfNames(REFIID riid,
                                                LPOLESTR* names,
                                                unsigned int namesCount,
                                                LCID localeId,
                                                DISPID* dispId) override;
        HRESULT STDMETHODCALLTYPE Invoke(DISPID dispId,
                                         REFIID riid,
                                         LCID localeId,
                                         WORD flags,
                                         DISPPARAMS* dispParams,
                                         VARIANT* result,
                                         EXCEPINFO* excepInfo,
                                         UINT* argErr) override;

        // ICoreWebView2PrivateDispatchContainer methods
        HRESULT STDMETHODCALLTYPE GetInnerObject(IUnknown** object) override;
        HRESULT STDMETHODCALLTYPE GetScriptBehavior(DWORD* behavior)
        {
            *behavior = DispatchContainerScriptBehaviorVector;
            return S_OK;
        }
        HRESULT STDMETHODCALLTYPE GetPropertyNames(wchar_t***, size_t*);
        HRESULT STDMETHODCALLTYPE GetPropertiesPrecacheability(BOOL** boolsOut, size_t* propertiesLengthOut);

    private:
        winrt::com_ptr<::IInspectable> m_innerObject;
        winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter m_dispatchAdapter;
        static DispatchProperties s_dispatchProperties;
        static const DISPID s_dispatchIds[];
        static const int s_precacheableProperties[];
        DispatchVectorHelper<winrt::Windows::Foundation::Collections::IVectorView<
                winrt::Windows::System::User>,
            false, winrt::Windows::System::User> m_dispatchCollectionHelper;
};
}

namespace wv2winrt_impl
{
struct Class_Windows_Foundation_Collections_IObservableMap_2_HSTRING_IInspectable_ : winrt::implements<
    Class_Windows_Foundation_Collections_IObservableMap_2_HSTRING_IInspectable_,
    DispatchBase>
{
    public:
        Class_Windows_Foundation_Collections_IObservableMap_2_HSTRING_IInspectable_(::IInspectable* innerObject, const winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter& dispatchAdapter);

        // IDispatch methods
        HRESULT STDMETHODCALLTYPE GetIDsOfNames(REFIID riid,
                                                LPOLESTR* names,
                                                unsigned int namesCount,
                                                LCID localeId,
                                                DISPID* dispId) override;
        HRESULT STDMETHODCALLTYPE Invoke(DISPID dispId,
                                         REFIID riid,
                                         LCID localeId,
                                         WORD flags,
                                         DISPPARAMS* dispParams,
                                         VARIANT* result,
                                         EXCEPINFO* excepInfo,
                                         UINT* argErr) override;

        // ICoreWebView2PrivateDispatchContainer methods
        HRESULT STDMETHODCALLTYPE GetInnerObject(IUnknown** object) override;
        HRESULT STDMETHODCALLTYPE GetScriptBehavior(DWORD* behavior)
        {
            *behavior = DispatchContainerScriptBehaviorMap;
            return S_OK;
        }
        HRESULT STDMETHODCALLTYPE GetPropertyNames(wchar_t***, size_t*);
        HRESULT STDMETHODCALLTYPE GetPropertiesPrecacheability(BOOL** boolsOut, size_t* propertiesLengthOut);

    private:
        winrt::com_ptr<::IInspectable> m_innerObject;
        winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter m_dispatchAdapter;
        static DispatchProperties s_dispatchProperties;
        static const DISPID s_dispatchIds[];
        static const int s_precacheableProperties[];

        // Event registration uses the callback's IDispatch* as the key value.
        // It is a weak reference and should not be resolved.
        std::map<void*, winrt::Windows::Foundation::Collections::IObservableMap<winrt::hstring, winrt::Windows::Foundation::IInspectable>::MapChanged_revoker > m_eventRegistrationMapChanged;

        DispatchMapHelper<winrt::Windows::Foundation::Collections::IMap<
                winrt::hstring, winrt::Windows::Foundation::IInspectable>,

            true, winrt::Windows::Foundation::IInspectable> m_dispatchCollectionHelper;
};
}

namespace wv2winrt_impl
{
struct Class_Windows_Foundation_Collections_IMap_2_HSTRING_IInspectable_ : winrt::implements<
    Class_Windows_Foundation_Collections_IMap_2_HSTRING_IInspectable_,
    DispatchBase>
{
    public:
        Class_Windows_Foundation_Collections_IMap_2_HSTRING_IInspectable_(::IInspectable* innerObject, const winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter& dispatchAdapter);

        // IDispatch methods
        HRESULT STDMETHODCALLTYPE GetIDsOfNames(REFIID riid,
                                                LPOLESTR* names,
                                                unsigned int namesCount,
                                                LCID localeId,
                                                DISPID* dispId) override;
        HRESULT STDMETHODCALLTYPE Invoke(DISPID dispId,
                                         REFIID riid,
                                         LCID localeId,
                                         WORD flags,
                                         DISPPARAMS* dispParams,
                                         VARIANT* result,
                                         EXCEPINFO* excepInfo,
                                         UINT* argErr) override;

        // ICoreWebView2PrivateDispatchContainer methods
        HRESULT STDMETHODCALLTYPE GetInnerObject(IUnknown** object) override;
        HRESULT STDMETHODCALLTYPE GetScriptBehavior(DWORD* behavior)
        {
            *behavior = DispatchContainerScriptBehaviorMap;
            return S_OK;
        }
        HRESULT STDMETHODCALLTYPE GetPropertyNames(wchar_t***, size_t*);
        HRESULT STDMETHODCALLTYPE GetPropertiesPrecacheability(BOOL** boolsOut, size_t* propertiesLengthOut);

    private:
        winrt::com_ptr<::IInspectable> m_innerObject;
        winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter m_dispatchAdapter;
        static DispatchProperties s_dispatchProperties;
        static const DISPID s_dispatchIds[];
        static const int s_precacheableProperties[];
        DispatchMapHelper<winrt::Windows::Foundation::Collections::IMap<
                winrt::hstring, winrt::Windows::Foundation::IInspectable>,

            true, winrt::Windows::Foundation::IInspectable> m_dispatchCollectionHelper;
};
}

namespace wv2winrt_impl
{
struct Class_Windows_Foundation_Collections_IIterable_1_Windows_System_User_ : winrt::implements<
    Class_Windows_Foundation_Collections_IIterable_1_Windows_System_User_,
    DispatchBase>
{
    public:
        Class_Windows_Foundation_Collections_IIterable_1_Windows_System_User_(::IInspectable* innerObject, const winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter& dispatchAdapter);

        // IDispatch methods
        HRESULT STDMETHODCALLTYPE GetIDsOfNames(REFIID riid,
                                                LPOLESTR* names,
                                                unsigned int namesCount,
                                                LCID localeId,
                                                DISPID* dispId) override;
        HRESULT STDMETHODCALLTYPE Invoke(DISPID dispId,
                                         REFIID riid,
                                         LCID localeId,
                                         WORD flags,
                                         DISPPARAMS* dispParams,
                                         VARIANT* result,
                                         EXCEPINFO* excepInfo,
                                         UINT* argErr) override;

        // ICoreWebView2PrivateDispatchContainer methods
        HRESULT STDMETHODCALLTYPE GetInnerObject(IUnknown** object) override;
        HRESULT STDMETHODCALLTYPE GetPropertyNames(wchar_t***, size_t*);
        HRESULT STDMETHODCALLTYPE GetPropertiesPrecacheability(BOOL** boolsOut, size_t* propertiesLengthOut);

    private:
        winrt::com_ptr<::IInspectable> m_innerObject;
        winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter m_dispatchAdapter;
        static DispatchProperties s_dispatchProperties;
        static const DISPID s_dispatchIds[];
        static const int s_precacheableProperties[];
};
}

namespace wv2winrt_impl
{
struct Class_Windows_Foundation_Collections_IIterator_1_Windows_System_User_ : winrt::implements<
    Class_Windows_Foundation_Collections_IIterator_1_Windows_System_User_,
    DispatchBase>
{
    public:
        Class_Windows_Foundation_Collections_IIterator_1_Windows_System_User_(::IInspectable* innerObject, const winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter& dispatchAdapter);

        // IDispatch methods
        HRESULT STDMETHODCALLTYPE GetIDsOfNames(REFIID riid,
                                                LPOLESTR* names,
                                                unsigned int namesCount,
                                                LCID localeId,
                                                DISPID* dispId) override;
        HRESULT STDMETHODCALLTYPE Invoke(DISPID dispId,
                                         REFIID riid,
                                         LCID localeId,
                                         WORD flags,
                                         DISPPARAMS* dispParams,
                                         VARIANT* result,
                                         EXCEPINFO* excepInfo,
                                         UINT* argErr) override;

        // ICoreWebView2PrivateDispatchContainer methods
        HRESULT STDMETHODCALLTYPE GetInnerObject(IUnknown** object) override;
        HRESULT STDMETHODCALLTYPE GetPropertyNames(wchar_t***, size_t*);
        HRESULT STDMETHODCALLTYPE GetPropertiesPrecacheability(BOOL** boolsOut, size_t* propertiesLengthOut);

    private:
        winrt::com_ptr<::IInspectable> m_innerObject;
        winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter m_dispatchAdapter;
        static DispatchProperties s_dispatchProperties;
        static const DISPID s_dispatchIds[];
        static const int s_precacheableProperties[];
};
}

namespace wv2winrt_impl
{
struct Class_Windows_Foundation_Collections_IVectorView_1_Windows_Storage_StorageFile_ : winrt::implements<
    Class_Windows_Foundation_Collections_IVectorView_1_Windows_Storage_StorageFile_,
    DispatchBase>
{
    public:
        Class_Windows_Foundation_Collections_IVectorView_1_Windows_Storage_StorageFile_(::IInspectable* innerObject, const winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter& dispatchAdapter);

        // IDispatch methods
        HRESULT STDMETHODCALLTYPE GetIDsOfNames(REFIID riid,
                                                LPOLESTR* names,
                                                unsigned int namesCount,
                                                LCID localeId,
                                                DISPID* dispId) override;
        HRESULT STDMETHODCALLTYPE Invoke(DISPID dispId,
                                         REFIID riid,
                                         LCID localeId,
                                         WORD flags,
                                         DISPPARAMS* dispParams,
                                         VARIANT* result,
                                         EXCEPINFO* excepInfo,
                                         UINT* argErr) override;

        // ICoreWebView2PrivateDispatchContainer methods
        HRESULT STDMETHODCALLTYPE GetInnerObject(IUnknown** object) override;
        HRESULT STDMETHODCALLTYPE GetScriptBehavior(DWORD* behavior)
        {
            *behavior = DispatchContainerScriptBehaviorVector;
            return S_OK;
        }
        HRESULT STDMETHODCALLTYPE GetPropertyNames(wchar_t***, size_t*);
        HRESULT STDMETHODCALLTYPE GetPropertiesPrecacheability(BOOL** boolsOut, size_t* propertiesLengthOut);

    private:
        winrt::com_ptr<::IInspectable> m_innerObject;
        winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter m_dispatchAdapter;
        static DispatchProperties s_dispatchProperties;
        static const DISPID s_dispatchIds[];
        static const int s_precacheableProperties[];
        DispatchVectorHelper<winrt::Windows::Foundation::Collections::IVectorView<
                winrt::Windows::Storage::StorageFile>,
            false, winrt::Windows::Storage::StorageFile> m_dispatchCollectionHelper;
};
}

namespace wv2winrt_impl
{
struct Class_Windows_Foundation_Collections_IVectorView_1_Windows_Storage_StorageFolder_ : winrt::implements<
    Class_Windows_Foundation_Collections_IVectorView_1_Windows_Storage_StorageFolder_,
    DispatchBase>
{
    public:
        Class_Windows_Foundation_Collections_IVectorView_1_Windows_Storage_StorageFolder_(::IInspectable* innerObject, const winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter& dispatchAdapter);

        // IDispatch methods
        HRESULT STDMETHODCALLTYPE GetIDsOfNames(REFIID riid,
                                                LPOLESTR* names,
                                                unsigned int namesCount,
                                                LCID localeId,
                                                DISPID* dispId) override;
        HRESULT STDMETHODCALLTYPE Invoke(DISPID dispId,
                                         REFIID riid,
                                         LCID localeId,
                                         WORD flags,
                                         DISPPARAMS* dispParams,
                                         VARIANT* result,
                                         EXCEPINFO* excepInfo,
                                         UINT* argErr) override;

        // ICoreWebView2PrivateDispatchContainer methods
        HRESULT STDMETHODCALLTYPE GetInnerObject(IUnknown** object) override;
        HRESULT STDMETHODCALLTYPE GetScriptBehavior(DWORD* behavior)
        {
            *behavior = DispatchContainerScriptBehaviorVector;
            return S_OK;
        }
        HRESULT STDMETHODCALLTYPE GetPropertyNames(wchar_t***, size_t*);
        HRESULT STDMETHODCALLTYPE GetPropertiesPrecacheability(BOOL** boolsOut, size_t* propertiesLengthOut);

    private:
        winrt::com_ptr<::IInspectable> m_innerObject;
        winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter m_dispatchAdapter;
        static DispatchProperties s_dispatchProperties;
        static const DISPID s_dispatchIds[];
        static const int s_precacheableProperties[];
        DispatchVectorHelper<winrt::Windows::Foundation::Collections::IVectorView<
                winrt::Windows::Storage::StorageFolder>,
            false, winrt::Windows::Storage::StorageFolder> m_dispatchCollectionHelper;
};
}

namespace wv2winrt_impl
{
struct Class_Windows_Foundation_Collections_IVectorView_1_Windows_Storage_IStorageItem_ : winrt::implements<
    Class_Windows_Foundation_Collections_IVectorView_1_Windows_Storage_IStorageItem_,
    DispatchBase>
{
    public:
        Class_Windows_Foundation_Collections_IVectorView_1_Windows_Storage_IStorageItem_(::IInspectable* innerObject, const winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter& dispatchAdapter);

        // IDispatch methods
        HRESULT STDMETHODCALLTYPE GetIDsOfNames(REFIID riid,
                                                LPOLESTR* names,
                                                unsigned int namesCount,
                                                LCID localeId,
                                                DISPID* dispId) override;
        HRESULT STDMETHODCALLTYPE Invoke(DISPID dispId,
                                         REFIID riid,
                                         LCID localeId,
                                         WORD flags,
                                         DISPPARAMS* dispParams,
                                         VARIANT* result,
                                         EXCEPINFO* excepInfo,
                                         UINT* argErr) override;

        // ICoreWebView2PrivateDispatchContainer methods
        HRESULT STDMETHODCALLTYPE GetInnerObject(IUnknown** object) override;
        HRESULT STDMETHODCALLTYPE GetScriptBehavior(DWORD* behavior)
        {
            *behavior = DispatchContainerScriptBehaviorVector;
            return S_OK;
        }
        HRESULT STDMETHODCALLTYPE GetPropertyNames(wchar_t***, size_t*);
        HRESULT STDMETHODCALLTYPE GetPropertiesPrecacheability(BOOL** boolsOut, size_t* propertiesLengthOut);

    private:
        winrt::com_ptr<::IInspectable> m_innerObject;
        winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter m_dispatchAdapter;
        static DispatchProperties s_dispatchProperties;
        static const DISPID s_dispatchIds[];
        static const int s_precacheableProperties[];
        DispatchVectorHelper<winrt::Windows::Foundation::Collections::IVectorView<
                winrt::Windows::Storage::IStorageItem>,
            false, winrt::Windows::Storage::IStorageItem> m_dispatchCollectionHelper;
};
}

namespace wv2winrt_impl
{
struct Class_Windows_Foundation_Collections_IIterable_1_Windows_Foundation_IWwwFormUrlDecoderEntry_ : winrt::implements<
    Class_Windows_Foundation_Collections_IIterable_1_Windows_Foundation_IWwwFormUrlDecoderEntry_,
    DispatchBase>
{
    public:
        Class_Windows_Foundation_Collections_IIterable_1_Windows_Foundation_IWwwFormUrlDecoderEntry_(::IInspectable* innerObject, const winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter& dispatchAdapter);

        // IDispatch methods
        HRESULT STDMETHODCALLTYPE GetIDsOfNames(REFIID riid,
                                                LPOLESTR* names,
                                                unsigned int namesCount,
                                                LCID localeId,
                                                DISPID* dispId) override;
        HRESULT STDMETHODCALLTYPE Invoke(DISPID dispId,
                                         REFIID riid,
                                         LCID localeId,
                                         WORD flags,
                                         DISPPARAMS* dispParams,
                                         VARIANT* result,
                                         EXCEPINFO* excepInfo,
                                         UINT* argErr) override;

        // ICoreWebView2PrivateDispatchContainer methods
        HRESULT STDMETHODCALLTYPE GetInnerObject(IUnknown** object) override;
        HRESULT STDMETHODCALLTYPE GetPropertyNames(wchar_t***, size_t*);
        HRESULT STDMETHODCALLTYPE GetPropertiesPrecacheability(BOOL** boolsOut, size_t* propertiesLengthOut);

    private:
        winrt::com_ptr<::IInspectable> m_innerObject;
        winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter m_dispatchAdapter;
        static DispatchProperties s_dispatchProperties;
        static const DISPID s_dispatchIds[];
        static const int s_precacheableProperties[];
};
}

namespace wv2winrt_impl
{
struct Class_Windows_Foundation_Collections_IIterator_1_Windows_Foundation_IWwwFormUrlDecoderEntry_ : winrt::implements<
    Class_Windows_Foundation_Collections_IIterator_1_Windows_Foundation_IWwwFormUrlDecoderEntry_,
    DispatchBase>
{
    public:
        Class_Windows_Foundation_Collections_IIterator_1_Windows_Foundation_IWwwFormUrlDecoderEntry_(::IInspectable* innerObject, const winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter& dispatchAdapter);

        // IDispatch methods
        HRESULT STDMETHODCALLTYPE GetIDsOfNames(REFIID riid,
                                                LPOLESTR* names,
                                                unsigned int namesCount,
                                                LCID localeId,
                                                DISPID* dispId) override;
        HRESULT STDMETHODCALLTYPE Invoke(DISPID dispId,
                                         REFIID riid,
                                         LCID localeId,
                                         WORD flags,
                                         DISPPARAMS* dispParams,
                                         VARIANT* result,
                                         EXCEPINFO* excepInfo,
                                         UINT* argErr) override;

        // ICoreWebView2PrivateDispatchContainer methods
        HRESULT STDMETHODCALLTYPE GetInnerObject(IUnknown** object) override;
        HRESULT STDMETHODCALLTYPE GetPropertyNames(wchar_t***, size_t*);
        HRESULT STDMETHODCALLTYPE GetPropertiesPrecacheability(BOOL** boolsOut, size_t* propertiesLengthOut);

    private:
        winrt::com_ptr<::IInspectable> m_innerObject;
        winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter m_dispatchAdapter;
        static DispatchProperties s_dispatchProperties;
        static const DISPID s_dispatchIds[];
        static const int s_precacheableProperties[];
};
}

namespace wv2winrt_impl
{
struct Class_Windows_Foundation_Collections_IVectorView_1_Windows_Foundation_IWwwFormUrlDecoderEntry_ : winrt::implements<
    Class_Windows_Foundation_Collections_IVectorView_1_Windows_Foundation_IWwwFormUrlDecoderEntry_,
    DispatchBase>
{
    public:
        Class_Windows_Foundation_Collections_IVectorView_1_Windows_Foundation_IWwwFormUrlDecoderEntry_(::IInspectable* innerObject, const winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter& dispatchAdapter);

        // IDispatch methods
        HRESULT STDMETHODCALLTYPE GetIDsOfNames(REFIID riid,
                                                LPOLESTR* names,
                                                unsigned int namesCount,
                                                LCID localeId,
                                                DISPID* dispId) override;
        HRESULT STDMETHODCALLTYPE Invoke(DISPID dispId,
                                         REFIID riid,
                                         LCID localeId,
                                         WORD flags,
                                         DISPPARAMS* dispParams,
                                         VARIANT* result,
                                         EXCEPINFO* excepInfo,
                                         UINT* argErr) override;

        // ICoreWebView2PrivateDispatchContainer methods
        HRESULT STDMETHODCALLTYPE GetInnerObject(IUnknown** object) override;
        HRESULT STDMETHODCALLTYPE GetScriptBehavior(DWORD* behavior)
        {
            *behavior = DispatchContainerScriptBehaviorVector;
            return S_OK;
        }
        HRESULT STDMETHODCALLTYPE GetPropertyNames(wchar_t***, size_t*);
        HRESULT STDMETHODCALLTYPE GetPropertiesPrecacheability(BOOL** boolsOut, size_t* propertiesLengthOut);

    private:
        winrt::com_ptr<::IInspectable> m_innerObject;
        winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter m_dispatchAdapter;
        static DispatchProperties s_dispatchProperties;
        static const DISPID s_dispatchIds[];
        static const int s_precacheableProperties[];
        DispatchVectorHelper<winrt::Windows::Foundation::Collections::IVectorView<
                winrt::Windows::Foundation::IWwwFormUrlDecoderEntry>,
            false, winrt::Windows::Foundation::IWwwFormUrlDecoderEntry> m_dispatchCollectionHelper;
};
}

namespace wv2winrt_impl
{
struct Class_Windows_Foundation_Collections_MapChangedEventHandler_2_HSTRING_IInspectable_ : winrt::implements<
    Class_Windows_Foundation_Collections_MapChangedEventHandler_2_HSTRING_IInspectable_,
    DispatchBase>
{
    public:
        Class_Windows_Foundation_Collections_MapChangedEventHandler_2_HSTRING_IInspectable_(::IInspectable* innerObject, const winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter& dispatchAdapter);

        // IDispatch methods
        HRESULT STDMETHODCALLTYPE GetIDsOfNames(REFIID riid,
                                                LPOLESTR* names,
                                                unsigned int namesCount,
                                                LCID localeId,
                                                DISPID* dispId) override;
        HRESULT STDMETHODCALLTYPE Invoke(DISPID dispId,
                                         REFIID riid,
                                         LCID localeId,
                                         WORD flags,
                                         DISPPARAMS* dispParams,
                                         VARIANT* result,
                                         EXCEPINFO* excepInfo,
                                         UINT* argErr) override;

        // ICoreWebView2PrivateDispatchContainer methods
        HRESULT STDMETHODCALLTYPE GetInnerObject(IUnknown** object) override;
        HRESULT STDMETHODCALLTYPE GetPropertyNames(wchar_t***, size_t*);
        HRESULT STDMETHODCALLTYPE GetPropertiesPrecacheability(BOOL** boolsOut, size_t* propertiesLengthOut);

    private:
        winrt::com_ptr<::IInspectable> m_innerObject;
        winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter m_dispatchAdapter;
        static DispatchProperties s_dispatchProperties;
        static const DISPID s_dispatchIds[];
        static const int s_precacheableProperties[];
};
}

namespace wv2winrt_impl
{
struct Class_Windows_Foundation_Collections_IVectorView_1_Windows_System_UserWatcherUpdateKind_ : winrt::implements<
    Class_Windows_Foundation_Collections_IVectorView_1_Windows_System_UserWatcherUpdateKind_,
    DispatchBase>
{
    public:
        Class_Windows_Foundation_Collections_IVectorView_1_Windows_System_UserWatcherUpdateKind_(::IInspectable* innerObject, const winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter& dispatchAdapter);

        // IDispatch methods
        HRESULT STDMETHODCALLTYPE GetIDsOfNames(REFIID riid,
                                                LPOLESTR* names,
                                                unsigned int namesCount,
                                                LCID localeId,
                                                DISPID* dispId) override;
        HRESULT STDMETHODCALLTYPE Invoke(DISPID dispId,
                                         REFIID riid,
                                         LCID localeId,
                                         WORD flags,
                                         DISPPARAMS* dispParams,
                                         VARIANT* result,
                                         EXCEPINFO* excepInfo,
                                         UINT* argErr) override;

        // ICoreWebView2PrivateDispatchContainer methods
        HRESULT STDMETHODCALLTYPE GetInnerObject(IUnknown** object) override;
        HRESULT STDMETHODCALLTYPE GetScriptBehavior(DWORD* behavior)
        {
            *behavior = DispatchContainerScriptBehaviorVector;
            return S_OK;
        }
        HRESULT STDMETHODCALLTYPE GetPropertyNames(wchar_t***, size_t*);
        HRESULT STDMETHODCALLTYPE GetPropertiesPrecacheability(BOOL** boolsOut, size_t* propertiesLengthOut);

    private:
        winrt::com_ptr<::IInspectable> m_innerObject;
        winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter m_dispatchAdapter;
        static DispatchProperties s_dispatchProperties;
        static const DISPID s_dispatchIds[];
        static const int s_precacheableProperties[];
        DispatchVectorHelper<winrt::Windows::Foundation::Collections::IVectorView<
                winrt::Windows::System::UserWatcherUpdateKind>,
            false, winrt::Windows::System::UserWatcherUpdateKind> m_dispatchCollectionHelper;
};
}

namespace wv2winrt_impl
{
struct Class_Windows_Foundation_Collections_IIterable_1_Windows_Storage_StorageFile_ : winrt::implements<
    Class_Windows_Foundation_Collections_IIterable_1_Windows_Storage_StorageFile_,
    DispatchBase>
{
    public:
        Class_Windows_Foundation_Collections_IIterable_1_Windows_Storage_StorageFile_(::IInspectable* innerObject, const winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter& dispatchAdapter);

        // IDispatch methods
        HRESULT STDMETHODCALLTYPE GetIDsOfNames(REFIID riid,
                                                LPOLESTR* names,
                                                unsigned int namesCount,
                                                LCID localeId,
                                                DISPID* dispId) override;
        HRESULT STDMETHODCALLTYPE Invoke(DISPID dispId,
                                         REFIID riid,
                                         LCID localeId,
                                         WORD flags,
                                         DISPPARAMS* dispParams,
                                         VARIANT* result,
                                         EXCEPINFO* excepInfo,
                                         UINT* argErr) override;

        // ICoreWebView2PrivateDispatchContainer methods
        HRESULT STDMETHODCALLTYPE GetInnerObject(IUnknown** object) override;
        HRESULT STDMETHODCALLTYPE GetPropertyNames(wchar_t***, size_t*);
        HRESULT STDMETHODCALLTYPE GetPropertiesPrecacheability(BOOL** boolsOut, size_t* propertiesLengthOut);

    private:
        winrt::com_ptr<::IInspectable> m_innerObject;
        winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter m_dispatchAdapter;
        static DispatchProperties s_dispatchProperties;
        static const DISPID s_dispatchIds[];
        static const int s_precacheableProperties[];
};
}

namespace wv2winrt_impl
{
struct Class_Windows_Foundation_Collections_IIterator_1_Windows_Storage_StorageFile_ : winrt::implements<
    Class_Windows_Foundation_Collections_IIterator_1_Windows_Storage_StorageFile_,
    DispatchBase>
{
    public:
        Class_Windows_Foundation_Collections_IIterator_1_Windows_Storage_StorageFile_(::IInspectable* innerObject, const winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter& dispatchAdapter);

        // IDispatch methods
        HRESULT STDMETHODCALLTYPE GetIDsOfNames(REFIID riid,
                                                LPOLESTR* names,
                                                unsigned int namesCount,
                                                LCID localeId,
                                                DISPID* dispId) override;
        HRESULT STDMETHODCALLTYPE Invoke(DISPID dispId,
                                         REFIID riid,
                                         LCID localeId,
                                         WORD flags,
                                         DISPPARAMS* dispParams,
                                         VARIANT* result,
                                         EXCEPINFO* excepInfo,
                                         UINT* argErr) override;

        // ICoreWebView2PrivateDispatchContainer methods
        HRESULT STDMETHODCALLTYPE GetInnerObject(IUnknown** object) override;
        HRESULT STDMETHODCALLTYPE GetPropertyNames(wchar_t***, size_t*);
        HRESULT STDMETHODCALLTYPE GetPropertiesPrecacheability(BOOL** boolsOut, size_t* propertiesLengthOut);

    private:
        winrt::com_ptr<::IInspectable> m_innerObject;
        winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter m_dispatchAdapter;
        static DispatchProperties s_dispatchProperties;
        static const DISPID s_dispatchIds[];
        static const int s_precacheableProperties[];
};
}

namespace wv2winrt_impl
{
struct Class_Windows_Foundation_Collections_IIterable_1_Windows_Storage_StorageFolder_ : winrt::implements<
    Class_Windows_Foundation_Collections_IIterable_1_Windows_Storage_StorageFolder_,
    DispatchBase>
{
    public:
        Class_Windows_Foundation_Collections_IIterable_1_Windows_Storage_StorageFolder_(::IInspectable* innerObject, const winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter& dispatchAdapter);

        // IDispatch methods
        HRESULT STDMETHODCALLTYPE GetIDsOfNames(REFIID riid,
                                                LPOLESTR* names,
                                                unsigned int namesCount,
                                                LCID localeId,
                                                DISPID* dispId) override;
        HRESULT STDMETHODCALLTYPE Invoke(DISPID dispId,
                                         REFIID riid,
                                         LCID localeId,
                                         WORD flags,
                                         DISPPARAMS* dispParams,
                                         VARIANT* result,
                                         EXCEPINFO* excepInfo,
                                         UINT* argErr) override;

        // ICoreWebView2PrivateDispatchContainer methods
        HRESULT STDMETHODCALLTYPE GetInnerObject(IUnknown** object) override;
        HRESULT STDMETHODCALLTYPE GetPropertyNames(wchar_t***, size_t*);
        HRESULT STDMETHODCALLTYPE GetPropertiesPrecacheability(BOOL** boolsOut, size_t* propertiesLengthOut);

    private:
        winrt::com_ptr<::IInspectable> m_innerObject;
        winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter m_dispatchAdapter;
        static DispatchProperties s_dispatchProperties;
        static const DISPID s_dispatchIds[];
        static const int s_precacheableProperties[];
};
}

namespace wv2winrt_impl
{
struct Class_Windows_Foundation_Collections_IIterator_1_Windows_Storage_StorageFolder_ : winrt::implements<
    Class_Windows_Foundation_Collections_IIterator_1_Windows_Storage_StorageFolder_,
    DispatchBase>
{
    public:
        Class_Windows_Foundation_Collections_IIterator_1_Windows_Storage_StorageFolder_(::IInspectable* innerObject, const winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter& dispatchAdapter);

        // IDispatch methods
        HRESULT STDMETHODCALLTYPE GetIDsOfNames(REFIID riid,
                                                LPOLESTR* names,
                                                unsigned int namesCount,
                                                LCID localeId,
                                                DISPID* dispId) override;
        HRESULT STDMETHODCALLTYPE Invoke(DISPID dispId,
                                         REFIID riid,
                                         LCID localeId,
                                         WORD flags,
                                         DISPPARAMS* dispParams,
                                         VARIANT* result,
                                         EXCEPINFO* excepInfo,
                                         UINT* argErr) override;

        // ICoreWebView2PrivateDispatchContainer methods
        HRESULT STDMETHODCALLTYPE GetInnerObject(IUnknown** object) override;
        HRESULT STDMETHODCALLTYPE GetPropertyNames(wchar_t***, size_t*);
        HRESULT STDMETHODCALLTYPE GetPropertiesPrecacheability(BOOL** boolsOut, size_t* propertiesLengthOut);

    private:
        winrt::com_ptr<::IInspectable> m_innerObject;
        winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter m_dispatchAdapter;
        static DispatchProperties s_dispatchProperties;
        static const DISPID s_dispatchIds[];
        static const int s_precacheableProperties[];
};
}

namespace wv2winrt_impl
{
struct Class_Windows_Foundation_Collections_IIterable_1_Windows_Storage_IStorageItem_ : winrt::implements<
    Class_Windows_Foundation_Collections_IIterable_1_Windows_Storage_IStorageItem_,
    DispatchBase>
{
    public:
        Class_Windows_Foundation_Collections_IIterable_1_Windows_Storage_IStorageItem_(::IInspectable* innerObject, const winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter& dispatchAdapter);

        // IDispatch methods
        HRESULT STDMETHODCALLTYPE GetIDsOfNames(REFIID riid,
                                                LPOLESTR* names,
                                                unsigned int namesCount,
                                                LCID localeId,
                                                DISPID* dispId) override;
        HRESULT STDMETHODCALLTYPE Invoke(DISPID dispId,
                                         REFIID riid,
                                         LCID localeId,
                                         WORD flags,
                                         DISPPARAMS* dispParams,
                                         VARIANT* result,
                                         EXCEPINFO* excepInfo,
                                         UINT* argErr) override;

        // ICoreWebView2PrivateDispatchContainer methods
        HRESULT STDMETHODCALLTYPE GetInnerObject(IUnknown** object) override;
        HRESULT STDMETHODCALLTYPE GetPropertyNames(wchar_t***, size_t*);
        HRESULT STDMETHODCALLTYPE GetPropertiesPrecacheability(BOOL** boolsOut, size_t* propertiesLengthOut);

    private:
        winrt::com_ptr<::IInspectable> m_innerObject;
        winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter m_dispatchAdapter;
        static DispatchProperties s_dispatchProperties;
        static const DISPID s_dispatchIds[];
        static const int s_precacheableProperties[];
};
}

namespace wv2winrt_impl
{
struct Class_Windows_Foundation_Collections_IIterator_1_Windows_Storage_IStorageItem_ : winrt::implements<
    Class_Windows_Foundation_Collections_IIterator_1_Windows_Storage_IStorageItem_,
    DispatchBase>
{
    public:
        Class_Windows_Foundation_Collections_IIterator_1_Windows_Storage_IStorageItem_(::IInspectable* innerObject, const winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter& dispatchAdapter);

        // IDispatch methods
        HRESULT STDMETHODCALLTYPE GetIDsOfNames(REFIID riid,
                                                LPOLESTR* names,
                                                unsigned int namesCount,
                                                LCID localeId,
                                                DISPID* dispId) override;
        HRESULT STDMETHODCALLTYPE Invoke(DISPID dispId,
                                         REFIID riid,
                                         LCID localeId,
                                         WORD flags,
                                         DISPPARAMS* dispParams,
                                         VARIANT* result,
                                         EXCEPINFO* excepInfo,
                                         UINT* argErr) override;

        // ICoreWebView2PrivateDispatchContainer methods
        HRESULT STDMETHODCALLTYPE GetInnerObject(IUnknown** object) override;
        HRESULT STDMETHODCALLTYPE GetPropertyNames(wchar_t***, size_t*);
        HRESULT STDMETHODCALLTYPE GetPropertiesPrecacheability(BOOL** boolsOut, size_t* propertiesLengthOut);

    private:
        winrt::com_ptr<::IInspectable> m_innerObject;
        winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter m_dispatchAdapter;
        static DispatchProperties s_dispatchProperties;
        static const DISPID s_dispatchIds[];
        static const int s_precacheableProperties[];
};
}

namespace wv2winrt_impl
{
struct Class_Windows_Foundation_Collections_IMap_2_HSTRING_Windows_Foundation_Collections_IVectorView_1_Windows_Data_Text_TextSegment__ : winrt::implements<
    Class_Windows_Foundation_Collections_IMap_2_HSTRING_Windows_Foundation_Collections_IVectorView_1_Windows_Data_Text_TextSegment__,
    DispatchBase>
{
    public:
        Class_Windows_Foundation_Collections_IMap_2_HSTRING_Windows_Foundation_Collections_IVectorView_1_Windows_Data_Text_TextSegment__(::IInspectable* innerObject, const winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter& dispatchAdapter);

        // IDispatch methods
        HRESULT STDMETHODCALLTYPE GetIDsOfNames(REFIID riid,
                                                LPOLESTR* names,
                                                unsigned int namesCount,
                                                LCID localeId,
                                                DISPID* dispId) override;
        HRESULT STDMETHODCALLTYPE Invoke(DISPID dispId,
                                         REFIID riid,
                                         LCID localeId,
                                         WORD flags,
                                         DISPPARAMS* dispParams,
                                         VARIANT* result,
                                         EXCEPINFO* excepInfo,
                                         UINT* argErr) override;

        // ICoreWebView2PrivateDispatchContainer methods
        HRESULT STDMETHODCALLTYPE GetInnerObject(IUnknown** object) override;
        HRESULT STDMETHODCALLTYPE GetScriptBehavior(DWORD* behavior)
        {
            *behavior = DispatchContainerScriptBehaviorMap;
            return S_OK;
        }
        HRESULT STDMETHODCALLTYPE GetPropertyNames(wchar_t***, size_t*);
        HRESULT STDMETHODCALLTYPE GetPropertiesPrecacheability(BOOL** boolsOut, size_t* propertiesLengthOut);

    private:
        winrt::com_ptr<::IInspectable> m_innerObject;
        winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter m_dispatchAdapter;
        static DispatchProperties s_dispatchProperties;
        static const DISPID s_dispatchIds[];
        static const int s_precacheableProperties[];
        DispatchMapHelper<winrt::Windows::Foundation::Collections::IMap<
                winrt::hstring, winrt::Windows::Foundation::Collections::IVectorView<winrt::Windows::Data::Text::TextSegment>>,

            true, winrt::Windows::Foundation::Collections::IVectorView<winrt::Windows::Data::Text::TextSegment>> m_dispatchCollectionHelper;
};
}

namespace wv2winrt_impl
{
struct Class_Windows_Foundation_Collections_IVector_1_Windows_Storage_Search_SortEntry_ : winrt::implements<
    Class_Windows_Foundation_Collections_IVector_1_Windows_Storage_Search_SortEntry_,
    DispatchBase>
{
    public:
        Class_Windows_Foundation_Collections_IVector_1_Windows_Storage_Search_SortEntry_(::IInspectable* innerObject, const winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter& dispatchAdapter);

        // IDispatch methods
        HRESULT STDMETHODCALLTYPE GetIDsOfNames(REFIID riid,
                                                LPOLESTR* names,
                                                unsigned int namesCount,
                                                LCID localeId,
                                                DISPID* dispId) override;
        HRESULT STDMETHODCALLTYPE Invoke(DISPID dispId,
                                         REFIID riid,
                                         LCID localeId,
                                         WORD flags,
                                         DISPPARAMS* dispParams,
                                         VARIANT* result,
                                         EXCEPINFO* excepInfo,
                                         UINT* argErr) override;

        // ICoreWebView2PrivateDispatchContainer methods
        HRESULT STDMETHODCALLTYPE GetInnerObject(IUnknown** object) override;
        HRESULT STDMETHODCALLTYPE GetScriptBehavior(DWORD* behavior)
        {
            *behavior = DispatchContainerScriptBehaviorVector;
            return S_OK;
        }
        HRESULT STDMETHODCALLTYPE GetPropertyNames(wchar_t***, size_t*);
        HRESULT STDMETHODCALLTYPE GetPropertiesPrecacheability(BOOL** boolsOut, size_t* propertiesLengthOut);

    private:
        winrt::com_ptr<::IInspectable> m_innerObject;
        winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter m_dispatchAdapter;
        static DispatchProperties s_dispatchProperties;
        static const DISPID s_dispatchIds[];
        static const int s_precacheableProperties[];
        DispatchVectorHelper<winrt::Windows::Foundation::Collections::IVector<
                winrt::Windows::Storage::Search::SortEntry>,
            true, winrt::Windows::Storage::Search::SortEntry> m_dispatchCollectionHelper;
};
}

namespace wv2winrt_impl
{
struct Class_Windows_Foundation_Collections_IIterable_1_Windows_System_UserWatcherUpdateKind_ : winrt::implements<
    Class_Windows_Foundation_Collections_IIterable_1_Windows_System_UserWatcherUpdateKind_,
    DispatchBase>
{
    public:
        Class_Windows_Foundation_Collections_IIterable_1_Windows_System_UserWatcherUpdateKind_(::IInspectable* innerObject, const winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter& dispatchAdapter);

        // IDispatch methods
        HRESULT STDMETHODCALLTYPE GetIDsOfNames(REFIID riid,
                                                LPOLESTR* names,
                                                unsigned int namesCount,
                                                LCID localeId,
                                                DISPID* dispId) override;
        HRESULT STDMETHODCALLTYPE Invoke(DISPID dispId,
                                         REFIID riid,
                                         LCID localeId,
                                         WORD flags,
                                         DISPPARAMS* dispParams,
                                         VARIANT* result,
                                         EXCEPINFO* excepInfo,
                                         UINT* argErr) override;

        // ICoreWebView2PrivateDispatchContainer methods
        HRESULT STDMETHODCALLTYPE GetInnerObject(IUnknown** object) override;
        HRESULT STDMETHODCALLTYPE GetPropertyNames(wchar_t***, size_t*);
        HRESULT STDMETHODCALLTYPE GetPropertiesPrecacheability(BOOL** boolsOut, size_t* propertiesLengthOut);

    private:
        winrt::com_ptr<::IInspectable> m_innerObject;
        winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter m_dispatchAdapter;
        static DispatchProperties s_dispatchProperties;
        static const DISPID s_dispatchIds[];
        static const int s_precacheableProperties[];
};
}

namespace wv2winrt_impl
{
struct Class_Windows_Foundation_Collections_IIterator_1_Windows_System_UserWatcherUpdateKind_ : winrt::implements<
    Class_Windows_Foundation_Collections_IIterator_1_Windows_System_UserWatcherUpdateKind_,
    DispatchBase>
{
    public:
        Class_Windows_Foundation_Collections_IIterator_1_Windows_System_UserWatcherUpdateKind_(::IInspectable* innerObject, const winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter& dispatchAdapter);

        // IDispatch methods
        HRESULT STDMETHODCALLTYPE GetIDsOfNames(REFIID riid,
                                                LPOLESTR* names,
                                                unsigned int namesCount,
                                                LCID localeId,
                                                DISPID* dispId) override;
        HRESULT STDMETHODCALLTYPE Invoke(DISPID dispId,
                                         REFIID riid,
                                         LCID localeId,
                                         WORD flags,
                                         DISPPARAMS* dispParams,
                                         VARIANT* result,
                                         EXCEPINFO* excepInfo,
                                         UINT* argErr) override;

        // ICoreWebView2PrivateDispatchContainer methods
        HRESULT STDMETHODCALLTYPE GetInnerObject(IUnknown** object) override;
        HRESULT STDMETHODCALLTYPE GetPropertyNames(wchar_t***, size_t*);
        HRESULT STDMETHODCALLTYPE GetPropertiesPrecacheability(BOOL** boolsOut, size_t* propertiesLengthOut);

    private:
        winrt::com_ptr<::IInspectable> m_innerObject;
        winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter m_dispatchAdapter;
        static DispatchProperties s_dispatchProperties;
        static const DISPID s_dispatchIds[];
        static const int s_precacheableProperties[];
};
}

namespace wv2winrt_impl
{
struct Class_Windows_Foundation_Collections_IVectorView_1_Windows_Data_Text_TextSegment_ : winrt::implements<
    Class_Windows_Foundation_Collections_IVectorView_1_Windows_Data_Text_TextSegment_,
    DispatchBase>
{
    public:
        Class_Windows_Foundation_Collections_IVectorView_1_Windows_Data_Text_TextSegment_(::IInspectable* innerObject, const winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter& dispatchAdapter);

        // IDispatch methods
        HRESULT STDMETHODCALLTYPE GetIDsOfNames(REFIID riid,
                                                LPOLESTR* names,
                                                unsigned int namesCount,
                                                LCID localeId,
                                                DISPID* dispId) override;
        HRESULT STDMETHODCALLTYPE Invoke(DISPID dispId,
                                         REFIID riid,
                                         LCID localeId,
                                         WORD flags,
                                         DISPPARAMS* dispParams,
                                         VARIANT* result,
                                         EXCEPINFO* excepInfo,
                                         UINT* argErr) override;

        // ICoreWebView2PrivateDispatchContainer methods
        HRESULT STDMETHODCALLTYPE GetInnerObject(IUnknown** object) override;
        HRESULT STDMETHODCALLTYPE GetScriptBehavior(DWORD* behavior)
        {
            *behavior = DispatchContainerScriptBehaviorVector;
            return S_OK;
        }
        HRESULT STDMETHODCALLTYPE GetPropertyNames(wchar_t***, size_t*);
        HRESULT STDMETHODCALLTYPE GetPropertiesPrecacheability(BOOL** boolsOut, size_t* propertiesLengthOut);

    private:
        winrt::com_ptr<::IInspectable> m_innerObject;
        winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter m_dispatchAdapter;
        static DispatchProperties s_dispatchProperties;
        static const DISPID s_dispatchIds[];
        static const int s_precacheableProperties[];
        DispatchVectorHelper<winrt::Windows::Foundation::Collections::IVectorView<
                winrt::Windows::Data::Text::TextSegment>,
            false, winrt::Windows::Data::Text::TextSegment> m_dispatchCollectionHelper;
};
}

namespace wv2winrt_impl
{
struct Class_Windows_Foundation_Collections_IMapView_2_HSTRING_Windows_Foundation_Collections_IVectorView_1_Windows_Data_Text_TextSegment__ : winrt::implements<
    Class_Windows_Foundation_Collections_IMapView_2_HSTRING_Windows_Foundation_Collections_IVectorView_1_Windows_Data_Text_TextSegment__,
    DispatchBase>
{
    public:
        Class_Windows_Foundation_Collections_IMapView_2_HSTRING_Windows_Foundation_Collections_IVectorView_1_Windows_Data_Text_TextSegment__(::IInspectable* innerObject, const winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter& dispatchAdapter);

        // IDispatch methods
        HRESULT STDMETHODCALLTYPE GetIDsOfNames(REFIID riid,
                                                LPOLESTR* names,
                                                unsigned int namesCount,
                                                LCID localeId,
                                                DISPID* dispId) override;
        HRESULT STDMETHODCALLTYPE Invoke(DISPID dispId,
                                         REFIID riid,
                                         LCID localeId,
                                         WORD flags,
                                         DISPPARAMS* dispParams,
                                         VARIANT* result,
                                         EXCEPINFO* excepInfo,
                                         UINT* argErr) override;

        // ICoreWebView2PrivateDispatchContainer methods
        HRESULT STDMETHODCALLTYPE GetInnerObject(IUnknown** object) override;
        HRESULT STDMETHODCALLTYPE GetScriptBehavior(DWORD* behavior)
        {
            *behavior = DispatchContainerScriptBehaviorMap;
            return S_OK;
        }
        HRESULT STDMETHODCALLTYPE GetPropertyNames(wchar_t***, size_t*);
        HRESULT STDMETHODCALLTYPE GetPropertiesPrecacheability(BOOL** boolsOut, size_t* propertiesLengthOut);

    private:
        winrt::com_ptr<::IInspectable> m_innerObject;
        winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter m_dispatchAdapter;
        static DispatchProperties s_dispatchProperties;
        static const DISPID s_dispatchIds[];
        static const int s_precacheableProperties[];
        DispatchMapHelper<winrt::Windows::Foundation::Collections::IMapView<
                winrt::hstring, winrt::Windows::Foundation::Collections::IVectorView<winrt::Windows::Data::Text::TextSegment>>,

            false, winrt::Windows::Foundation::Collections::IVectorView<winrt::Windows::Data::Text::TextSegment>> m_dispatchCollectionHelper;
};
}

namespace wv2winrt_impl
{
struct Class_Windows_Foundation_Collections_IIterable_1_Windows_Foundation_Collections_IKeyValuePair_2_HSTRING_Windows_Foundation_Collections_IVectorView_1_Windows_Data_Text_TextSegment___ : winrt::implements<
    Class_Windows_Foundation_Collections_IIterable_1_Windows_Foundation_Collections_IKeyValuePair_2_HSTRING_Windows_Foundation_Collections_IVectorView_1_Windows_Data_Text_TextSegment___,
    DispatchBase>
{
    public:
        Class_Windows_Foundation_Collections_IIterable_1_Windows_Foundation_Collections_IKeyValuePair_2_HSTRING_Windows_Foundation_Collections_IVectorView_1_Windows_Data_Text_TextSegment___(::IInspectable* innerObject, const winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter& dispatchAdapter);

        // IDispatch methods
        HRESULT STDMETHODCALLTYPE GetIDsOfNames(REFIID riid,
                                                LPOLESTR* names,
                                                unsigned int namesCount,
                                                LCID localeId,
                                                DISPID* dispId) override;
        HRESULT STDMETHODCALLTYPE Invoke(DISPID dispId,
                                         REFIID riid,
                                         LCID localeId,
                                         WORD flags,
                                         DISPPARAMS* dispParams,
                                         VARIANT* result,
                                         EXCEPINFO* excepInfo,
                                         UINT* argErr) override;

        // ICoreWebView2PrivateDispatchContainer methods
        HRESULT STDMETHODCALLTYPE GetInnerObject(IUnknown** object) override;
        HRESULT STDMETHODCALLTYPE GetPropertyNames(wchar_t***, size_t*);
        HRESULT STDMETHODCALLTYPE GetPropertiesPrecacheability(BOOL** boolsOut, size_t* propertiesLengthOut);

    private:
        winrt::com_ptr<::IInspectable> m_innerObject;
        winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter m_dispatchAdapter;
        static DispatchProperties s_dispatchProperties;
        static const DISPID s_dispatchIds[];
        static const int s_precacheableProperties[];
};
}

namespace wv2winrt_impl
{
struct Class_Windows_Foundation_Collections_IIterator_1_Windows_Foundation_Collections_IKeyValuePair_2_HSTRING_Windows_Foundation_Collections_IVectorView_1_Windows_Data_Text_TextSegment___ : winrt::implements<
    Class_Windows_Foundation_Collections_IIterator_1_Windows_Foundation_Collections_IKeyValuePair_2_HSTRING_Windows_Foundation_Collections_IVectorView_1_Windows_Data_Text_TextSegment___,
    DispatchBase>
{
    public:
        Class_Windows_Foundation_Collections_IIterator_1_Windows_Foundation_Collections_IKeyValuePair_2_HSTRING_Windows_Foundation_Collections_IVectorView_1_Windows_Data_Text_TextSegment___(::IInspectable* innerObject, const winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter& dispatchAdapter);

        // IDispatch methods
        HRESULT STDMETHODCALLTYPE GetIDsOfNames(REFIID riid,
                                                LPOLESTR* names,
                                                unsigned int namesCount,
                                                LCID localeId,
                                                DISPID* dispId) override;
        HRESULT STDMETHODCALLTYPE Invoke(DISPID dispId,
                                         REFIID riid,
                                         LCID localeId,
                                         WORD flags,
                                         DISPPARAMS* dispParams,
                                         VARIANT* result,
                                         EXCEPINFO* excepInfo,
                                         UINT* argErr) override;

        // ICoreWebView2PrivateDispatchContainer methods
        HRESULT STDMETHODCALLTYPE GetInnerObject(IUnknown** object) override;
        HRESULT STDMETHODCALLTYPE GetPropertyNames(wchar_t***, size_t*);
        HRESULT STDMETHODCALLTYPE GetPropertiesPrecacheability(BOOL** boolsOut, size_t* propertiesLengthOut);

    private:
        winrt::com_ptr<::IInspectable> m_innerObject;
        winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter m_dispatchAdapter;
        static DispatchProperties s_dispatchProperties;
        static const DISPID s_dispatchIds[];
        static const int s_precacheableProperties[];
};
}

namespace wv2winrt_impl
{
struct Class_Windows_Foundation_Collections_IVectorView_1_Windows_Storage_Search_SortEntry_ : winrt::implements<
    Class_Windows_Foundation_Collections_IVectorView_1_Windows_Storage_Search_SortEntry_,
    DispatchBase>
{
    public:
        Class_Windows_Foundation_Collections_IVectorView_1_Windows_Storage_Search_SortEntry_(::IInspectable* innerObject, const winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter& dispatchAdapter);

        // IDispatch methods
        HRESULT STDMETHODCALLTYPE GetIDsOfNames(REFIID riid,
                                                LPOLESTR* names,
                                                unsigned int namesCount,
                                                LCID localeId,
                                                DISPID* dispId) override;
        HRESULT STDMETHODCALLTYPE Invoke(DISPID dispId,
                                         REFIID riid,
                                         LCID localeId,
                                         WORD flags,
                                         DISPPARAMS* dispParams,
                                         VARIANT* result,
                                         EXCEPINFO* excepInfo,
                                         UINT* argErr) override;

        // ICoreWebView2PrivateDispatchContainer methods
        HRESULT STDMETHODCALLTYPE GetInnerObject(IUnknown** object) override;
        HRESULT STDMETHODCALLTYPE GetScriptBehavior(DWORD* behavior)
        {
            *behavior = DispatchContainerScriptBehaviorVector;
            return S_OK;
        }
        HRESULT STDMETHODCALLTYPE GetPropertyNames(wchar_t***, size_t*);
        HRESULT STDMETHODCALLTYPE GetPropertiesPrecacheability(BOOL** boolsOut, size_t* propertiesLengthOut);

    private:
        winrt::com_ptr<::IInspectable> m_innerObject;
        winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter m_dispatchAdapter;
        static DispatchProperties s_dispatchProperties;
        static const DISPID s_dispatchIds[];
        static const int s_precacheableProperties[];
        DispatchVectorHelper<winrt::Windows::Foundation::Collections::IVectorView<
                winrt::Windows::Storage::Search::SortEntry>,
            false, winrt::Windows::Storage::Search::SortEntry> m_dispatchCollectionHelper;
};
}

namespace wv2winrt_impl
{
struct Class_Windows_Foundation_Collections_IIterable_1_Windows_Storage_Search_SortEntry_ : winrt::implements<
    Class_Windows_Foundation_Collections_IIterable_1_Windows_Storage_Search_SortEntry_,
    DispatchBase>
{
    public:
        Class_Windows_Foundation_Collections_IIterable_1_Windows_Storage_Search_SortEntry_(::IInspectable* innerObject, const winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter& dispatchAdapter);

        // IDispatch methods
        HRESULT STDMETHODCALLTYPE GetIDsOfNames(REFIID riid,
                                                LPOLESTR* names,
                                                unsigned int namesCount,
                                                LCID localeId,
                                                DISPID* dispId) override;
        HRESULT STDMETHODCALLTYPE Invoke(DISPID dispId,
                                         REFIID riid,
                                         LCID localeId,
                                         WORD flags,
                                         DISPPARAMS* dispParams,
                                         VARIANT* result,
                                         EXCEPINFO* excepInfo,
                                         UINT* argErr) override;

        // ICoreWebView2PrivateDispatchContainer methods
        HRESULT STDMETHODCALLTYPE GetInnerObject(IUnknown** object) override;
        HRESULT STDMETHODCALLTYPE GetPropertyNames(wchar_t***, size_t*);
        HRESULT STDMETHODCALLTYPE GetPropertiesPrecacheability(BOOL** boolsOut, size_t* propertiesLengthOut);

    private:
        winrt::com_ptr<::IInspectable> m_innerObject;
        winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter m_dispatchAdapter;
        static DispatchProperties s_dispatchProperties;
        static const DISPID s_dispatchIds[];
        static const int s_precacheableProperties[];
};
}

namespace wv2winrt_impl
{
struct Class_Windows_Foundation_Collections_IIterator_1_Windows_Storage_Search_SortEntry_ : winrt::implements<
    Class_Windows_Foundation_Collections_IIterator_1_Windows_Storage_Search_SortEntry_,
    DispatchBase>
{
    public:
        Class_Windows_Foundation_Collections_IIterator_1_Windows_Storage_Search_SortEntry_(::IInspectable* innerObject, const winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter& dispatchAdapter);

        // IDispatch methods
        HRESULT STDMETHODCALLTYPE GetIDsOfNames(REFIID riid,
                                                LPOLESTR* names,
                                                unsigned int namesCount,
                                                LCID localeId,
                                                DISPID* dispId) override;
        HRESULT STDMETHODCALLTYPE Invoke(DISPID dispId,
                                         REFIID riid,
                                         LCID localeId,
                                         WORD flags,
                                         DISPPARAMS* dispParams,
                                         VARIANT* result,
                                         EXCEPINFO* excepInfo,
                                         UINT* argErr) override;

        // ICoreWebView2PrivateDispatchContainer methods
        HRESULT STDMETHODCALLTYPE GetInnerObject(IUnknown** object) override;
        HRESULT STDMETHODCALLTYPE GetPropertyNames(wchar_t***, size_t*);
        HRESULT STDMETHODCALLTYPE GetPropertiesPrecacheability(BOOL** boolsOut, size_t* propertiesLengthOut);

    private:
        winrt::com_ptr<::IInspectable> m_innerObject;
        winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter m_dispatchAdapter;
        static DispatchProperties s_dispatchProperties;
        static const DISPID s_dispatchIds[];
        static const int s_precacheableProperties[];
};
}

namespace wv2winrt_impl
{
struct Class_Windows_Foundation_Collections_IIterable_1_Windows_Data_Text_TextSegment_ : winrt::implements<
    Class_Windows_Foundation_Collections_IIterable_1_Windows_Data_Text_TextSegment_,
    DispatchBase>
{
    public:
        Class_Windows_Foundation_Collections_IIterable_1_Windows_Data_Text_TextSegment_(::IInspectable* innerObject, const winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter& dispatchAdapter);

        // IDispatch methods
        HRESULT STDMETHODCALLTYPE GetIDsOfNames(REFIID riid,
                                                LPOLESTR* names,
                                                unsigned int namesCount,
                                                LCID localeId,
                                                DISPID* dispId) override;
        HRESULT STDMETHODCALLTYPE Invoke(DISPID dispId,
                                         REFIID riid,
                                         LCID localeId,
                                         WORD flags,
                                         DISPPARAMS* dispParams,
                                         VARIANT* result,
                                         EXCEPINFO* excepInfo,
                                         UINT* argErr) override;

        // ICoreWebView2PrivateDispatchContainer methods
        HRESULT STDMETHODCALLTYPE GetInnerObject(IUnknown** object) override;
        HRESULT STDMETHODCALLTYPE GetPropertyNames(wchar_t***, size_t*);
        HRESULT STDMETHODCALLTYPE GetPropertiesPrecacheability(BOOL** boolsOut, size_t* propertiesLengthOut);

    private:
        winrt::com_ptr<::IInspectable> m_innerObject;
        winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter m_dispatchAdapter;
        static DispatchProperties s_dispatchProperties;
        static const DISPID s_dispatchIds[];
        static const int s_precacheableProperties[];
};
}

namespace wv2winrt_impl
{
struct Class_Windows_Foundation_Collections_IIterator_1_Windows_Data_Text_TextSegment_ : winrt::implements<
    Class_Windows_Foundation_Collections_IIterator_1_Windows_Data_Text_TextSegment_,
    DispatchBase>
{
    public:
        Class_Windows_Foundation_Collections_IIterator_1_Windows_Data_Text_TextSegment_(::IInspectable* innerObject, const winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter& dispatchAdapter);

        // IDispatch methods
        HRESULT STDMETHODCALLTYPE GetIDsOfNames(REFIID riid,
                                                LPOLESTR* names,
                                                unsigned int namesCount,
                                                LCID localeId,
                                                DISPID* dispId) override;
        HRESULT STDMETHODCALLTYPE Invoke(DISPID dispId,
                                         REFIID riid,
                                         LCID localeId,
                                         WORD flags,
                                         DISPPARAMS* dispParams,
                                         VARIANT* result,
                                         EXCEPINFO* excepInfo,
                                         UINT* argErr) override;

        // ICoreWebView2PrivateDispatchContainer methods
        HRESULT STDMETHODCALLTYPE GetInnerObject(IUnknown** object) override;
        HRESULT STDMETHODCALLTYPE GetPropertyNames(wchar_t***, size_t*);
        HRESULT STDMETHODCALLTYPE GetPropertiesPrecacheability(BOOL** boolsOut, size_t* propertiesLengthOut);

    private:
        winrt::com_ptr<::IInspectable> m_innerObject;
        winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter m_dispatchAdapter;
        static DispatchProperties s_dispatchProperties;
        static const DISPID s_dispatchIds[];
        static const int s_precacheableProperties[];
};
}

namespace wv2winrt_impl
{
struct Class_Windows_Foundation_Collections_IKeyValuePair_2_HSTRING_Windows_Foundation_Collections_IVectorView_1_Windows_Data_Text_TextSegment__ : winrt::implements<
    Class_Windows_Foundation_Collections_IKeyValuePair_2_HSTRING_Windows_Foundation_Collections_IVectorView_1_Windows_Data_Text_TextSegment__,
    DispatchBase>
{
    public:
        Class_Windows_Foundation_Collections_IKeyValuePair_2_HSTRING_Windows_Foundation_Collections_IVectorView_1_Windows_Data_Text_TextSegment__(::IInspectable* innerObject, const winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter& dispatchAdapter);

        // IDispatch methods
        HRESULT STDMETHODCALLTYPE GetIDsOfNames(REFIID riid,
                                                LPOLESTR* names,
                                                unsigned int namesCount,
                                                LCID localeId,
                                                DISPID* dispId) override;
        HRESULT STDMETHODCALLTYPE Invoke(DISPID dispId,
                                         REFIID riid,
                                         LCID localeId,
                                         WORD flags,
                                         DISPPARAMS* dispParams,
                                         VARIANT* result,
                                         EXCEPINFO* excepInfo,
                                         UINT* argErr) override;

        // ICoreWebView2PrivateDispatchContainer methods
        HRESULT STDMETHODCALLTYPE GetInnerObject(IUnknown** object) override;
        HRESULT STDMETHODCALLTYPE GetPropertyNames(wchar_t***, size_t*);
        HRESULT STDMETHODCALLTYPE GetPropertiesPrecacheability(BOOL** boolsOut, size_t* propertiesLengthOut);

    private:
        winrt::com_ptr<::IInspectable> m_innerObject;
        winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter m_dispatchAdapter;
        static DispatchProperties s_dispatchProperties;
        static const DISPID s_dispatchIds[];
        static const int s_precacheableProperties[];
};
}

namespace wv2winrt_impl
{
struct Class_Windows_Foundation_Collections_IVectorView_1_Windows_Storage_StorageLibraryChange_ : winrt::implements<
    Class_Windows_Foundation_Collections_IVectorView_1_Windows_Storage_StorageLibraryChange_,
    DispatchBase>
{
    public:
        Class_Windows_Foundation_Collections_IVectorView_1_Windows_Storage_StorageLibraryChange_(::IInspectable* innerObject, const winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter& dispatchAdapter);

        // IDispatch methods
        HRESULT STDMETHODCALLTYPE GetIDsOfNames(REFIID riid,
                                                LPOLESTR* names,
                                                unsigned int namesCount,
                                                LCID localeId,
                                                DISPID* dispId) override;
        HRESULT STDMETHODCALLTYPE Invoke(DISPID dispId,
                                         REFIID riid,
                                         LCID localeId,
                                         WORD flags,
                                         DISPPARAMS* dispParams,
                                         VARIANT* result,
                                         EXCEPINFO* excepInfo,
                                         UINT* argErr) override;

        // ICoreWebView2PrivateDispatchContainer methods
        HRESULT STDMETHODCALLTYPE GetInnerObject(IUnknown** object) override;
        HRESULT STDMETHODCALLTYPE GetScriptBehavior(DWORD* behavior)
        {
            *behavior = DispatchContainerScriptBehaviorVector;
            return S_OK;
        }
        HRESULT STDMETHODCALLTYPE GetPropertyNames(wchar_t***, size_t*);
        HRESULT STDMETHODCALLTYPE GetPropertiesPrecacheability(BOOL** boolsOut, size_t* propertiesLengthOut);

    private:
        winrt::com_ptr<::IInspectable> m_innerObject;
        winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter m_dispatchAdapter;
        static DispatchProperties s_dispatchProperties;
        static const DISPID s_dispatchIds[];
        static const int s_precacheableProperties[];
        DispatchVectorHelper<winrt::Windows::Foundation::Collections::IVectorView<
                winrt::Windows::Storage::StorageLibraryChange>,
            false, winrt::Windows::Storage::StorageLibraryChange> m_dispatchCollectionHelper;
};
}

namespace wv2winrt_impl
{
struct Class_Windows_Foundation_Collections_IIterable_1_Windows_Storage_StorageLibraryChange_ : winrt::implements<
    Class_Windows_Foundation_Collections_IIterable_1_Windows_Storage_StorageLibraryChange_,
    DispatchBase>
{
    public:
        Class_Windows_Foundation_Collections_IIterable_1_Windows_Storage_StorageLibraryChange_(::IInspectable* innerObject, const winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter& dispatchAdapter);

        // IDispatch methods
        HRESULT STDMETHODCALLTYPE GetIDsOfNames(REFIID riid,
                                                LPOLESTR* names,
                                                unsigned int namesCount,
                                                LCID localeId,
                                                DISPID* dispId) override;
        HRESULT STDMETHODCALLTYPE Invoke(DISPID dispId,
                                         REFIID riid,
                                         LCID localeId,
                                         WORD flags,
                                         DISPPARAMS* dispParams,
                                         VARIANT* result,
                                         EXCEPINFO* excepInfo,
                                         UINT* argErr) override;

        // ICoreWebView2PrivateDispatchContainer methods
        HRESULT STDMETHODCALLTYPE GetInnerObject(IUnknown** object) override;
        HRESULT STDMETHODCALLTYPE GetPropertyNames(wchar_t***, size_t*);
        HRESULT STDMETHODCALLTYPE GetPropertiesPrecacheability(BOOL** boolsOut, size_t* propertiesLengthOut);

    private:
        winrt::com_ptr<::IInspectable> m_innerObject;
        winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter m_dispatchAdapter;
        static DispatchProperties s_dispatchProperties;
        static const DISPID s_dispatchIds[];
        static const int s_precacheableProperties[];
};
}

namespace wv2winrt_impl
{
struct Class_Windows_Foundation_Collections_IIterator_1_Windows_Storage_StorageLibraryChange_ : winrt::implements<
    Class_Windows_Foundation_Collections_IIterator_1_Windows_Storage_StorageLibraryChange_,
    DispatchBase>
{
    public:
        Class_Windows_Foundation_Collections_IIterator_1_Windows_Storage_StorageLibraryChange_(::IInspectable* innerObject, const winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter& dispatchAdapter);

        // IDispatch methods
        HRESULT STDMETHODCALLTYPE GetIDsOfNames(REFIID riid,
                                                LPOLESTR* names,
                                                unsigned int namesCount,
                                                LCID localeId,
                                                DISPID* dispId) override;
        HRESULT STDMETHODCALLTYPE Invoke(DISPID dispId,
                                         REFIID riid,
                                         LCID localeId,
                                         WORD flags,
                                         DISPPARAMS* dispParams,
                                         VARIANT* result,
                                         EXCEPINFO* excepInfo,
                                         UINT* argErr) override;

        // ICoreWebView2PrivateDispatchContainer methods
        HRESULT STDMETHODCALLTYPE GetInnerObject(IUnknown** object) override;
        HRESULT STDMETHODCALLTYPE GetPropertyNames(wchar_t***, size_t*);
        HRESULT STDMETHODCALLTYPE GetPropertiesPrecacheability(BOOL** boolsOut, size_t* propertiesLengthOut);

    private:
        winrt::com_ptr<::IInspectable> m_innerObject;
        winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter m_dispatchAdapter;
        static DispatchProperties s_dispatchProperties;
        static const DISPID s_dispatchIds[];
        static const int s_precacheableProperties[];
};
}
