// WARNING: Please don't edit this file. It was generated by wv2winrt v1.0.0.0
#include "pch.h"

#include "wv2winrt/asyncdispatch.h"
#include "wv2winrt/converter.h"
#include "wv2winrt/eventargsdispatch.h"
#include "wv2winrt/implicitstructs.g.h"
#include "wv2winrt/main.h"
#include "wv2winrt/returnaggregator.h"
#include "wv2winrt/uniquevariant.h"
#include "wv2winrt/Windows.Data.Text.g.h"
#include "wv2winrt/Windows.Data.Text.g.h"

namespace wv2winrt_impl
{
Namespace_Windows_Data_Text::Namespace_Windows_Data_Text(const winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter& dispatchAdapter)
    : m_dispatchAdapter(dispatchAdapter)
{
}

const static wchar_t* const s_Namespace_Windows_Data_Text_dispatchProperties[] =
{
    L"TextSegment"
};
DispatchProperties Namespace_Windows_Data_Text::s_dispatchProperties = s_Namespace_Windows_Data_Text_dispatchProperties;

const DISPID Namespace_Windows_Data_Text::s_dispatchIds[1] =
{
    327
};

HRESULT Namespace_Windows_Data_Text::GetPropertyNames(wchar_t*** namesOut, size_t* namesLengthOut)
{
    *namesLengthOut = ARRAYSIZE(s_Namespace_Windows_Data_Text_dispatchProperties);
    *namesOut = const_cast<wchar_t **>(s_dispatchProperties);
    return S_OK;
}

HRESULT Namespace_Windows_Data_Text::GetIDsOfNames(REFIID riid,
                                                  LPOLESTR* names,
                                                  unsigned int namesCount,
                                                  LCID localeId,
                                                  DISPID* dispId)
{
    HRESULT hr = DispatchBase::GetIDsOfNames(riid, names, namesCount, localeId, dispId);
    if (SUCCEEDED(hr))
    {
        hr = DISP_E_MEMBERNOTFOUND;
        size_t idx;
        if (LookupProperty(s_dispatchProperties, names[0], idx, 1))
        {
            *dispId = s_dispatchIds[idx];
            hr = S_OK;
        }
    }
    return hr;
}

HRESULT Namespace_Windows_Data_Text::Invoke(DISPID dispId,
                                           REFIID riid,
                                           LCID localeId,
                                           WORD flags,
                                           DISPPARAMS* dispParams,
                                           VARIANT* result,
                                           EXCEPINFO* excepInfo,
                                           UINT* argErr)
{
    HRESULT hr = DispatchBase::Invoke(dispId,
                                      riid,
                                      localeId,
                                      flags,
                                      dispParams,
                                      result,
                                      excepInfo,
                                      argErr);

    if (SUCCEEDED(hr))
    {
        hr = DISP_E_MEMBERNOTFOUND;
        if (flags == DISPATCH_PROPERTYGET)
        {
            if (dispParams->cArgs != 0 ||
                dispParams->rgvarg != nullptr)
            {
                hr = E_INVALIDARG;
            }
            else
            {
                winrt::com_ptr<IDispatch> dispatch;
#pragma warning( push )
#pragma warning( disable: 4065 )
                switch (dispId)
                {

                    default:
                        hr = DISP_E_MEMBERNOTFOUND;
                        break;
                }
#pragma warning( pop )

                if (SUCCEEDED(hr))
                {
                    // Copy dispatch into output result
                    VARIANT dispatchAsVariant;
                    dispatchAsVariant.vt = VT_DISPATCH;
                    dispatchAsVariant.pdispVal = dispatch.detach();
                    *result = dispatchAsVariant;
                }
            }
        }
        else if (flags == DISPATCH_METHOD || flags == 0)
        {
            switch (dispId)
            {
                case 327:
                {
                    // Invoke for Windows.Data.Text.TextSegment c'tor
                    if (2 == dispParams->cArgs)
                    {
                        hr = S_OK;
                        try
                        {
                            winrt::Windows::Data::Text::TextSegment resultAsWinRT{ Converter<VARIANT, uint32_t>(m_dispatchAdapter).Convert(dispParams->rgvarg[2 - 1]),
                Converter<VARIANT, uint32_t>(m_dispatchAdapter).Convert(dispParams->rgvarg[2 - 2]) };
                            *result = Converter<decltype(resultAsWinRT), VARIANT>(m_dispatchAdapter).Convert(resultAsWinRT);
                        }
                        catch (winrt::hresult_error)
                        {
                            hr = winrt::to_hresult();
                        }
                        catch (...)
                        {
                            hr = E_UNEXPECTED;
                        }
                    }
                    else
                    {
                        hr = DISP_E_BADPARAMCOUNT;
                    }
                    break;
                }

                default:
                    hr = DISP_E_MEMBERNOTFOUND;
                    break;
            }
        }
    }
    return hr;
}

}

namespace wv2winrt_impl
{
Struct_Windows_Data_Text_TextSegment::Struct_Windows_Data_Text_TextSegment(winrt::Windows::Data::Text::TextSegment innerObject, const winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter& dispatchAdapter)
    : m_innerObject(innerObject), m_dispatchAdapter(dispatchAdapter)
{
}

const static wchar_t* const s_Struct_Windows_Data_Text_TextSegment_dispatchProperties[] =
{
    L"length",
    L"startPosition"
};
DispatchProperties Struct_Windows_Data_Text_TextSegment::s_dispatchProperties = s_Struct_Windows_Data_Text_TextSegment_dispatchProperties;

const DISPID Struct_Windows_Data_Text_TextSegment::s_dispatchIds[2] =
{
    2,
    1
};

HRESULT Struct_Windows_Data_Text_TextSegment::GetIDsOfNames(REFIID riid,
                                             LPOLESTR* names,
                                             unsigned int namesCount,
                                             LCID localeId,
                                             DISPID* dispId)
{
    HRESULT hr = DispatchBase::GetIDsOfNames(
        riid, names, namesCount, localeId, dispId);

    if (SUCCEEDED(hr))
    {
        hr = DISP_E_MEMBERNOTFOUND;
        size_t idx;
        if (LookupProperty(s_dispatchProperties, names[0], idx, 2))
        {
            *dispId = s_dispatchIds[idx];
            hr = S_OK;
        }
    }
    return hr;
}

HRESULT Struct_Windows_Data_Text_TextSegment::Invoke(
    DISPID dispId,
    REFIID riid,
    LCID localeId,
    WORD flags,
    DISPPARAMS* dispParams,
    VARIANT* result,
    EXCEPINFO* excepInfo,
    UINT* argErr)
{
    HRESULT hr = DispatchBase::Invoke(dispId,
                                      riid,
                                      localeId,
                                      flags,
                                      dispParams,
                                      result,
                                      excepInfo,
                                      argErr);

    if (SUCCEEDED(hr))
    {
        hr = DISP_E_MEMBERNOTFOUND;

        if (flags == DISPATCH_PROPERTYGET || flags == DISPATCH_PROPERTYPUT)
        {
#pragma warning( push )
#pragma warning( disable: 4065 )
            switch (dispId)
            {
                case 1:
                    // Invoke for StartPosition
                    if (flags == DISPATCH_PROPERTYGET)
                    {
                        hr = S_OK;
                        try
                        {
                            auto resultAsWinRT = m_innerObject.StartPosition;
                            *result = Converter<decltype(resultAsWinRT), VARIANT>(m_dispatchAdapter).Convert(resultAsWinRT);
                        }
                        catch (winrt::hresult_error)
                        {
                            hr = winrt::to_hresult();
                        }
                        catch (...)
                        {
                            hr = E_UNEXPECTED;
                        }
                    }
                    else if (flags == DISPATCH_PROPERTYPUT)
                    {
                        hr = S_OK;
                        try
                        {
                            m_innerObject.StartPosition = Converter<VARIANT, uint32_t>(m_dispatchAdapter).Convert(*(dispParams->rgvarg));
                        }
                        catch (winrt::hresult_error)
                        {
                            hr = winrt::to_hresult();
                        }
                        catch (...)
                        {
                            hr = E_UNEXPECTED;
                        }
                    }
                    break;
                case 2:
                    // Invoke for Length
                    if (flags == DISPATCH_PROPERTYGET)
                    {
                        hr = S_OK;
                        try
                        {
                            auto resultAsWinRT = m_innerObject.Length;
                            *result = Converter<decltype(resultAsWinRT), VARIANT>(m_dispatchAdapter).Convert(resultAsWinRT);
                        }
                        catch (winrt::hresult_error)
                        {
                            hr = winrt::to_hresult();
                        }
                        catch (...)
                        {
                            hr = E_UNEXPECTED;
                        }
                    }
                    else if (flags == DISPATCH_PROPERTYPUT)
                    {
                        hr = S_OK;
                        try
                        {
                            m_innerObject.Length = Converter<VARIANT, uint32_t>(m_dispatchAdapter).Convert(*(dispParams->rgvarg));
                        }
                        catch (winrt::hresult_error)
                        {
                            hr = winrt::to_hresult();
                        }
                        catch (...)
                        {
                            hr = E_UNEXPECTED;
                        }
                    }
                    break;

                default:
                    hr = DISP_E_MEMBERNOTFOUND;
                    break;
            }
#pragma warning( pop )
        }
    }
    return hr;
}

HRESULT Struct_Windows_Data_Text_TextSegment::GetInnerObject(IUnknown** object)
{
    auto boxed = winrt::box_value(m_innerObject);
    *object = boxed.as<IUnknown>().detach();

    return S_OK;
}

HRESULT Struct_Windows_Data_Text_TextSegment::GetPropertyNames(wchar_t*** namesOut, size_t* namesLengthOut)
{
    *namesLengthOut = ARRAYSIZE(s_Struct_Windows_Data_Text_TextSegment_dispatchProperties);
    *namesOut = const_cast<wchar_t **>(s_dispatchProperties);
    return S_OK;
}

} // namespace wv2winrt_impl

