// WARNING: Please don't edit this file. It was generated by wv2winrt v1.0.0.0
#pragma once

#include "wv2winrt/dispatchbase.h"
#include "wv2winrt/dispatchcollectionhelpers.h"
#include <functional>
#include "wv2winrt/base.h"
#include "winrt/Windows.System.UserProfile.h"

#include "winrt/Windows.Foundation.Collections.h"


namespace wv2winrt_impl
{
struct Namespace_Windows_System_UserProfile : winrt::implements<Namespace_Windows_System_UserProfile, DispatchBase>
{
    public:
        Namespace_Windows_System_UserProfile(const winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter& dispatchAdapter);

        // IDispatch methods
        HRESULT STDMETHODCALLTYPE GetIDsOfNames(REFIID riid,
                                                LPOLESTR* names,
                                                unsigned int namesCount,
                                                LCID localeId,
                                                DISPID* dispId);

        HRESULT STDMETHODCALLTYPE Invoke(DISPID dispId,
                                         REFIID riid,
                                         LCID localeId,
                                         WORD flags,
                                         DISPPARAMS* dispParams,
                                         VARIANT* result,
                                         EXCEPINFO* excepInfo,
                                         UINT* argErr);
        // ICoreWebView2PrivateDispatchContainer methods
        HRESULT STDMETHODCALLTYPE GetPropertyNames(wchar_t***, size_t*);

    private:
        winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter m_dispatchAdapter;
        static DispatchProperties s_dispatchProperties;
        static const DISPID s_dispatchIds[];
};
}

namespace wv2winrt_impl
{
struct Class_Windows_System_UserProfile_AdvertisingManager : winrt::implements<
    Class_Windows_System_UserProfile_AdvertisingManager,
    DispatchBase>
{
    public:
        Class_Windows_System_UserProfile_AdvertisingManager(::IInspectable* innerObject, const winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter& dispatchAdapter);

        // IDispatch methods
        HRESULT STDMETHODCALLTYPE GetIDsOfNames(REFIID riid,
                                                LPOLESTR* names,
                                                unsigned int namesCount,
                                                LCID localeId,
                                                DISPID* dispId) override;
        HRESULT STDMETHODCALLTYPE Invoke(DISPID dispId,
                                         REFIID riid,
                                         LCID localeId,
                                         WORD flags,
                                         DISPPARAMS* dispParams,
                                         VARIANT* result,
                                         EXCEPINFO* excepInfo,
                                         UINT* argErr) override;

        // ICoreWebView2PrivateDispatchContainer methods
        HRESULT STDMETHODCALLTYPE GetInnerObject(IUnknown** object) override;
        HRESULT STDMETHODCALLTYPE GetPropertyNames(wchar_t***, size_t*);
        HRESULT STDMETHODCALLTYPE GetPropertiesPrecacheability(BOOL** boolsOut, size_t* propertiesLengthOut);

    private:
        winrt::com_ptr<::IInspectable> m_innerObject;
        winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter m_dispatchAdapter;
        static DispatchProperties s_dispatchProperties;
        static const DISPID s_dispatchIds[];
        static const int s_precacheableProperties[];
};
}

namespace wv2winrt_impl
{
struct Class_Windows_System_UserProfile_AdvertisingManagerForUser : winrt::implements<
    Class_Windows_System_UserProfile_AdvertisingManagerForUser,
    DispatchBase>
{
    public:
        Class_Windows_System_UserProfile_AdvertisingManagerForUser(::IInspectable* innerObject, const winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter& dispatchAdapter);

        // IDispatch methods
        HRESULT STDMETHODCALLTYPE GetIDsOfNames(REFIID riid,
                                                LPOLESTR* names,
                                                unsigned int namesCount,
                                                LCID localeId,
                                                DISPID* dispId) override;
        HRESULT STDMETHODCALLTYPE Invoke(DISPID dispId,
                                         REFIID riid,
                                         LCID localeId,
                                         WORD flags,
                                         DISPPARAMS* dispParams,
                                         VARIANT* result,
                                         EXCEPINFO* excepInfo,
                                         UINT* argErr) override;

        // ICoreWebView2PrivateDispatchContainer methods
        HRESULT STDMETHODCALLTYPE GetInnerObject(IUnknown** object) override;
        HRESULT STDMETHODCALLTYPE GetPropertyNames(wchar_t***, size_t*);
        HRESULT STDMETHODCALLTYPE GetPropertiesPrecacheability(BOOL** boolsOut, size_t* propertiesLengthOut);

    private:
        winrt::com_ptr<::IInspectable> m_innerObject;
        winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter m_dispatchAdapter;
        static DispatchProperties s_dispatchProperties;
        static const DISPID s_dispatchIds[];
        static const int s_precacheableProperties[];
};
}

namespace wv2winrt_impl
{
struct Class_Windows_System_UserProfile_AssignedAccessSettings : winrt::implements<
    Class_Windows_System_UserProfile_AssignedAccessSettings,
    DispatchBase>
{
    public:
        Class_Windows_System_UserProfile_AssignedAccessSettings(::IInspectable* innerObject, const winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter& dispatchAdapter);

        // IDispatch methods
        HRESULT STDMETHODCALLTYPE GetIDsOfNames(REFIID riid,
                                                LPOLESTR* names,
                                                unsigned int namesCount,
                                                LCID localeId,
                                                DISPID* dispId) override;
        HRESULT STDMETHODCALLTYPE Invoke(DISPID dispId,
                                         REFIID riid,
                                         LCID localeId,
                                         WORD flags,
                                         DISPPARAMS* dispParams,
                                         VARIANT* result,
                                         EXCEPINFO* excepInfo,
                                         UINT* argErr) override;

        // ICoreWebView2PrivateDispatchContainer methods
        HRESULT STDMETHODCALLTYPE GetInnerObject(IUnknown** object) override;
        HRESULT STDMETHODCALLTYPE GetPropertyNames(wchar_t***, size_t*);
        HRESULT STDMETHODCALLTYPE GetPropertiesPrecacheability(BOOL** boolsOut, size_t* propertiesLengthOut);

    private:
        winrt::com_ptr<::IInspectable> m_innerObject;
        winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter m_dispatchAdapter;
        static DispatchProperties s_dispatchProperties;
        static const DISPID s_dispatchIds[];
        static const int s_precacheableProperties[];
};
}

namespace wv2winrt_impl
{
struct Class_Windows_System_UserProfile_DiagnosticsSettings : winrt::implements<
    Class_Windows_System_UserProfile_DiagnosticsSettings,
    DispatchBase>
{
    public:
        Class_Windows_System_UserProfile_DiagnosticsSettings(::IInspectable* innerObject, const winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter& dispatchAdapter);

        // IDispatch methods
        HRESULT STDMETHODCALLTYPE GetIDsOfNames(REFIID riid,
                                                LPOLESTR* names,
                                                unsigned int namesCount,
                                                LCID localeId,
                                                DISPID* dispId) override;
        HRESULT STDMETHODCALLTYPE Invoke(DISPID dispId,
                                         REFIID riid,
                                         LCID localeId,
                                         WORD flags,
                                         DISPPARAMS* dispParams,
                                         VARIANT* result,
                                         EXCEPINFO* excepInfo,
                                         UINT* argErr) override;

        // ICoreWebView2PrivateDispatchContainer methods
        HRESULT STDMETHODCALLTYPE GetInnerObject(IUnknown** object) override;
        HRESULT STDMETHODCALLTYPE GetPropertyNames(wchar_t***, size_t*);
        HRESULT STDMETHODCALLTYPE GetPropertiesPrecacheability(BOOL** boolsOut, size_t* propertiesLengthOut);

    private:
        winrt::com_ptr<::IInspectable> m_innerObject;
        winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter m_dispatchAdapter;
        static DispatchProperties s_dispatchProperties;
        static const DISPID s_dispatchIds[];
        static const int s_precacheableProperties[];
};
}

namespace wv2winrt_impl
{
struct Class_Windows_System_UserProfile_FirstSignInSettings : winrt::implements<
    Class_Windows_System_UserProfile_FirstSignInSettings,
    DispatchBase>
{
    public:
        Class_Windows_System_UserProfile_FirstSignInSettings(::IInspectable* innerObject, const winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter& dispatchAdapter);

        // IDispatch methods
        HRESULT STDMETHODCALLTYPE GetIDsOfNames(REFIID riid,
                                                LPOLESTR* names,
                                                unsigned int namesCount,
                                                LCID localeId,
                                                DISPID* dispId) override;
        HRESULT STDMETHODCALLTYPE Invoke(DISPID dispId,
                                         REFIID riid,
                                         LCID localeId,
                                         WORD flags,
                                         DISPPARAMS* dispParams,
                                         VARIANT* result,
                                         EXCEPINFO* excepInfo,
                                         UINT* argErr) override;

        // ICoreWebView2PrivateDispatchContainer methods
        HRESULT STDMETHODCALLTYPE GetInnerObject(IUnknown** object) override;
        HRESULT STDMETHODCALLTYPE GetScriptBehavior(DWORD* behavior)
        {
            *behavior = DispatchContainerScriptBehaviorMap;
            return S_OK;
        }
        HRESULT STDMETHODCALLTYPE GetPropertyNames(wchar_t***, size_t*);
        HRESULT STDMETHODCALLTYPE GetPropertiesPrecacheability(BOOL** boolsOut, size_t* propertiesLengthOut);

    private:
        winrt::com_ptr<::IInspectable> m_innerObject;
        winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter m_dispatchAdapter;
        static DispatchProperties s_dispatchProperties;
        static const DISPID s_dispatchIds[];
        static const int s_precacheableProperties[];
        DispatchMapHelper<winrt::Windows::Foundation::Collections::IMapView<
                winrt::hstring, winrt::Windows::Foundation::IInspectable>,

            false, winrt::Windows::Foundation::IInspectable> m_dispatchCollectionHelper;
};
}

namespace wv2winrt_impl
{
struct Class_Windows_System_UserProfile_GlobalizationPreferences : winrt::implements<
    Class_Windows_System_UserProfile_GlobalizationPreferences,
    DispatchBase>
{
    public:
        Class_Windows_System_UserProfile_GlobalizationPreferences(::IInspectable* innerObject, const winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter& dispatchAdapter);

        // IDispatch methods
        HRESULT STDMETHODCALLTYPE GetIDsOfNames(REFIID riid,
                                                LPOLESTR* names,
                                                unsigned int namesCount,
                                                LCID localeId,
                                                DISPID* dispId) override;
        HRESULT STDMETHODCALLTYPE Invoke(DISPID dispId,
                                         REFIID riid,
                                         LCID localeId,
                                         WORD flags,
                                         DISPPARAMS* dispParams,
                                         VARIANT* result,
                                         EXCEPINFO* excepInfo,
                                         UINT* argErr) override;

        // ICoreWebView2PrivateDispatchContainer methods
        HRESULT STDMETHODCALLTYPE GetInnerObject(IUnknown** object) override;
        HRESULT STDMETHODCALLTYPE GetPropertyNames(wchar_t***, size_t*);
        HRESULT STDMETHODCALLTYPE GetPropertiesPrecacheability(BOOL** boolsOut, size_t* propertiesLengthOut);

    private:
        winrt::com_ptr<::IInspectable> m_innerObject;
        winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter m_dispatchAdapter;
        static DispatchProperties s_dispatchProperties;
        static const DISPID s_dispatchIds[];
        static const int s_precacheableProperties[];
};
}

namespace wv2winrt_impl
{
struct Class_Windows_System_UserProfile_GlobalizationPreferencesForUser : winrt::implements<
    Class_Windows_System_UserProfile_GlobalizationPreferencesForUser,
    DispatchBase>
{
    public:
        Class_Windows_System_UserProfile_GlobalizationPreferencesForUser(::IInspectable* innerObject, const winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter& dispatchAdapter);

        // IDispatch methods
        HRESULT STDMETHODCALLTYPE GetIDsOfNames(REFIID riid,
                                                LPOLESTR* names,
                                                unsigned int namesCount,
                                                LCID localeId,
                                                DISPID* dispId) override;
        HRESULT STDMETHODCALLTYPE Invoke(DISPID dispId,
                                         REFIID riid,
                                         LCID localeId,
                                         WORD flags,
                                         DISPPARAMS* dispParams,
                                         VARIANT* result,
                                         EXCEPINFO* excepInfo,
                                         UINT* argErr) override;

        // ICoreWebView2PrivateDispatchContainer methods
        HRESULT STDMETHODCALLTYPE GetInnerObject(IUnknown** object) override;
        HRESULT STDMETHODCALLTYPE GetPropertyNames(wchar_t***, size_t*);
        HRESULT STDMETHODCALLTYPE GetPropertiesPrecacheability(BOOL** boolsOut, size_t* propertiesLengthOut);

    private:
        winrt::com_ptr<::IInspectable> m_innerObject;
        winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter m_dispatchAdapter;
        static DispatchProperties s_dispatchProperties;
        static const DISPID s_dispatchIds[];
        static const int s_precacheableProperties[];
};
}

namespace wv2winrt_impl
{
struct Class_Windows_System_UserProfile_UserProfilePersonalizationSettings : winrt::implements<
    Class_Windows_System_UserProfile_UserProfilePersonalizationSettings,
    DispatchBase>
{
    public:
        Class_Windows_System_UserProfile_UserProfilePersonalizationSettings(::IInspectable* innerObject, const winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter& dispatchAdapter);

        // IDispatch methods
        HRESULT STDMETHODCALLTYPE GetIDsOfNames(REFIID riid,
                                                LPOLESTR* names,
                                                unsigned int namesCount,
                                                LCID localeId,
                                                DISPID* dispId) override;
        HRESULT STDMETHODCALLTYPE Invoke(DISPID dispId,
                                         REFIID riid,
                                         LCID localeId,
                                         WORD flags,
                                         DISPPARAMS* dispParams,
                                         VARIANT* result,
                                         EXCEPINFO* excepInfo,
                                         UINT* argErr) override;

        // ICoreWebView2PrivateDispatchContainer methods
        HRESULT STDMETHODCALLTYPE GetInnerObject(IUnknown** object) override;
        HRESULT STDMETHODCALLTYPE GetPropertyNames(wchar_t***, size_t*);
        HRESULT STDMETHODCALLTYPE GetPropertiesPrecacheability(BOOL** boolsOut, size_t* propertiesLengthOut);

    private:
        winrt::com_ptr<::IInspectable> m_innerObject;
        winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter m_dispatchAdapter;
        static DispatchProperties s_dispatchProperties;
        static const DISPID s_dispatchIds[];
        static const int s_precacheableProperties[];
};
}

namespace wv2winrt_impl
{
struct Class_Windows_System_UserProfile_IAdvertisingManagerForUser : winrt::implements<
    Class_Windows_System_UserProfile_IAdvertisingManagerForUser,
    DispatchBase>
{
    public:
        Class_Windows_System_UserProfile_IAdvertisingManagerForUser(::IInspectable* innerObject, const winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter& dispatchAdapter);

        // IDispatch methods
        HRESULT STDMETHODCALLTYPE GetIDsOfNames(REFIID riid,
                                                LPOLESTR* names,
                                                unsigned int namesCount,
                                                LCID localeId,
                                                DISPID* dispId) override;
        HRESULT STDMETHODCALLTYPE Invoke(DISPID dispId,
                                         REFIID riid,
                                         LCID localeId,
                                         WORD flags,
                                         DISPPARAMS* dispParams,
                                         VARIANT* result,
                                         EXCEPINFO* excepInfo,
                                         UINT* argErr) override;

        // ICoreWebView2PrivateDispatchContainer methods
        HRESULT STDMETHODCALLTYPE GetInnerObject(IUnknown** object) override;
        HRESULT STDMETHODCALLTYPE GetPropertyNames(wchar_t***, size_t*);
        HRESULT STDMETHODCALLTYPE GetPropertiesPrecacheability(BOOL** boolsOut, size_t* propertiesLengthOut);

    private:
        winrt::com_ptr<::IInspectable> m_innerObject;
        winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter m_dispatchAdapter;
        static DispatchProperties s_dispatchProperties;
        static const DISPID s_dispatchIds[];
        static const int s_precacheableProperties[];
};
}

namespace wv2winrt_impl
{
struct Class_Windows_System_UserProfile_IAdvertisingManagerStatics : winrt::implements<
    Class_Windows_System_UserProfile_IAdvertisingManagerStatics,
    DispatchBase>
{
    public:
        Class_Windows_System_UserProfile_IAdvertisingManagerStatics(::IInspectable* innerObject, const winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter& dispatchAdapter);

        // IDispatch methods
        HRESULT STDMETHODCALLTYPE GetIDsOfNames(REFIID riid,
                                                LPOLESTR* names,
                                                unsigned int namesCount,
                                                LCID localeId,
                                                DISPID* dispId) override;
        HRESULT STDMETHODCALLTYPE Invoke(DISPID dispId,
                                         REFIID riid,
                                         LCID localeId,
                                         WORD flags,
                                         DISPPARAMS* dispParams,
                                         VARIANT* result,
                                         EXCEPINFO* excepInfo,
                                         UINT* argErr) override;

        // ICoreWebView2PrivateDispatchContainer methods
        HRESULT STDMETHODCALLTYPE GetInnerObject(IUnknown** object) override;
        HRESULT STDMETHODCALLTYPE GetPropertyNames(wchar_t***, size_t*);
        HRESULT STDMETHODCALLTYPE GetPropertiesPrecacheability(BOOL** boolsOut, size_t* propertiesLengthOut);

    private:
        winrt::com_ptr<::IInspectable> m_innerObject;
        winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter m_dispatchAdapter;
        static DispatchProperties s_dispatchProperties;
        static const DISPID s_dispatchIds[];
        static const int s_precacheableProperties[];
};
}

namespace wv2winrt_impl
{
struct Class_Windows_System_UserProfile_IAdvertisingManagerStatics2 : winrt::implements<
    Class_Windows_System_UserProfile_IAdvertisingManagerStatics2,
    DispatchBase>
{
    public:
        Class_Windows_System_UserProfile_IAdvertisingManagerStatics2(::IInspectable* innerObject, const winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter& dispatchAdapter);

        // IDispatch methods
        HRESULT STDMETHODCALLTYPE GetIDsOfNames(REFIID riid,
                                                LPOLESTR* names,
                                                unsigned int namesCount,
                                                LCID localeId,
                                                DISPID* dispId) override;
        HRESULT STDMETHODCALLTYPE Invoke(DISPID dispId,
                                         REFIID riid,
                                         LCID localeId,
                                         WORD flags,
                                         DISPPARAMS* dispParams,
                                         VARIANT* result,
                                         EXCEPINFO* excepInfo,
                                         UINT* argErr) override;

        // ICoreWebView2PrivateDispatchContainer methods
        HRESULT STDMETHODCALLTYPE GetInnerObject(IUnknown** object) override;
        HRESULT STDMETHODCALLTYPE GetPropertyNames(wchar_t***, size_t*);
        HRESULT STDMETHODCALLTYPE GetPropertiesPrecacheability(BOOL** boolsOut, size_t* propertiesLengthOut);

    private:
        winrt::com_ptr<::IInspectable> m_innerObject;
        winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter m_dispatchAdapter;
        static DispatchProperties s_dispatchProperties;
        static const DISPID s_dispatchIds[];
        static const int s_precacheableProperties[];
};
}

namespace wv2winrt_impl
{
struct Class_Windows_System_UserProfile_IAssignedAccessSettings : winrt::implements<
    Class_Windows_System_UserProfile_IAssignedAccessSettings,
    DispatchBase>
{
    public:
        Class_Windows_System_UserProfile_IAssignedAccessSettings(::IInspectable* innerObject, const winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter& dispatchAdapter);

        // IDispatch methods
        HRESULT STDMETHODCALLTYPE GetIDsOfNames(REFIID riid,
                                                LPOLESTR* names,
                                                unsigned int namesCount,
                                                LCID localeId,
                                                DISPID* dispId) override;
        HRESULT STDMETHODCALLTYPE Invoke(DISPID dispId,
                                         REFIID riid,
                                         LCID localeId,
                                         WORD flags,
                                         DISPPARAMS* dispParams,
                                         VARIANT* result,
                                         EXCEPINFO* excepInfo,
                                         UINT* argErr) override;

        // ICoreWebView2PrivateDispatchContainer methods
        HRESULT STDMETHODCALLTYPE GetInnerObject(IUnknown** object) override;
        HRESULT STDMETHODCALLTYPE GetPropertyNames(wchar_t***, size_t*);
        HRESULT STDMETHODCALLTYPE GetPropertiesPrecacheability(BOOL** boolsOut, size_t* propertiesLengthOut);

    private:
        winrt::com_ptr<::IInspectable> m_innerObject;
        winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter m_dispatchAdapter;
        static DispatchProperties s_dispatchProperties;
        static const DISPID s_dispatchIds[];
        static const int s_precacheableProperties[];
};
}

namespace wv2winrt_impl
{
struct Class_Windows_System_UserProfile_IAssignedAccessSettingsStatics : winrt::implements<
    Class_Windows_System_UserProfile_IAssignedAccessSettingsStatics,
    DispatchBase>
{
    public:
        Class_Windows_System_UserProfile_IAssignedAccessSettingsStatics(::IInspectable* innerObject, const winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter& dispatchAdapter);

        // IDispatch methods
        HRESULT STDMETHODCALLTYPE GetIDsOfNames(REFIID riid,
                                                LPOLESTR* names,
                                                unsigned int namesCount,
                                                LCID localeId,
                                                DISPID* dispId) override;
        HRESULT STDMETHODCALLTYPE Invoke(DISPID dispId,
                                         REFIID riid,
                                         LCID localeId,
                                         WORD flags,
                                         DISPPARAMS* dispParams,
                                         VARIANT* result,
                                         EXCEPINFO* excepInfo,
                                         UINT* argErr) override;

        // ICoreWebView2PrivateDispatchContainer methods
        HRESULT STDMETHODCALLTYPE GetInnerObject(IUnknown** object) override;
        HRESULT STDMETHODCALLTYPE GetPropertyNames(wchar_t***, size_t*);
        HRESULT STDMETHODCALLTYPE GetPropertiesPrecacheability(BOOL** boolsOut, size_t* propertiesLengthOut);

    private:
        winrt::com_ptr<::IInspectable> m_innerObject;
        winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter m_dispatchAdapter;
        static DispatchProperties s_dispatchProperties;
        static const DISPID s_dispatchIds[];
        static const int s_precacheableProperties[];
};
}

namespace wv2winrt_impl
{
struct Class_Windows_System_UserProfile_IDiagnosticsSettings : winrt::implements<
    Class_Windows_System_UserProfile_IDiagnosticsSettings,
    DispatchBase>
{
    public:
        Class_Windows_System_UserProfile_IDiagnosticsSettings(::IInspectable* innerObject, const winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter& dispatchAdapter);

        // IDispatch methods
        HRESULT STDMETHODCALLTYPE GetIDsOfNames(REFIID riid,
                                                LPOLESTR* names,
                                                unsigned int namesCount,
                                                LCID localeId,
                                                DISPID* dispId) override;
        HRESULT STDMETHODCALLTYPE Invoke(DISPID dispId,
                                         REFIID riid,
                                         LCID localeId,
                                         WORD flags,
                                         DISPPARAMS* dispParams,
                                         VARIANT* result,
                                         EXCEPINFO* excepInfo,
                                         UINT* argErr) override;

        // ICoreWebView2PrivateDispatchContainer methods
        HRESULT STDMETHODCALLTYPE GetInnerObject(IUnknown** object) override;
        HRESULT STDMETHODCALLTYPE GetPropertyNames(wchar_t***, size_t*);
        HRESULT STDMETHODCALLTYPE GetPropertiesPrecacheability(BOOL** boolsOut, size_t* propertiesLengthOut);

    private:
        winrt::com_ptr<::IInspectable> m_innerObject;
        winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter m_dispatchAdapter;
        static DispatchProperties s_dispatchProperties;
        static const DISPID s_dispatchIds[];
        static const int s_precacheableProperties[];
};
}

namespace wv2winrt_impl
{
struct Class_Windows_System_UserProfile_IDiagnosticsSettingsStatics : winrt::implements<
    Class_Windows_System_UserProfile_IDiagnosticsSettingsStatics,
    DispatchBase>
{
    public:
        Class_Windows_System_UserProfile_IDiagnosticsSettingsStatics(::IInspectable* innerObject, const winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter& dispatchAdapter);

        // IDispatch methods
        HRESULT STDMETHODCALLTYPE GetIDsOfNames(REFIID riid,
                                                LPOLESTR* names,
                                                unsigned int namesCount,
                                                LCID localeId,
                                                DISPID* dispId) override;
        HRESULT STDMETHODCALLTYPE Invoke(DISPID dispId,
                                         REFIID riid,
                                         LCID localeId,
                                         WORD flags,
                                         DISPPARAMS* dispParams,
                                         VARIANT* result,
                                         EXCEPINFO* excepInfo,
                                         UINT* argErr) override;

        // ICoreWebView2PrivateDispatchContainer methods
        HRESULT STDMETHODCALLTYPE GetInnerObject(IUnknown** object) override;
        HRESULT STDMETHODCALLTYPE GetPropertyNames(wchar_t***, size_t*);
        HRESULT STDMETHODCALLTYPE GetPropertiesPrecacheability(BOOL** boolsOut, size_t* propertiesLengthOut);

    private:
        winrt::com_ptr<::IInspectable> m_innerObject;
        winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter m_dispatchAdapter;
        static DispatchProperties s_dispatchProperties;
        static const DISPID s_dispatchIds[];
        static const int s_precacheableProperties[];
};
}

namespace wv2winrt_impl
{
struct Class_Windows_System_UserProfile_IFirstSignInSettings : winrt::implements<
    Class_Windows_System_UserProfile_IFirstSignInSettings,
    DispatchBase>
{
    public:
        Class_Windows_System_UserProfile_IFirstSignInSettings(::IInspectable* innerObject, const winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter& dispatchAdapter);

        // IDispatch methods
        HRESULT STDMETHODCALLTYPE GetIDsOfNames(REFIID riid,
                                                LPOLESTR* names,
                                                unsigned int namesCount,
                                                LCID localeId,
                                                DISPID* dispId) override;
        HRESULT STDMETHODCALLTYPE Invoke(DISPID dispId,
                                         REFIID riid,
                                         LCID localeId,
                                         WORD flags,
                                         DISPPARAMS* dispParams,
                                         VARIANT* result,
                                         EXCEPINFO* excepInfo,
                                         UINT* argErr) override;

        // ICoreWebView2PrivateDispatchContainer methods
        HRESULT STDMETHODCALLTYPE GetInnerObject(IUnknown** object) override;
        HRESULT STDMETHODCALLTYPE GetScriptBehavior(DWORD* behavior)
        {
            *behavior = DispatchContainerScriptBehaviorMap;
            return S_OK;
        }
        HRESULT STDMETHODCALLTYPE GetPropertyNames(wchar_t***, size_t*);
        HRESULT STDMETHODCALLTYPE GetPropertiesPrecacheability(BOOL** boolsOut, size_t* propertiesLengthOut);

    private:
        winrt::com_ptr<::IInspectable> m_innerObject;
        winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter m_dispatchAdapter;
        static DispatchProperties s_dispatchProperties;
        static const DISPID s_dispatchIds[];
        static const int s_precacheableProperties[];
        DispatchMapHelper<winrt::Windows::Foundation::Collections::IMapView<
                winrt::hstring, winrt::Windows::Foundation::IInspectable>,

            false, winrt::Windows::Foundation::IInspectable> m_dispatchCollectionHelper;
};
}

namespace wv2winrt_impl
{
struct Class_Windows_System_UserProfile_IFirstSignInSettingsStatics : winrt::implements<
    Class_Windows_System_UserProfile_IFirstSignInSettingsStatics,
    DispatchBase>
{
    public:
        Class_Windows_System_UserProfile_IFirstSignInSettingsStatics(::IInspectable* innerObject, const winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter& dispatchAdapter);

        // IDispatch methods
        HRESULT STDMETHODCALLTYPE GetIDsOfNames(REFIID riid,
                                                LPOLESTR* names,
                                                unsigned int namesCount,
                                                LCID localeId,
                                                DISPID* dispId) override;
        HRESULT STDMETHODCALLTYPE Invoke(DISPID dispId,
                                         REFIID riid,
                                         LCID localeId,
                                         WORD flags,
                                         DISPPARAMS* dispParams,
                                         VARIANT* result,
                                         EXCEPINFO* excepInfo,
                                         UINT* argErr) override;

        // ICoreWebView2PrivateDispatchContainer methods
        HRESULT STDMETHODCALLTYPE GetInnerObject(IUnknown** object) override;
        HRESULT STDMETHODCALLTYPE GetPropertyNames(wchar_t***, size_t*);
        HRESULT STDMETHODCALLTYPE GetPropertiesPrecacheability(BOOL** boolsOut, size_t* propertiesLengthOut);

    private:
        winrt::com_ptr<::IInspectable> m_innerObject;
        winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter m_dispatchAdapter;
        static DispatchProperties s_dispatchProperties;
        static const DISPID s_dispatchIds[];
        static const int s_precacheableProperties[];
};
}

namespace wv2winrt_impl
{
struct Class_Windows_System_UserProfile_IGlobalizationPreferencesForUser : winrt::implements<
    Class_Windows_System_UserProfile_IGlobalizationPreferencesForUser,
    DispatchBase>
{
    public:
        Class_Windows_System_UserProfile_IGlobalizationPreferencesForUser(::IInspectable* innerObject, const winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter& dispatchAdapter);

        // IDispatch methods
        HRESULT STDMETHODCALLTYPE GetIDsOfNames(REFIID riid,
                                                LPOLESTR* names,
                                                unsigned int namesCount,
                                                LCID localeId,
                                                DISPID* dispId) override;
        HRESULT STDMETHODCALLTYPE Invoke(DISPID dispId,
                                         REFIID riid,
                                         LCID localeId,
                                         WORD flags,
                                         DISPPARAMS* dispParams,
                                         VARIANT* result,
                                         EXCEPINFO* excepInfo,
                                         UINT* argErr) override;

        // ICoreWebView2PrivateDispatchContainer methods
        HRESULT STDMETHODCALLTYPE GetInnerObject(IUnknown** object) override;
        HRESULT STDMETHODCALLTYPE GetPropertyNames(wchar_t***, size_t*);
        HRESULT STDMETHODCALLTYPE GetPropertiesPrecacheability(BOOL** boolsOut, size_t* propertiesLengthOut);

    private:
        winrt::com_ptr<::IInspectable> m_innerObject;
        winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter m_dispatchAdapter;
        static DispatchProperties s_dispatchProperties;
        static const DISPID s_dispatchIds[];
        static const int s_precacheableProperties[];
};
}

namespace wv2winrt_impl
{
struct Class_Windows_System_UserProfile_IGlobalizationPreferencesStatics : winrt::implements<
    Class_Windows_System_UserProfile_IGlobalizationPreferencesStatics,
    DispatchBase>
{
    public:
        Class_Windows_System_UserProfile_IGlobalizationPreferencesStatics(::IInspectable* innerObject, const winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter& dispatchAdapter);

        // IDispatch methods
        HRESULT STDMETHODCALLTYPE GetIDsOfNames(REFIID riid,
                                                LPOLESTR* names,
                                                unsigned int namesCount,
                                                LCID localeId,
                                                DISPID* dispId) override;
        HRESULT STDMETHODCALLTYPE Invoke(DISPID dispId,
                                         REFIID riid,
                                         LCID localeId,
                                         WORD flags,
                                         DISPPARAMS* dispParams,
                                         VARIANT* result,
                                         EXCEPINFO* excepInfo,
                                         UINT* argErr) override;

        // ICoreWebView2PrivateDispatchContainer methods
        HRESULT STDMETHODCALLTYPE GetInnerObject(IUnknown** object) override;
        HRESULT STDMETHODCALLTYPE GetPropertyNames(wchar_t***, size_t*);
        HRESULT STDMETHODCALLTYPE GetPropertiesPrecacheability(BOOL** boolsOut, size_t* propertiesLengthOut);

    private:
        winrt::com_ptr<::IInspectable> m_innerObject;
        winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter m_dispatchAdapter;
        static DispatchProperties s_dispatchProperties;
        static const DISPID s_dispatchIds[];
        static const int s_precacheableProperties[];
};
}

namespace wv2winrt_impl
{
struct Class_Windows_System_UserProfile_IGlobalizationPreferencesStatics2 : winrt::implements<
    Class_Windows_System_UserProfile_IGlobalizationPreferencesStatics2,
    DispatchBase>
{
    public:
        Class_Windows_System_UserProfile_IGlobalizationPreferencesStatics2(::IInspectable* innerObject, const winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter& dispatchAdapter);

        // IDispatch methods
        HRESULT STDMETHODCALLTYPE GetIDsOfNames(REFIID riid,
                                                LPOLESTR* names,
                                                unsigned int namesCount,
                                                LCID localeId,
                                                DISPID* dispId) override;
        HRESULT STDMETHODCALLTYPE Invoke(DISPID dispId,
                                         REFIID riid,
                                         LCID localeId,
                                         WORD flags,
                                         DISPPARAMS* dispParams,
                                         VARIANT* result,
                                         EXCEPINFO* excepInfo,
                                         UINT* argErr) override;

        // ICoreWebView2PrivateDispatchContainer methods
        HRESULT STDMETHODCALLTYPE GetInnerObject(IUnknown** object) override;
        HRESULT STDMETHODCALLTYPE GetPropertyNames(wchar_t***, size_t*);
        HRESULT STDMETHODCALLTYPE GetPropertiesPrecacheability(BOOL** boolsOut, size_t* propertiesLengthOut);

    private:
        winrt::com_ptr<::IInspectable> m_innerObject;
        winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter m_dispatchAdapter;
        static DispatchProperties s_dispatchProperties;
        static const DISPID s_dispatchIds[];
        static const int s_precacheableProperties[];
};
}

namespace wv2winrt_impl
{
struct Class_Windows_System_UserProfile_IGlobalizationPreferencesStatics3 : winrt::implements<
    Class_Windows_System_UserProfile_IGlobalizationPreferencesStatics3,
    DispatchBase>
{
    public:
        Class_Windows_System_UserProfile_IGlobalizationPreferencesStatics3(::IInspectable* innerObject, const winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter& dispatchAdapter);

        // IDispatch methods
        HRESULT STDMETHODCALLTYPE GetIDsOfNames(REFIID riid,
                                                LPOLESTR* names,
                                                unsigned int namesCount,
                                                LCID localeId,
                                                DISPID* dispId) override;
        HRESULT STDMETHODCALLTYPE Invoke(DISPID dispId,
                                         REFIID riid,
                                         LCID localeId,
                                         WORD flags,
                                         DISPPARAMS* dispParams,
                                         VARIANT* result,
                                         EXCEPINFO* excepInfo,
                                         UINT* argErr) override;

        // ICoreWebView2PrivateDispatchContainer methods
        HRESULT STDMETHODCALLTYPE GetInnerObject(IUnknown** object) override;
        HRESULT STDMETHODCALLTYPE GetPropertyNames(wchar_t***, size_t*);
        HRESULT STDMETHODCALLTYPE GetPropertiesPrecacheability(BOOL** boolsOut, size_t* propertiesLengthOut);

    private:
        winrt::com_ptr<::IInspectable> m_innerObject;
        winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter m_dispatchAdapter;
        static DispatchProperties s_dispatchProperties;
        static const DISPID s_dispatchIds[];
        static const int s_precacheableProperties[];
};
}

namespace wv2winrt_impl
{
struct Class_Windows_System_UserProfile_IUserProfilePersonalizationSettings : winrt::implements<
    Class_Windows_System_UserProfile_IUserProfilePersonalizationSettings,
    DispatchBase>
{
    public:
        Class_Windows_System_UserProfile_IUserProfilePersonalizationSettings(::IInspectable* innerObject, const winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter& dispatchAdapter);

        // IDispatch methods
        HRESULT STDMETHODCALLTYPE GetIDsOfNames(REFIID riid,
                                                LPOLESTR* names,
                                                unsigned int namesCount,
                                                LCID localeId,
                                                DISPID* dispId) override;
        HRESULT STDMETHODCALLTYPE Invoke(DISPID dispId,
                                         REFIID riid,
                                         LCID localeId,
                                         WORD flags,
                                         DISPPARAMS* dispParams,
                                         VARIANT* result,
                                         EXCEPINFO* excepInfo,
                                         UINT* argErr) override;

        // ICoreWebView2PrivateDispatchContainer methods
        HRESULT STDMETHODCALLTYPE GetInnerObject(IUnknown** object) override;
        HRESULT STDMETHODCALLTYPE GetPropertyNames(wchar_t***, size_t*);
        HRESULT STDMETHODCALLTYPE GetPropertiesPrecacheability(BOOL** boolsOut, size_t* propertiesLengthOut);

    private:
        winrt::com_ptr<::IInspectable> m_innerObject;
        winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter m_dispatchAdapter;
        static DispatchProperties s_dispatchProperties;
        static const DISPID s_dispatchIds[];
        static const int s_precacheableProperties[];
};
}

namespace wv2winrt_impl
{
struct Class_Windows_System_UserProfile_IUserProfilePersonalizationSettingsStatics : winrt::implements<
    Class_Windows_System_UserProfile_IUserProfilePersonalizationSettingsStatics,
    DispatchBase>
{
    public:
        Class_Windows_System_UserProfile_IUserProfilePersonalizationSettingsStatics(::IInspectable* innerObject, const winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter& dispatchAdapter);

        // IDispatch methods
        HRESULT STDMETHODCALLTYPE GetIDsOfNames(REFIID riid,
                                                LPOLESTR* names,
                                                unsigned int namesCount,
                                                LCID localeId,
                                                DISPID* dispId) override;
        HRESULT STDMETHODCALLTYPE Invoke(DISPID dispId,
                                         REFIID riid,
                                         LCID localeId,
                                         WORD flags,
                                         DISPPARAMS* dispParams,
                                         VARIANT* result,
                                         EXCEPINFO* excepInfo,
                                         UINT* argErr) override;

        // ICoreWebView2PrivateDispatchContainer methods
        HRESULT STDMETHODCALLTYPE GetInnerObject(IUnknown** object) override;
        HRESULT STDMETHODCALLTYPE GetPropertyNames(wchar_t***, size_t*);
        HRESULT STDMETHODCALLTYPE GetPropertiesPrecacheability(BOOL** boolsOut, size_t* propertiesLengthOut);

    private:
        winrt::com_ptr<::IInspectable> m_innerObject;
        winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter m_dispatchAdapter;
        static DispatchProperties s_dispatchProperties;
        static const DISPID s_dispatchIds[];
        static const int s_precacheableProperties[];
};
}
namespace wv2winrt_impl
{
struct Static_Class_Windows_System_UserProfile_AdvertisingManager : winrt::implements<Static_Class_Windows_System_UserProfile_AdvertisingManager, DispatchBase>
{
    public:
        Static_Class_Windows_System_UserProfile_AdvertisingManager(const winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter& dispatchAdapter);

        HRESULT STDMETHODCALLTYPE GetIDsOfNames(REFIID riid,
                                                LPOLESTR* names,
                                                unsigned int namesCount,
                                                LCID localeId,
                                                DISPID* dispId) override;
        HRESULT STDMETHODCALLTYPE Invoke(DISPID dispId,
                                         REFIID riid,
                                         LCID localeId,
                                         WORD flags,
                                         DISPPARAMS* dispParams,
                                         VARIANT* result,
                                         EXCEPINFO* excepInfo,
                                         UINT* argErr) override;

        // ICoreWebView2PrivateDispatchContainer methods
        HRESULT STDMETHODCALLTYPE GetPropertyNames(wchar_t***, size_t*);

    private:
        winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter m_dispatchAdapter;
        static DispatchProperties s_dispatchProperties;
        static const DISPID s_dispatchIds[];
};
}
namespace wv2winrt_impl
{
struct Static_Class_Windows_System_UserProfile_AssignedAccessSettings : winrt::implements<Static_Class_Windows_System_UserProfile_AssignedAccessSettings, DispatchBase>
{
    public:
        Static_Class_Windows_System_UserProfile_AssignedAccessSettings(const winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter& dispatchAdapter);

        HRESULT STDMETHODCALLTYPE GetIDsOfNames(REFIID riid,
                                                LPOLESTR* names,
                                                unsigned int namesCount,
                                                LCID localeId,
                                                DISPID* dispId) override;
        HRESULT STDMETHODCALLTYPE Invoke(DISPID dispId,
                                         REFIID riid,
                                         LCID localeId,
                                         WORD flags,
                                         DISPPARAMS* dispParams,
                                         VARIANT* result,
                                         EXCEPINFO* excepInfo,
                                         UINT* argErr) override;

        // ICoreWebView2PrivateDispatchContainer methods
        HRESULT STDMETHODCALLTYPE GetPropertyNames(wchar_t***, size_t*);

    private:
        winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter m_dispatchAdapter;
        static DispatchProperties s_dispatchProperties;
        static const DISPID s_dispatchIds[];
};
}
namespace wv2winrt_impl
{
struct Static_Class_Windows_System_UserProfile_DiagnosticsSettings : winrt::implements<Static_Class_Windows_System_UserProfile_DiagnosticsSettings, DispatchBase>
{
    public:
        Static_Class_Windows_System_UserProfile_DiagnosticsSettings(const winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter& dispatchAdapter);

        HRESULT STDMETHODCALLTYPE GetIDsOfNames(REFIID riid,
                                                LPOLESTR* names,
                                                unsigned int namesCount,
                                                LCID localeId,
                                                DISPID* dispId) override;
        HRESULT STDMETHODCALLTYPE Invoke(DISPID dispId,
                                         REFIID riid,
                                         LCID localeId,
                                         WORD flags,
                                         DISPPARAMS* dispParams,
                                         VARIANT* result,
                                         EXCEPINFO* excepInfo,
                                         UINT* argErr) override;

        // ICoreWebView2PrivateDispatchContainer methods
        HRESULT STDMETHODCALLTYPE GetPropertyNames(wchar_t***, size_t*);

    private:
        winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter m_dispatchAdapter;
        static DispatchProperties s_dispatchProperties;
        static const DISPID s_dispatchIds[];
};
}
namespace wv2winrt_impl
{
struct Static_Class_Windows_System_UserProfile_FirstSignInSettings : winrt::implements<Static_Class_Windows_System_UserProfile_FirstSignInSettings, DispatchBase>
{
    public:
        Static_Class_Windows_System_UserProfile_FirstSignInSettings(const winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter& dispatchAdapter);

        HRESULT STDMETHODCALLTYPE GetIDsOfNames(REFIID riid,
                                                LPOLESTR* names,
                                                unsigned int namesCount,
                                                LCID localeId,
                                                DISPID* dispId) override;
        HRESULT STDMETHODCALLTYPE Invoke(DISPID dispId,
                                         REFIID riid,
                                         LCID localeId,
                                         WORD flags,
                                         DISPPARAMS* dispParams,
                                         VARIANT* result,
                                         EXCEPINFO* excepInfo,
                                         UINT* argErr) override;

        // ICoreWebView2PrivateDispatchContainer methods
        HRESULT STDMETHODCALLTYPE GetPropertyNames(wchar_t***, size_t*);

    private:
        winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter m_dispatchAdapter;
        static DispatchProperties s_dispatchProperties;
        static const DISPID s_dispatchIds[];
};
}
namespace wv2winrt_impl
{
struct Static_Class_Windows_System_UserProfile_GlobalizationPreferences : winrt::implements<Static_Class_Windows_System_UserProfile_GlobalizationPreferences, DispatchBase>
{
    public:
        Static_Class_Windows_System_UserProfile_GlobalizationPreferences(const winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter& dispatchAdapter);

        HRESULT STDMETHODCALLTYPE GetIDsOfNames(REFIID riid,
                                                LPOLESTR* names,
                                                unsigned int namesCount,
                                                LCID localeId,
                                                DISPID* dispId) override;
        HRESULT STDMETHODCALLTYPE Invoke(DISPID dispId,
                                         REFIID riid,
                                         LCID localeId,
                                         WORD flags,
                                         DISPPARAMS* dispParams,
                                         VARIANT* result,
                                         EXCEPINFO* excepInfo,
                                         UINT* argErr) override;

        // ICoreWebView2PrivateDispatchContainer methods
        HRESULT STDMETHODCALLTYPE GetPropertyNames(wchar_t***, size_t*);

    private:
        winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter m_dispatchAdapter;
        static DispatchProperties s_dispatchProperties;
        static const DISPID s_dispatchIds[];
};
}
namespace wv2winrt_impl
{
struct Static_Class_Windows_System_UserProfile_UserProfilePersonalizationSettings : winrt::implements<Static_Class_Windows_System_UserProfile_UserProfilePersonalizationSettings, DispatchBase>
{
    public:
        Static_Class_Windows_System_UserProfile_UserProfilePersonalizationSettings(const winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter& dispatchAdapter);

        HRESULT STDMETHODCALLTYPE GetIDsOfNames(REFIID riid,
                                                LPOLESTR* names,
                                                unsigned int namesCount,
                                                LCID localeId,
                                                DISPID* dispId) override;
        HRESULT STDMETHODCALLTYPE Invoke(DISPID dispId,
                                         REFIID riid,
                                         LCID localeId,
                                         WORD flags,
                                         DISPPARAMS* dispParams,
                                         VARIANT* result,
                                         EXCEPINFO* excepInfo,
                                         UINT* argErr) override;

        // ICoreWebView2PrivateDispatchContainer methods
        HRESULT STDMETHODCALLTYPE GetPropertyNames(wchar_t***, size_t*);

    private:
        winrt::Microsoft::Web::WebView2::Core::ICoreWebView2DispatchAdapter m_dispatchAdapter;
        static DispatchProperties s_dispatchProperties;
        static const DISPID s_dispatchIds[];
};
}
