// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.220531.1

#pragma once
#ifndef WINRT_NativeCode_H
#define WINRT_NativeCode_H
#include "winrt/base.h"
static_assert(winrt::check_version(CPPWINRT_VERSION, "2.0.220531.1"), "Mismatched C++/WinRT headers.");
#define CPPWINRT_VERSION "2.0.220531.1"
#include "winrt/impl/NativeCode.2.h"
namespace winrt::impl
{
    template <typename D> auto consume_NativeCode_IPlayWithNumbers<D>::Add(int32_t number1, int32_t number2) const
    {
        int32_t result{};
        check_hresult(WINRT_IMPL_SHIM(winrt::NativeCode::IPlayWithNumbers)->Add(number1, number2, &result));
        return result;
    }
    template <typename D>
    struct produce<D, winrt::NativeCode::IPlayWithNumbers> : produce_base<D, winrt::NativeCode::IPlayWithNumbers>
    {
        int32_t __stdcall Add(int32_t number1, int32_t number2, int32_t* result) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            *result = detach_from<int32_t>(this->shim().Add(number1, number2));
            return 0;
        }
        catch (...) { return to_hresult(); }
    };
}
WINRT_EXPORT namespace winrt::NativeCode
{
}
namespace std
{
#ifndef WINRT_LEAN_AND_MEAN
    template<> struct hash<winrt::NativeCode::IPlayWithNumbers> : winrt::impl::hash_base {};
    template<> struct hash<winrt::NativeCode::PlayWithNumbers> : winrt::impl::hash_base {};
#endif
#ifdef __cpp_lib_format
#endif
}
#endif
