// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.220531.1

#pragma once
#ifndef WINRT_WinRTAdapter_H
#define WINRT_WinRTAdapter_H
#include "winrt/base.h"
static_assert(winrt::check_version(CPPWINRT_VERSION, "2.0.220531.1"), "Mismatched C++/WinRT headers.");
#define CPPWINRT_VERSION "2.0.220531.1"
#include "winrt/impl/Microsoft.Web.WebView2.Core.2.h"
#include "winrt/impl/WinRTAdapter.2.h"
namespace winrt::impl
{
    template <typename D>
    struct produce<D, winrt::WinRTAdapter::IDispatchAdapter> : produce_base<D, winrt::WinRTAdapter::IDispatchAdapter>
    {
    };
}
WINRT_EXPORT namespace winrt::WinRTAdapter
{
}
namespace std
{
#ifndef WINRT_LEAN_AND_MEAN
    template<> struct hash<winrt::WinRTAdapter::IDispatchAdapter> : winrt::impl::hash_base {};
    template<> struct hash<winrt::WinRTAdapter::DispatchAdapter> : winrt::impl::hash_base {};
#endif
#ifdef __cpp_lib_format
#endif
}
#endif
