// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.220531.1

#pragma once
#ifndef WINRT_NativeCode_2_H
#define WINRT_NativeCode_2_H
#include "winrt/impl/NativeCode.1.h"
WINRT_EXPORT namespace winrt::NativeCode
{
    struct __declspec(empty_bases) PlayWithNumbers : winrt::NativeCode::IPlayWithNumbers
    {
        PlayWithNumbers(std::nullptr_t) noexcept {}
        PlayWithNumbers(void* ptr, take_ownership_from_abi_t) noexcept : winrt::NativeCode::IPlayWithNumbers(ptr, take_ownership_from_abi) {}
        PlayWithNumbers();
    };
}
#endif
