// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.220531.1

#pragma once
#ifndef WINRT_NativeCode_0_H
#define WINRT_NativeCode_0_H
WINRT_EXPORT namespace winrt::NativeCode
{
    struct IPlayWithNumbers;
    struct PlayWithNumbers;
}
namespace winrt::impl
{
    template <> struct category<winrt::NativeCode::IPlayWithNumbers>{ using type = interface_category; };
    template <> struct category<winrt::NativeCode::PlayWithNumbers>{ using type = class_category; };
    template <> inline constexpr auto& name_v<winrt::NativeCode::PlayWithNumbers> = L"NativeCode.PlayWithNumbers";
    template <> inline constexpr auto& name_v<winrt::NativeCode::IPlayWithNumbers> = L"NativeCode.IPlayWithNumbers";
    template <> inline constexpr guid guid_v<winrt::NativeCode::IPlayWithNumbers>{ 0x80E5F59F,0x9DAA,0x5A2F,{ 0xA1,0x8F,0xCF,0x0C,0x0B,0xAF,0x52,0x06 } }; // 80E5F59F-9DAA-5A2F-A18F-CF0C0BAF5206
    template <> struct default_interface<winrt::NativeCode::PlayWithNumbers>{ using type = winrt::NativeCode::IPlayWithNumbers; };
    template <> struct abi<winrt::NativeCode::IPlayWithNumbers>
    {
        struct __declspec(novtable) type : inspectable_abi
        {
            virtual int32_t __stdcall Add(int32_t, int32_t, int32_t*) noexcept = 0;
        };
    };
    template <typename D>
    struct consume_NativeCode_IPlayWithNumbers
    {
        auto Add(int32_t number1, int32_t number2) const;
    };
    template <> struct consume<winrt::NativeCode::IPlayWithNumbers>
    {
        template <typename D> using type = consume_NativeCode_IPlayWithNumbers<D>;
    };
}
#endif
