// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.220531.1

#pragma once
#ifndef WINRT_WinRTAdapter_0_H
#define WINRT_WinRTAdapter_0_H
WINRT_EXPORT namespace winrt::WinRTAdapter
{
    struct IDispatchAdapter;
    struct DispatchAdapter;
}
namespace winrt::impl
{
    template <> struct category<winrt::WinRTAdapter::IDispatchAdapter>{ using type = interface_category; };
    template <> struct category<winrt::WinRTAdapter::DispatchAdapter>{ using type = class_category; };
    template <> inline constexpr auto& name_v<winrt::WinRTAdapter::DispatchAdapter> = L"WinRTAdapter.DispatchAdapter";
    template <> inline constexpr auto& name_v<winrt::WinRTAdapter::IDispatchAdapter> = L"WinRTAdapter.IDispatchAdapter";
    template <> inline constexpr guid guid_v<winrt::WinRTAdapter::IDispatchAdapter>{ 0x5EE8E690,0xBC26,0x5176,{ 0x8B,0x97,0xE2,0xB8,0xDD,0x53,0x20,0x4A } }; // 5EE8E690-BC26-5176-8B97-E2B8DD53204A
    template <> struct default_interface<winrt::WinRTAdapter::DispatchAdapter>{ using type = winrt::WinRTAdapter::IDispatchAdapter; };
    template <> struct abi<winrt::WinRTAdapter::IDispatchAdapter>
    {
        struct __declspec(novtable) type : inspectable_abi
        {
        };
    };
    template <typename D>
    struct consume_WinRTAdapter_IDispatchAdapter
    {
    };
    template <> struct consume<winrt::WinRTAdapter::IDispatchAdapter>
    {
        template <typename D> using type = consume_WinRTAdapter_IDispatchAdapter<D>;
    };
}
#endif
