// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.220531.1

#pragma once
#include "winrt/NativeCode.h"
namespace winrt::NativeCode::implementation
{
    template <typename D, typename... I>
    struct __declspec(empty_bases) PlayWithNumbers_base : implements<D, NativeCode::PlayWithNumbers, I...>
    {
        using base_type = PlayWithNumbers_base;
        using class_type = NativeCode::PlayWithNumbers;
        using implements_type = typename PlayWithNumbers_base::implements_type;
        using implements_type::implements_type;
        
        hstring GetRuntimeClassName() const
        {
            return L"NativeCode.PlayWithNumbers";
        }
    };
}
namespace winrt::NativeCode::factory_implementation
{
    template <typename D, typename T, typename... I>
    struct __declspec(empty_bases) PlayWithNumbersT : implements<D, winrt::Windows::Foundation::IActivationFactory, I...>
    {
        using instance_type = NativeCode::PlayWithNumbers;

        hstring GetRuntimeClassName() const
        {
            return L"NativeCode.PlayWithNumbers";
        }
        auto ActivateInstance() const
        {
            return make<T>();
        }
    };
}

#if defined(WINRT_FORCE_INCLUDE_PLAYWITHNUMBERS_XAML_G_H) || __has_include("NativeCode.PlayWithNumbers.xaml.g.h")

#include "NativeCode.PlayWithNumbers.xaml.g.h"

#else

namespace winrt::NativeCode::implementation
{
    template <typename D, typename... I>
    using PlayWithNumbersT = PlayWithNumbers_base<D, I...>;
}

#endif
