name: Автосборка Music M (Unpacked)

on:
  workflow_dispatch:
    inputs:
      namevers:
        description: "Название релиза"
        required: true
        default: "🤖 Автосборка"
      descr:
        description: "Описание релиза"
        required: true
        default: "❌ Описание сборки отсутствует"
      release:
        description: "Выкинуть в релиз?"
        required: true
        default: false
        type: boolean
      prerelease:
        description: "Пререлиз?"
        required: true
        default: true
        type: boolean

  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Unpacked]
        platform: [x64]

    runs-on: windows-latest

    env:
      Project_Name: "VK UI3" # Имя основного проекта

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET 8.x
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore NuGet packages
        run: dotnet restore "$env:Project_Name/$env:Project_Name.csproj"

      - name: Обновить TOKEN_STAT_SLY
        run: |
          $repoName = "${{ github.repository }}".Split('/')[1]
          $content = Get-Content -Path "$env:Project_Name/StaticParams.cs" -ErrorAction SilentlyContinue
          if ($content) {
            $updatedContent = $content -replace 'Environment.GetEnvironmentVariable\("TOKEN_STAT_SLY"\)', '"${{ secrets.TOKEN_STAT_SLY }}"'
            Set-Content -Path "$env:Project_Name/StaticParams.cs" -Value $updatedContent
            Write-Output $updatedContent
          }

      - name: Build Unpacked Application
        run: |
          dotnet build "$env:Project_Name/$env:Project_Name.csproj" `
            -c $env:Configuration `
            -p:Platform=$env:Platform `
            -p:WindowsPackageType=None `
            -p:SelfContained=true `
            -p:WindowsAppSDKSelfContained=true `
            -p:RuntimeIdentifier=win-${{ matrix.platform }}
        env:
          Configuration: ${{ matrix.configuration }}
          Platform: ${{ matrix.platform }}

      - name: Publish Unpacked Application
        run: |
          $outputDir = "${{ github.workspace }}\Output\${{ matrix.platform }}\${{ matrix.configuration }}"
          New-Item -ItemType Directory -Path $outputDir -Force
          dotnet publish "$env:Project_Name/$env:Project_Name.csproj" `
            -c $env:Configuration `
            -r win-${{ matrix.platform }} `
            --self-contained true `
            -p:WindowsPackageType=None `
            -p:WindowsAppSDKSelfContained=true `
            -o $outputDir
        env:
          Configuration: ${{ matrix.configuration }}

      - name: Zip Unpacked Output
        run: |
          $outputDir = "${{ github.workspace }}\Output\${{ matrix.platform }}\${{ matrix.configuration }}"
          $zipPath = "${{ github.workspace }}\Output\VK_UI3_Unpacked_${{ matrix.platform }}.zip"
          Compress-Archive -Path "$outputDir\*" -DestinationPath $zipPath -Force

      - name: Upload Unpacked Artifact
        uses: actions/upload-artifact@v4
        with:
          name: VK_UI3_Unpacked_${{ matrix.platform }}
          path: ${{ github.workspace }}\Output\VK_UI3_Unpacked_${{ matrix.platform }}.zip

      - name: Извлечь версию
        id: get_version
        run: |
          $csprojPath = "$env:Project_Name/$env:Project_Name.csproj"
          [xml]$doc = Get-Content $csprojPath
          $version = $doc.Project.PropertyGroup.AppxPackageVersion
          if (-not $version) {
            $version = $doc.Project.PropertyGroup.Version
          }
          echo "version=$version" >> $GITHUB_OUTPUT
          echo "Версия: $version"
        if: github.event.inputs.release == 'true'

      - name: Проверить существование релиза
        id: check_release
        run: |
          $version = "${{ steps.get_version.outputs.version }}"
          $headers = @{
            "Authorization" = "token ${{ secrets.TOKEN }}"
          }
          $releases = Invoke-RestMethod -Uri "https://api.github.com/repos/${{ github.repository }}/releases" -Headers $headers
          $release = $releases | Where-Object { $_.tag_name -eq $version -and $_.draft -eq $false -and $_.prerelease -eq $false }
          if ($release) {
            Write-Host "Релиз с тегом $version уже существует"
            echo "exists=true" >> $GITHUB_OUTPUT
          } else {
            Write-Host "Релиз с тегом $version не найден"
            echo "exists=false" >> $GITHUB_OUTPUT
          }
        if: github.event.inputs.release == 'true'

      - name: Создать релиз
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          tag_name: ${{ steps.get_version.outputs.version }}
          release_name: ${{ github.event.inputs.namevers }}
          body: ${{ github.event.inputs.descr }}
          draft: false
          prerelease: ${{ github.event.inputs.prerelease }}
        if: steps.check_release.outputs.exists == 'false' && github.event.inputs.release == 'true'

      - name: Загрузить файлы в релиз
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.TOKEN }}
          file: ${{ github.workspace }}\Output\VK_UI3_Unpacked_*.zip
          asset_name: VK_UI3_Unpacked_${{ matrix.platform }}
          tag: ${{ steps.get_version.outputs.version }}
          overwrite: true
          file_glob: true
        if: steps.check_release.outputs.exists == 'false' && github.event.inputs.release == 'true'

      - name: Отправить сообщение в Telegram
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          RELEASE_URL: https://github.com/${{ github.repository }}/releases/tag/${{ steps.get_version.outputs.version }}
        run: |
          $telegramBotToken = '${{ secrets.TELEGRAM_BOT_TOKEN }}'
          $telegramChatId = '${{ secrets.TELEGRAM_CHAT_ID }}'
          $releaseUrl = 'https://github.com/${{ github.repository }}/releases/tag/${{ steps.get_version.outputs.version }}'
          $message = @"
          <b>🎉 Новый релиз:</b> ${{ github.event.inputs.namevers }}
          <b>📦 Версия:</b> ${{ steps.get_version.outputs.version }}
          <b>📝 Описание:</b> ${{ github.event.inputs.descr }}
          <b>🔗 <a href='$releaseUrl'>Ссылка на релиз</a></b>
          "@
          $uri = 'https://api.telegram.org/bot' + $telegramBotToken + '/sendMessage'
          $body = @{
              chat_id = $telegramChatId
              text = $message
              parse_mode = 'HTML'
          }
          $bodyJson = $body | ConvertTo-Json -Compress
          Invoke-RestMethod -Uri $uri -Method Post -Body $bodyJson -ContentType 'application/json'
