name: Автосборка Music M test

on:
  workflow_dispatch:
    inputs:
      namevers:
        description: "Название релиза"
        required: true
        default: "🤖 Автосборка"
      descr:
        description: "Описание релиза"
        required: true
        default: "❌ Описание сборки отсутствует"
      release:
        description: "Выкинуть в релиз?"
        required: true
        default: false
        type: boolean
      prerelease:
        description: "Пререлиз?"
        required: true
        default: true
        type: boolean

  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Unpacked]
        platform: [x64]  # Собираем только x64, так как другие платформы требуют дополнительной настройки

    runs-on: windows-latest

    env:
      Solution_Name: "VK UI3"

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          node-version: 16
          fetch-depth: 0

      - name: Decode the pfx
        run: |
          $pfx_cert_byte = [System.Convert]::FromBase64String("${{ secrets.BASE64_ENCODED_PFX }}")
          $certificatePath = "${{ github.workspace }}\GitHubActionsWorkflow.pfx"
          [IO.File]::WriteAllBytes("$certificatePath", $pfx_cert_byte)

      - name: Обновить TOKEN_STAT_SLY
        run: |
          $repoName = "${{ github.repository }}".Split('/')[1]
          $content = Get-Content -Path "D:\a\$repoName\$repoName\VK UI3\StaticParams.cs"
          $updatedContent = $content -replace 'Environment.GetEnvironmentVariable\("TOKEN_STAT_SLY"\)', '"${{ secrets.TOKEN_STAT_SLY }}"'
          Set-Content -Path "D:\a\$repoName\$repoName\VK UI3\StaticParams.cs" -Value $updatedContent
          Write-Output $updatedContent

      - name: Install .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v2

      - name: Restore the application
        run: msbuild $env:Solution_Name /t:Restore /p:Configuration=$env:Configuration
        env:
          Configuration: ${{ matrix.configuration }}

      - name: Build the project (unpacked)
        run: |
          $platform = "${{ matrix.platform }}"
          Write-Host "Building for platform: $platform"
          
          msbuild $env:Solution_Name `
            /p:Configuration=$env:Configuration `
            /p:Platform=$platform `
            /p:PlatformTarget=$platform `
            /p:RuntimeIdentifier="win-$platform" `
            /p:AppxPackageBuildMode=None `
            /p:TOKEN_STAT_SLY="${{ secrets.TOKEN_STAT_SLY }}"
        env:
          Configuration: ${{ matrix.configuration }}

      - name: Remove the pfx
        run: |
          $certificatePath = "${{ github.workspace }}\GitHubActionsWorkflow.pfx"
          Remove-Item -path "$certificatePath"

      - name: Create ZIP archive
        run: |
          $version = "${{ steps.get_version.outputs.VERSION }}"
          $platform = "${{ matrix.platform }}"
          $sourceDir = "${{ github.workspace }}\${{ env.Solution_Name }}\bin\$platform\${{ matrix.configuration }}\"
          $zipPath = "${{ github.workspace }}\Output\${{ env.Solution_Name }}_${platform}_${version}.zip"
          
          if (Test-Path $sourceDir) {
            Write-Host "Creating ZIP archive for $platform from $sourceDir"
            Compress-Archive -Path "$sourceDir\*" -DestinationPath $zipPath -Force
          } else {
            Write-Host "Directory not found: $sourceDir"
            exit 1
          }
        shell: pwsh

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: WinUI3-App-ZIP
          path: ${{ github.workspace }}\Output\*.zip

      - name: Извлечь версию
        id: get_version
        run: |
          $repoName = "${{ github.repository }}".Split('/')[1]
          $csprojPath = "D:\a\$repoName\$repoName\VK UI3\VK UI3.csproj"
          $doc = New-Object xml
          $doc.Load((Convert-Path $csprojPath))
          $version = $doc.SelectSingleNode('//AppxPackageVersion').InnerText
          echo "::set-output name=VERSION::$version"
          echo "Версия: $version"
        continue-on-error: true
        if: github.event.inputs.release == 'true'

      # Остальные шаги (создание релиза, отправка в Telegram и т.д.) остаются без изменений
      # ...
